### ISSUE TITLE
unzipFileAtPath skips folders with accented characters

### ISSUE THREAD

**Issue by luisangelsm** [ZipArchive/ZipArchive#14]
I am using ssziparchive to extract zip files into the Documents directory of my ios application. If the path of the zipped files contains accented characters (f.e. á é í ó ú) they are skipped.

Sample zip file:

/
-- folder1/
-----file1
-----file2
-----file3
-- fólder2/
-----file1
-----file2
-- folder3/
-----file1
-----file2

Result:

/
-- folder1/
-----file1
-----file2
-----file3
-- folder3/
-----file1
-----file2

I don't know if I missing something or it is a bug.

Thanks.

**Comment by RadhakrishnanRakki** [comment]
I have same problem of Unzip the file and this library is skip the special character file.
Ex :--Place_de_l'OpeÔra.png
This file is skip the unzip process.If any update of sszipArchive library this issue realated.

**Comment by DanielHJA** [comment]
Hello!

Has this issue been resolved? I am experiencing the same problem.

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'

**Comment by jeevanRao7** [comment]
Even it is skipping files. Here is my thread https://stackoverflow.com/questions/44839858/ziparchiver-skips-for-file-with-accented-character-file-name

**Comment by Coeur** [comment]
@jeevanRao7 this issue was closed in 2012... please open a new ticket here on GitHub describing your steps (like you did on StackOverflow).
