### ISSUE TITLE
Corrupting small files after unpacking

### ISSUE THREAD

**Issue by K-Be** [ZipArchive/ZipArchive#143]
I've faced with strange behavior. If I unpack archive with my files, some of them will have 33 bytes size, but should be 21 byte. It happens only if them are in subdirectories (not in root directory of archive).
For example:

    sync.1
         backgrounds
                 order.json

If order.json is in sync.1, then all ok.

Before I will have unpacked the archive, order.json contains follow data:

       {
          "order":[1, 2]
       }
After I will have unpacked the archive order.json will have follow data:

      {
           "order":[1, 2]
      }slF®ç¿+^~.

I've created fork of this project and created some testCases https://github.com/K-Be/ssziparchive .
If you run testUnzipSmallWithPass, you will get success, but if you run testPassSync2File then you will get fail.

I couldn't find solution of this problem, but have some information. In the method unzReadCurrentFile exist variable "unz64_s* s" if I run testUnzipSmallWithPass, then uncompressed_size and compressed_size are same (21). If I run testPassSync2File then uncompressed_size = 21, but compressed_size=33.
May be problem in this place, because compressed_size will be returned from method as length of read bytes.

**Comment by K-Be** [comment]
I've found that this library: https://github.com/abbeycode/UnzipKit, also use MiniZip, but can correct unpack my archive. May be you have old version of MiniZip.

**Comment by istx25** [comment]
If you would create a PR with the appropriate improvements/fixes, that would be much appreciated!

**Comment by jhudsonWA** [comment]
I verified that MiniZip in this project is the latest version. There are some small changes, but mostly just to silence the warnings in the analyzer. My guess is it is not MiniZip causing this issue. Did not track it further.

**Comment by istx25** [comment]
Would you be able to solve the problem and create a PR, @jhudsonWA? It would be much appreciated.

**Comment by bartcone** [comment]
This issue was introduced by the PR in this [issue](https://github.com/soffes/ssziparchive/issues/16). Uncomment the code below and @K-Be's testPassSync2File test passes. It's not sufficient to just uncomment though, it causes other test failures which I didn't look into.

You can see this starting on line 1720 of unzip.c

I unfortunately don't have a lot of time to submit a patch, but hopefully this can put someone on the right track. I'd start by pulling in an untampered version of minizip. 

```objective-c
    // NOTE:
    // This bit of code seems to try to set the amount of space in the output buffer based on the
    // value stored in the headers stored in the .zip file. However, if those values are incorrect
    // it may result in a loss of data when uncompresssing that file. The compressed data is still
    // legit and will deflate without knowing the uncompressed code so this tidbit is unnecessary and
    // may cause issues for some .zip files.
    //
    // It's removed in here to fix those issues.
    //
    // See: https://github.com/samsoffes/ssziparchive/issues/16
    //
    
    /*
    if ((len>pfile_in_zip_read_info->rest_read_uncompressed) &&
        (!(pfile_in_zip_read_info->raw)))
        pfile_in_zip_read_info->stream.avail_out =
            (uInt)pfile_in_zip_read_info->rest_read_uncompressed;
     */
```

**Comment by jhudsonWA** [comment]
I'm working towards a big release next week, so I'm also out of time. But if no one has tackled it by then I can take a look. I had a bit of time last week and merged in a fresh copy of minizip and all seemed to compile fine. The only real changes were the code you highlighted there plus some code to muffle warnings from the analyzer. I'll see what I can do to get those other tests to pass.

**Comment by istx25** [comment]
@jhudsonWA Are you available now to work on this patch?

**Comment by jhudsonWA** [comment]
Still in crunch time, after July 1.

**Comment by jhudsonWA** [comment]
Closed? Was it fixed?

**Comment by istx25** [comment]
Please read #163.
