### ISSUE TITLE
Microsoft under compression under the OS and unpack failure

### ISSUE THREAD

**Issue by LiuSky** [ZipArchive/ZipArchive#152]
Microsoft under compression under the OS and unpack failure

**Comment by istx25** [comment]
Thanks for filing this issue, @LiuSky! Please feel free to create a PR with the related improvements/fixes.

**Comment by LiuSky** [comment]
I am sorry, I did not fix this bug, I do not know this problem is not due to the library caused

**Comment by LiuSky** [comment]
I am sorry, I did not fix this bug, I do not know this problem is not due to the library caused @istx25

**Comment by istx25** [comment]
Okay. I will look into it.
