### ISSUE TITLE
CocoaPods podspec file has not been updated

### ISSUE THREAD

**Issue by larryaasen** [ZipArchive/ZipArchive#156]
The CocoaPods podspec file has not been updated for a while so we cannot easily pickup these great changes that have been added recently. Will the podspec file and release tag be update soon?

**Comment by istx25** [comment]
Would you be able to do this for us, @adamyanalunas?

**Comment by adamyanalunas** [comment]
Sure! I'm at WWDC right now but will try to get to this at night or after WWDC.

**Comment by istx25** [comment]
@adamyanalunas: Lucky you! Have an awesome time at dub dub. :smiley:

**Comment by adamyanalunas** [comment]
@istx25 The latest tag is `v0.3.2`, which is pretty old. `master` has a lot of new commits but I don't feel comfortable making a new tag as I’m not sure where stable is on `master`. If a new tag is made I can update the `podspec` and see if I can push it up to the CocoaPods trunk.

**Comment by adamyanalunas** [comment]
@istx25 Also, I'll need @soffes to add me as an owner of the SSZipArchive podspec. That can be done by him running:

```
pod trunk add-owner SSZipArchive adam@yanalunas.com
```

This is a one-time deal. After I'm marked as an owner I'll be able to make new pod releases any time.

**Comment by rsanchezsaez** [comment]
What's the progress on this?

**Comment by scspijker** [comment]
As far as transferring credentials for the Cocoapod spec I don't know, but the biggest problem will be the new tag, as no current version of the master has been tested.

Please see #163

**Comment by istx25** [comment]
I will try to get in touch with @soffes via email to collect the CocoaPods credentials. I don't know how CocoaPods actually works as I have personally moved onto Carthage. I would need someone else to manage all future CocoaPod releases.

**Comment by istx25** [comment]
What's the status on this, @adamyanalunas? Have you tried to contact @soffes? I sent an email out but received no reply. I'll tweet him this issue.

**Comment by tbaranes** [comment]
Any news about this?

**Comment by nevyn** [comment]
@adamyanalunas If @soffes isn't replying, I'm sure one could ping the CP team and ask them to add anyone who is obviously a current maintainer of this library as an owner of the pod.

(Also interested in this issue as the current podspec'd SSZipArchive has tons of build warnings, and it's a dependency of my library Lookback)

**Comment by adamyanalunas** [comment]
Sam got back to me this morning and said he added me as contributor to this and the CocoaPods repo. If someone has a stable commit I'll make a new tag and get the podfile updated and submitted.

**Comment by rsattar** [comment]
The most recent stable release I found (and am vendoring out of my own (private for now) Cocoapod) is 28be5a67abd2aa939a2c055bf02a98e5f227ed73. Beyond that, the project won't compile.

**Comment by soffes** [comment]
@rsattar I can add you as a collab and cocoa pods owner if you and @adamyanalunas want to run with this. I haven't used this in years.

**Comment by larryaasen** [comment]
@rsattar Hey Riz: nice to see you on this comment thread. Would be nice to have someone update this pod for everyone.

**Comment by rsattar** [comment]
@soffes, sure that'd be great. I don't know much about the zlib C library, but this would be a good reason to learn it!

@larryaasen Small world!

**Comment by levigroker** [comment]
Hey all, thanks for continuing this project... I'm using CocoaPods and would love to see this updated. What's the status, and how can I help?

**Comment by adamyanalunas** [comment]
@levigroker et al: I've created branch (0.3.3)[https://github.com/ZipArchive/ZipArchive/releases/tag/v0.3.3] that points to 28be5a6, which is the last known good working state, as pointed out by @rsattar. 

The podspec is good to go but I don't have access to CocoaPods. If anybody here has contributor access you just need to clone this repo then run

```
pod trunk push --allow-warnings
```

The `--allow-warnings` is necessary as there are some things that need fixing, according to the CocoaPods linter, but I deemed them outside the scope of this issue. I'd rather have a pod that works with a few compiler warnings and out now than a warning-free pod but released who knows when.

Does anyone have `pod trunk push` privileges? I asked @soffes to add me but that hasn't yet happened.

**Comment by levigroker** [comment]
Thanks @adamyanalunas. Perhaps @soffes will step up.

**Comment by adamyanalunas** [comment]
![kw4n56e](https://cloud.githubusercontent.com/assets/366221/10185491/688b9a62-66fd-11e5-97f3-39e7c2035f2a.png)

Good news, everyone! I've pushed the `0.3.3` podspec for SSZipArchive!

>  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/0d3bf4ea52ede10b05701503d6028a632e503439/Specs/SSZipArchive/0.3.3/SSZipArchive.podspec.json
>  - Log messages:
>    - September 29th, 22:55: Push for `SSZipArchive 0.3.3' initiated.
>    - September 29th, 22:55: Push for `SSZipArchive 0.3.3' has been pushed (1.767049639 s).

That's, right _SSZipArchive_, not _ZipArchive_. Turns out there's already a [ZipArchive](https://github.com/mattconnolly/ZipArchive) maintained by @mattconnolly. That was preventing me from pushing up a new `ZipArchive.podspec` because `pod trunk` believed I was trying update Matt's podspec, not this one.

For anyone interested in such things, if you are trying to push a pod to trunk and it isn't working, you can check if you're a pod owner by running

```
pod trunk info SSZipArchive (or whatever pod)
```

Apologies to @soffes who did give me pod trunk access when he said it was done. I assumed I had no access when `pod trunk` told me I had no permissions. Lessoned relearned for the 10,000th time: confirm assumptions first.

Going to close out this issue and open a few more related-related issues. Thanks for everyone's persistence and patience!
