### ISSUE TITLE
Does ZipArchive support unzipping of .tar.gz files?

### ISSUE THREAD

**Issue by iori57** [ZipArchive/ZipArchive#159]
I've setup the library in my project but when I try to unzip a .tar.gz file downloaded online, it gives an error "failed to open zip file"

Thanks!

**Comment by istx25** [comment]
Not at the moment.

**Comment by istx25** [comment]
Read #163.

**Comment by fgiraffe** [comment]
Is .gz support still being considered for a 2.0 release? (I read #163 but it was not mentioned there).
Thanks in advance.
