### ISSUE TITLE
Possible to get 0.3.3 soon? 

### ISSUE THREAD

**Issue by rsattar** [ZipArchive/ZipArchive#162]
I'd love to use ZipArchive with this update from a few months ago:

https://github.com/ZipArchive/ZipArchive/commit/a9ece3bef78540661cb63f86436f1282f18f1a26

so that I can tell the name of the file(s) that were unzipped.

Thanks,
Riz

**Comment by istx25** [comment]
There is a lot of work to do until the next stable version can be released. Please read #163.

**Comment by adamyanalunas** [comment]
@rsattar `0.3.3` [just shipped](https://github.com/ZipArchive/ZipArchive/issues/156)! However, it is based off a tag pointed a bit further back in the history of this repo as the `2.0` work in master isn't stable.

**Comment by rsattar** [comment]
Thanks!
