### ISSUE TITLE
2.0 Kickoff

### ISSUE THREAD

**Issue by istx25** [ZipArchive/ZipArchive#163]
As you may know, @soffes has formed a new Github organisation for ZipArchive. (previously called SSZipArchive. We have been planning to build a 2.0 version that includes wide-spread improvements. We're looking at modern Objective-C, better Swift bridging, nullability and more. I am looking for people who would like to contribute to the new version to start brainstorming.

So let's start that here! :smiley:

**Comment by istx25** [comment]
I personally think that it is time to put `minizip` to bed and either find something that's better or write our own specifically for ZipArchive. Our current version of ZipArchive is using a lot of legacy Objective-C and C technologies.

**Comment by istx25** [comment]
@jhudsonWA What do you think?

**Comment by jhudsonWA** [comment]
Got it. minizip does seem to be the defacto for similar projects. However, it also has not been updated for years.

**Comment by jhudsonWA** [comment]
If we are brainstorming, I would love a way to be able to get progress during the unzipping process for each file and not just an event once a file is unzipped or zipped.

**Comment by istx25** [comment]
I would think that in between the time that `minizip` went inactive, a lot of improvements to that area probably exist. I think that we should build a modern `minizip`-like library that we can use for ZipArchive (2.0). Maybe that could be a repository/project on its own?

**Comment by istx25** [comment]
We should also plan out what features we would like in the 2.0 version. If there are any unnecessary ones that exist in v0.3.2. Most of the existing features will be remade for modern Objective-C and a style guide.

**Comment by scspijker** [comment]
It seems that the ZIP format hasn't really changed over the last 5 years, so the fact that Minizip hasn't been updated recently would not disqualify it from being a well proven and tested library :)

However, I do think ZipArchive should get a 2.0 release, and the main thing would be to first test all the pull requests that have (largely untested) been granted recently.

Swift support could be a version 3.0. Cleaning up and testing current HEAD would be most important imho.

**Comment by istx25** [comment]
Sorry for the delayed response! I've been in the middle of an overseas move. 

I agree with @scspijker that we should fix the Objective-C version and improve the codebase. I am sorry if some of the recently PRs have been granted without being tested. We also need to rename all classname/references from `SSZipArchive` to just `ZipArchive` as @soffes recently moved the project into its own Github Organisation.

**Comment by istx25** [comment]
As previously talked about, I have been working on fixing the Objective-C version before we move onto 3.0 features. I have done the following:

- [x] Created a new framework project with the name "ZipArchive".
- [x] Rewrote portions to ensure legacy Objective-C was removed.
- [x] Cleaned up miscellaneous bits and bobs to ensure we're following Apple's style guide.
- [x] Up-to-date sample code in README.md.
- [x] Added support for Carthage.

Some of the tests are still failing, but I am going to try to fix them in the coming week, but please feel free to contribute if you would like to. I am currently in a contract and that will have to take priority until it's finished. Let's try to fix what we have before adding additional functionality to ZipArchive! :boom: :+1:

**Comment by istx25** [comment]
I would appreciate any PRs that fix the following broken tests: :kissing_smiling_eyes: :beer:

```objective
- (void)testMultipleZipping;
- (void)testSmallFileUnzipping;
- (void)testUnzippingWithSymlinkedFileInside;
- (void)testUnzippingWithRelativeSymlink;
- (void)testUnzippingWithCancel;
```

**Comment by arthurj58** [comment]
Hello  
How can we solve error  

Ld /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos/Example.app/Example normal arm64
    cd /Users/arthur/Downloads/ZipArchive-master
    export IPHONEOS_DEPLOYMENT_TARGET=7.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -L/Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos -F/Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos -filelist /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Intermediates/ZipArchive.build/Debug-iphoneos/Example.build/Objects-normal/arm64/Example.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=7.1 -Xlinker -dependency_info -Xlinker /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Intermediates/ZipArchive.build/Debug-iphoneos/Example.build/Objects-normal/arm64/Example_dependency_info.dat -o /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos/Example.app/Example

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_Main", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by istx25** [comment]
@arthurj58 Create a new issue please. This is a thread about the future of this project.
