### ISSUE TITLE
some precision  warn

### ISSUE THREAD

**Issue by gtgg** [ZipArchive/ZipArchive#166]
SSZipArchive/SSZipArchive/minizip/ioapi.c:195:33: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'long' [-Wshorten-64-to-32]
  SSZipArchive/SSZipArchive/SSZipArchive.m:85:37: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
SSZipArchive/SSZipArchive/SSZipArchive.m:85:59: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
 SSZipArchive/SSZipArchive/SSZipArchive.m:121:39: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
SSZipArchive/SSZipArchive/SSZipArchive.m:121:61: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
SSZipArchive/SSZipArchive/SSZipArchive.m:297:37: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
SSZipArchive/SSZipArchive/SSZipArchive.m:297:52: warning: implicit conversion loses integer precision: 'ZPOS64_T' (aka 'unsigned long long') to 'NSInteger' (aka 'int') [-Wshorten-64-to-32]
 Headers/Private/CocoaLumberjack/DDTTYLogger.h:44:22: warning: unused function 'DDMakeColor' [-Wunused-function]

**Comment by istx25** [comment]
Darn. PRs welcome.

**Comment by istx25** [comment]
Fixed.
