### ISSUE TITLE
memory leaks when unzipping asynchronously

### ISSUE THREAD

**Issue by Chaolong** [ZipArchive/ZipArchive#167]
my program uses method :+ (BOOL)unzipFileAtPath:(NSString *)path
		  toDestination:(NSString *)destination
		progressHandler:(void (^)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
	  completionHandler:(void (^)(NSString *path, BOOL succeeded, NSError *error))completionHandler;
when the complete block executed ,about 30 mb memory is not deallocated for 40mb zip file.But later Every time I invoke this method to unzip 40mb files, it adds up 10mb memory leaks.
How can I solve this problem?

**Comment by istx25** [comment]
:+1:
