### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by arthurj58** [ZipArchive/ZipArchive#171]
Hello

How can we solve error

Ld /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos/Example.app/Example normal arm64
cd /Users/arthur/Downloads/ZipArchive-master
export IPHONEOS_DEPLOYMENT_TARGET=7.1
export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -L/Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos -F/Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos -filelist /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Intermediates/ZipArchive.build/Debug-iphoneos/Example.build/Objects-normal/arm64/Example.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=7.1 -Xlinker -dependency_info -Xlinker /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Intermediates/ZipArchive.build/Debug-iphoneos/Example.build/Objects-normal/arm64/Example_dependency_info.dat -o /Users/arthur/Library/Developer/Xcode/DerivedData/ZipArchive-efqrtkmeqpeelqfpjjchjunubpzo/Build/Products/Debug-iphoneos/Example.app/Example

Undefined symbols for architecture arm64:
"OBJC_CLASS$_Main", referenced from:
objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rsattar** [comment]
It looks like the "Example" project doesn't declare any import (explicit or implicit) of the "ZipArchive" framework target.

**Comment by jhudsonWA** [comment]
Updated the pod spec for the configs and checked in. Seems to work now.
