### ISSUE TITLE
Why the maximum number of files for archiving 252?

### ISSUE THREAD

**Issue by DimonDeveloper** [ZipArchive/ZipArchive#173]
I'm trying to archive a folder with 2000 files. But archived only 252. Why?

And if you choose 2000 files separately, still only 252 files are added to the archive.

**Comment by istx25** [comment]
What version of the library are you using?

**Comment by DimonDeveloper** [comment]
@istx25 last version, downloaded couple hours ago.

**Comment by DimonDeveloper** [comment]
@istx25  You know what's the problem?

**Comment by istx25** [comment]
No I don't. I will have to look into it. Any ideas, @scspijker?

**Comment by scspijker** [comment]
No.

However, the current HEAD is not stable. Please try again with the last tag.

https://github.com/ZipArchive/ZipArchive/releases/tag/v0.3.2

The files, are they just 2000 files in a single folder?

**Comment by DimonDeveloper** [comment]
@scspijker Yes, all the 2000 files in a single folder.

**Comment by 14017831** [comment]
The author forgot to close file handler in the method
writeFileAtPath:(NSString *)path withFileName:(NSString *)fileName
Please add "fclose(input)" on line 631 in Main.m

**Comment by DimonDeveloper** [comment]
@14017831 almost correct. Need put "fclose(input)" after this lines:
 
```
while (!feof(input)) {
        len = (unsigned int) fread(buffer, 1, CHUNK, input);
        zipWriteInFileInZip(_zip, buffer, len);
    }
```

In the end of this method:
```writeFileAtPath:(NSString *)path withFileName:(NSString *)fileName```

**Comment by istx25** [comment]
@DimonDeveloper I'm no longer contributing. Please feel free to submit a PR and one of the other contributors will deal with it.
