### ISSUE TITLE
Main class called "Main" instead of "ZipArchive" ?

### ISSUE THREAD

**Issue by Autoc0diq** [ZipArchive/ZipArchive#176]
So the class has been renamed to Main?
Why?

**Comment by tbaranes** [comment]
I agree, it would be better to call it "ZipArchive"...

**Comment by catlan** [comment]
In the need of a **Cocoa** ZIP reader that can handle unzipping memory based zips and list filenames in the zip archive I went ahead and created https://github.com/catlan/LOZIPFileWrapper/

@Autoc0diq ;)

**Comment by nevyn** [comment]
Yeah, this is a major namespacing issue. The name is not prefixed, and the name has nothing to do with the library. Why not call it SSZipArchive? (note that "ZipArchive" is also taken by *several* other libraries)

**Comment by mikeCalvir** [comment]
Plus one on this, I was surprised to discover it had changed, I came here looking for an update just to fix new Xcode 7 compiler warnings for the previous SSZipArchive.m and .h files, and now it is called "Main"? Why would you do that to us? :-)

**Comment by timkettering** [comment]
Agreed, Main is a poor choice of name for the class, unless there's an justification we havent heard of yet.

**Comment by colincameron** [comment]
Came here looking for a Zip library for iOS. Why was the `SSZipArchive` class renamed to `Main` a few months back? This is a terrible naming choice! Every Objective-C app already has a `main.m` file!

**Comment by olympianoiseco** [comment]
Yes, this is a really bad naming choice, and completely against convention.

**Comment by jhudsonWA** [comment]
This change has been reversed.
