### ISSUE TITLE
Cannot use for a Carthage package

### ISSUE THREAD

**Issue by fumitoito** [ZipArchive/ZipArchive#183]
I tried to use ZipArchive as a Carthage package, but cannot import it with a following error at `Main.h`.

`'unzip.h' file not found`

here is my steps. Do I need more steps to use ZipArchive ?

1. add a line in my Cartfile `github "ZipArchive/ZipArchive" "master"`
1. run `carthage update`
1. add `import ZipArchive` at the top of my swift file

**Comment by jhudsonWA** [comment]
I'll take a look @fumitoito. We are kind of waiting for Carthage to be updated to support Swift 2.0. I'll leave this open.

**Comment by smumryak** [comment]
Created pull request with carthage support. Basically, Carthage supports swift 2.0 for a long time since it's implemented in swift. Resulting framework (which was build by Carhtage) is used in my swift project.

https://github.com/ZipArchive/ZipArchive/pull/218
