### ISSUE TITLE
Revoke or surpass 1.0 podspec

### ISSUE THREAD

**Issue by adamyanalunas** [ZipArchive/ZipArchive#184]
Although `0.3.3` [just shipped](https://github.com/ZipArchive/ZipArchive/issues/156) there is a submitted pod for version `1.0` that looks to be the first version published. Because CocoaPods follows semver and following versions reverted to `0.x` number that extremely old `1.0` version is what is seen in [pod search resutls](https://cocoapods.org/?q=ssziparchive).

The `pod trunk` documentation doesn't show a way to revoke a pushed podspec, although it may be possible by contacting the CocoaPods team. It may be easier – and more correct – to jump back to the `1.x` versioning. `0.3.3` is the first release in over a year without any critical issues open.

Can I get some votes for or against making a `1.0.1` tag and corresponding podspec update to surpass the old version? What do you think, @istx25?

**Comment by istx25** [comment]
Hey @adamyanalunas. I'm no longer maintaining this project. I'll leave it to you to decide. :smiling_imp:

**Comment by jhudsonWA** [comment]
I vote we do this. Want me to handle it @adamyanalunas?

**Comment by jhudsonWA** [comment]
I think we should do this. I will bump the podspec to 1.0.1 with a new release on Monday.

**Comment by jhudsonWA** [comment]
Bumped spec and release to 1.0.1.

Updating spec repo `master`
  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/93bf2fa90f0899c34b1198d66efc9cf582b2c42b/Specs/SSZipArchive/1.0.1/SSZipArchive.podspec.json
  - Log messages:
    - November 16th, 10:32: Push for `SSZipArchive 1.0.1' initiated.
    - November 16th, 10:32: Push for `SSZipArchive 1.0.1' has been pushed
    (1.273899578 s).

**Comment by jhudsonWA** [comment]
This also fixes the issue where the spec could not be opened on the cocopods site.
