### ISSUE TITLE
Needs cocoapods support with use_frameworks!

### ISSUE THREAD

**Issue by tychop** [ZipArchive/ZipArchive#185]

**Comment by joshuatbrown** [comment]
Agreed. Any idea when this will be ready?

**Comment by inamiy** [comment]
I found nearly coming ver 0.4.0 will fix CocoaPods + dylib issue (see #191 & #194).
Try pointing to git's podspec for a while:

```
pod 'SSZipArchive', :git => 'https://github.com/ZipArchive/ZipArchive', :commit => '1bb8a98'
```

**Comment by jhudsonWA** [comment]
I tried to push the pod spec but it seems I don't have rights, so I contacted @soffes to see if I can get the needed rights. For now, I did create a 0.4.0 release with all of these changes.

**Comment by ssoper** [comment]
May need to contact someone from the Cocoapods team like @segiddins. Also, when trying to find the pod on the Cocoapods site I can only see a 1.0 version which then fails to link or open.

https://cocoapods.org/?q=ssziparchive

**Comment by jhudsonWA** [comment]
Lets give @soffes a few more days to respond. He is still owner of this project, if I don't hear anything I'll see if I can contact Cocoapods directly

**Comment by jhudsonWA** [comment]
This should be resolved. The cocopods is now updated.
