### ISSUE TITLE
Fork or roll in changes

### ISSUE THREAD

**Issue by ssoper** [ZipArchive/ZipArchive#191]
So lots of folks have been having issues with SSZipArchive on Pods 0.39 and Swift (#185). I've got it working in a fork (https://github.com/WPMedia/WPZipArchive). I had to roll back all changes made since v0.3.3 due to some bugs that were introduced (#176, #178) and move some files around. Also did a bit of housecleaning and tests are passing again (#177). 

Question is, do the maintainers want to try and pull my changes in or do we part ways and I create a new Pod, WPZipArchive, which will focus on Pods compatibility, stability and Swift interoperability?

**Comment by timkettering** [comment]
I would say go your own way.  The maintainer for this project has been non-repsonsive for months now.

**Comment by jhudsonWA** [comment]
Agreed. There are a couple of us who got pulled into the ZipArchive org, usually without asking, by @istx25 but that user seems to have removed themselves from the project. Hate to say it but it seems unless @soffes comes back or hands this one off to someone else it does not look good for the future of this project.

With that said.. There are a couple of of us who are still members of the ZipArchive org. If you want to post your changes as a pull request I'll pull them in. 

The rename of the main class to Main seems to have hosed everyone and I have no idea why it was done. 

If you've fixed it, we should roll it in.

**Comment by istx25** [comment]
@jhudsonWA That's not exactly fair... I added the people who were collaborators on the project when it was hosted on @soffes account. The reason I removed myself from this project was because I was the only one maintaining it and I don't even use the project. But either way, please feel free to role back or merge in a repair.

**Comment by istx25** [comment]
I apologise for the inconveniences that I may have caused. There were over 100 open issues when I started contributing to the project.

**Comment by jhudsonWA** [comment]
@istx25, No, you are right, I may have been venting my frustrations because the project seemed to have stalled. I didn't realize over the past few months you had left until today, I thought you had just gone silent. Oops. Sorry for pulling you back in with a @ mention.

I wasn't a contributor in the past, except in the issues, but I do use the project so I can help and glad I was added to the org.

**Comment by ssoper** [comment]
Ok I created a branch that can be merged in. Unfortunately two more commits have been brought in to SSZipArchive master since I made my changes so a branch will need to be created off 1f7d737 and my changes can be rolled into there. Other downside is that my branch doesn't have Carthage compatibility. I attempted to install Carthage on my local machine so I could re-implement but am unable to due to lack of Swift 2 compatibility. 
https://github.com/Carthage/Carthage/issues/807

Here's the compare I created
https://github.com/ZipArchive/ZipArchive/compare/1f7d737...WPMedia:feature/ssziparchive

Please let me know if I can be of any further help.

**Comment by ssoper** [comment]
Suggest you branch current master to something like 'carthage' and then update your README to reflect that for the Carthage installation instructions
`github "ZipArchive/ZipArchive" "carthage"`

**Comment by jhudsonWA** [comment]
Thanks @ssoper! I'll take a look at this Monday morning.

**Comment by jhudsonWA** [comment]
I reverted the two pull request I have put in. I'll merge your change in and then reapply.

**Comment by jhudsonWA** [comment]
Pull request merged in. Thanks again @ssoper. I'll look into the 'carthage' issue once 2.0 support is added. I've been waiting for it for another project.

**Comment by ssoper** [comment]
Excellent! Don't forget to push the pod (0.4.0) :boat:

**Comment by jhudsonWA** [comment]
I will try. Need to figure out if I have the correct rights on the pods side of things.

**Comment by inamiy** [comment]
Thanks for this great fix! :star::star::star::star::star: to @ssoper !

BTW, is Carthage support still existing?
If not, we might want to have another xcodeproj for just building framework (not from CocoaPods).

And please `pod trunk push` :)

**Comment by jhudsonWA** [comment]
I'll try to first thing in the morning. Need to get to my Mac. 

Also for Carthage we will tackle that next.
