### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by ssoper** [ZipArchive/ZipArchive#195]
Now that tests are once again passing in master (#191) why not integrate this repo with Travis CI to ensure new commits don't break the build.

https://github.com/travis-ci/travis-ci

I know it's been a busy past couple of days so let me know if I can be of any assistance here.

**Comment by jhudsonWA** [comment]
Good idea. Do you want to create a .travis.yml file and send a pull request. I'm working to get travis-ci hooked up to this project.

**Comment by ssoper** [comment]
After pulling this in you'll need to go setup an account on travis-ci.org and enable this repo. Don't forget to update the README to point to the correct badge.

Here's how it looks on my fork
https://github.com/ssoper/ZipArchive

Let me know if you need any add'l help getting this working.

**Comment by jhudsonWA** [comment]
Thanks. I also requested access to this organization already from travis-ci.org. Did that a few days ago. I think it's another thing we are waiting on @soffes for approval.

**Comment by jhudsonWA** [comment]
This happened but was never closed.
