### ISSUE TITLE
symbolic link is not supported while unzip

### ISSUE THREAD

**Issue by boalove** [ZipArchive/ZipArchive#201]
symbolic link is not supported while unzip, please see the variable fileIsSymbolicLink, please check it. and it is wrong while merging.

**Comment by boalove** [comment]
in the file SSZipArchive.m, line 200:
	            fileIsSymbolicLink = NO;
change it to : 
	            fileIsSymbolicLink = YES;
.

**Comment by Coeur** [comment]
https://github.com/ZipArchive/ZipArchive/issues/52
