### ISSUE TITLE
Will 0.4.0 be distributed via CocoaPods?

### ISSUE THREAD

**Issue by parski** [ZipArchive/ZipArchive#202]
I noticed that this product was updated to 0.4.0 almost two weeks ago. I'm using it in a pod of my own and tried specifying the following in the podspec:

```ruby
s.dependency 'SSZipArchive', '~> 0.4.0'
```

The terminal output was:

```bash
[!] Unable to satisfy the following requirements:

- `SSZipArchive (~> 0.4.0)` required by `MyPod (0.1.0)`
```

I tried removing the version specification from my podspec and the relevant output of a pod install looked like this:

```bash
Installing SSZipArchive (0.3.3)
```

It seems that 0.4.0 is not available in the CocoaPods repo. Will it be available or should I stick to 0.3.3?

**Comment by jhudsonWA** [comment]
I'm trying to get rights so I can push it. The owner of this project has sadly moved on. I do have contributor rights so I'm going to see if I can work directly with the cocopod folks today.

**Comment by jhudsonWA** [comment]
@adamyanalunas Adam, looking again at the cocopod I see that you have access. Can you update the trunk to .4.0?

**Comment by adamyanalunas** [comment]
@jhudsonWA I'll take a look.

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by adamyanalunas** [comment]
@jhudsonWA Don't have push access at my work machine but I should at home. I'll give it a shot later tonight and update this issue.

**Comment by jhudsonWA** [comment]
According to cocopods the adam@yana... account has access.

Thanks again Adam!

**Comment by adamyanalunas** [comment]
>  - Data URL: https://raw.githubusercontent.com/CocoaPods/Specs/81579b4cb4456e9e38d3e37060dacd229db5574a/Specs/SSZipArchive/0.4.0/SSZipArchive.podspec.json
>  - Log messages:
>    - November 11th, 22:05: Push for `SSZipArchive 0.4.0' initiated.
>    - November 11th, 22:05: Push for `SSZipArchive 0.4.0' has been pushed (1.105537993 s).

It'll take a little while but the podspec has been pushed. Closing issue.

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by parski** [comment]
👍

**Comment by jhudsonWA** [comment]
@adamyanalunas as a side note, any chance you can add my address to the list of who can push? I'm the second member of this org.

**Comment by adamyanalunas** [comment]
@jhudsonWA I'll take a look tonight when I'm at my home machine.

**Comment by jhudsonWA** [comment]
Thanks :)

**Comment by adamyanalunas** [comment]
@jhudsonWA I'll need your email address (send it to me however you like) to add you.

**Comment by jhudsonWA** [comment]
joshua

**Comment by jhudsonWA** [comment]
joshua.hudson at gmail 

Let me know when it's added.

Thanks!

**Comment by adamyanalunas** [comment]
@jhudsonWA It is done.

**Comment by jhudsonWA** [comment]
Nice. Thanks! I'll remove my email from the last comment then :)
