### ISSUE TITLE
Carthage don't know how to build

### ISSUE THREAD

**Issue by fernandodev** [ZipArchive/ZipArchive#203]
`Dependency "ZipArchive" has no shared framework schemes`

How can I fix it?

i'm using: `github "ZipArchive/ZipArchive" >= 0.4.0`

**Comment by jhudsonWA** [comment]
This project does not Carthage support yet. It's planned

**Comment by Alexey-Matjuk** [comment]
@fernandodev temporary solution:
• `carthage update`
• `pod update` for **ZipArchive**
• `carthage build`

**Comment by jhudsonWA** [comment]
Can you try again? We updated the pod spec and I'm curious if that fixes Carthage.

**Comment by fernandodev** [comment]
@jhudsonWA Now I'm using ZipArchive (master) via Podfile. I abandoned Carthage, but I'll test when I get some free time ;)

**Comment by jhudsonWA** [comment]
Great :)

**Comment by fernandodev** [comment]
@jhudsonWA Hi, 

I got the same issue :(

```shell
*** Fetching ZipArchive
*** Checking out ZipArchive at "7b2ccbb2b60339396581f40adfcccaceb0b4609e"
*** xcodebuild output can be found in /var/folders/f3/57gqn_392td41jqprhyqm8q00000gp/T/carthage-xcodebuild.IxG10m.log
Dependency "ZipArchive" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ZipArchive/ZipArchive/issues/new
```
In [Shared schemes](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework) I saw that is necessary to push `.xcodeproj` and respective framework build scheme therefore Carthage will know how to build ZipArchive.

**Comment by jhudsonWA** [comment]
Interesting. Ok I'll take a look.

**Comment by andrewjackman** [comment]
Carthage requires an Project.xcodeproj directory that contains a shared scheme that it can build a framework from. So firstly you need a checked-in xcodeproj...

**Comment by jhudsonWA** [comment]
If anyone wants to submit a PR for this it would be considered. I've always just used cocoapods and don't have much experience with Carthage. Last time i tried it there was incompatibilities between it and Swift 2.0 projects.

**Comment by jhudsonWA** [comment]
Ok, latest version released with full carthage support. Thanks to all who submitted PRs!
