### ISSUE TITLE
Project Future

### ISSUE THREAD

**Issue by jhudsonWA** [ZipArchive/ZipArchive#204]
Hey all. I've tried to get a hold of the project owner @soffes  via email several times, twitter and on here and have gotten no response over the last two weeks. This is making it so I can't update the cocopods, hook up travis-ci etc.

Does anyone have any opinions on how best to continue this project in an official way. I know I can fork the project but we still have the issue that I can't update cocopods etc for the SSZipArchive project name.

Would anyone support a new official fork with a new name? And if yes, any ideas what that name should be?

I could do the fork then update this project's readme to point to the new one.

Ideas?

**Comment by DimonDeveloper** [comment]
Here are the names I came up with:
Zipper
Zippy
Zipest
Zippiest
ZipestLib
Zips

**Comment by fernandodev** [comment]
ZipZap
LittleZip
ZipIt
Zippah
YoZip
ZipArch
ZippiZ

**Comment by jhudsonWA** [comment]
Nice. Keep them coming.

**Comment by koenpunt** [comment]
Some people do have a life outside of github. So writing-off someone who hasn't responded in 2 weeks (what are 2 weeks anyways?) in regard to his opensource project seems not the right thing to do

**Comment by fernandodev** [comment]
@koenpunt I agree with you. I think it's better to add some admins to @Ziparchive organisation that are able to publish in cocoapods. 

Anyway, Lib still outdated :(

**Comment by jhudsonWA** [comment]
@koenpunt I also agree. But It's only been two weeks for me. The previous person who was trying to get this project revived also could not get him to respond. The last activity from the project owner was 1 year ago.

I would love if this project org just got more admins and we were granted rights to post to cocopods. However, so far without contact from the current owner that is not possible. So we are stuck without either getting contact from him or spinning off the project and hoping folks follow.

**Comment by jhudsonWA** [comment]
An update. I was able to find one other person who is not a owner of the project but does have cocopods update rights. Hoping that pans out, and we can get them to update the spec. If we can update the cocopod we are good to go as I do have member right to the project so work can continue here.

**Comment by jhudsonWA** [comment]
Putting this on hold for now, was able to find someone who could update the pod.
