### ISSUE TITLE
testUnzippingTruncatedFileFix Test fails after AES support drop #199

### ISSUE THREAD

**Issue by jhudsonWA** [ZipArchive/ZipArchive#211]
After merging in the upgrade to mini zip 1.1 with AES support from PR #199 all tests pass but:
testUnzippingTruncatedFileFix

The original fix was described here. #16 

In minizip 1.1 this fix no longer works. Keeping the code commented out mentioned in #16 makes the tests testUnzippingWithSymlinkedFileInside and testUnzippingWithUnicodeFilenameInside never finish running. 

For now I've uncommented the fix for #16, as all the other improvements are worth the one test failing. But I would love some pull requests if anyone can make that test happy again.

![screen shot 2015-11-24 at 10 36 23 am](https://cloud.githubusercontent.com/assets/702446/11376744/44a6257a-9297-11e5-83f9-9c821b11f3cf.png)

@SLBoat any ideas? Great work by the way with the other fixes. I had to make some changes to your PR to make everything compile, but it's happy now.

**Comment by jhudsonWA** [comment]
It's this area: unzip.c in the minizip folder:

'''
 if (pfile_in_zip_read_info->raw) {
        if (len > pfile_in_zip_read_info->rest_read_compressed + pfile_in_zip_read_info->stream.avail_in)
            pfile_in_zip_read_info->stream.avail_out = (uInt)pfile_in_zip_read_info->rest_read_compressed +
                                                       pfile_in_zip_read_info->stream.avail_in;
    } else {
        
        // NOTE:
        // This bit of code seems to try to set the amount of space in the output buffer based on the
        // value stored in the headers stored in the .zip file. However, if those values are incorrect
        // it may result in a loss of data when uncompresssing that file. The compressed data is still
        // legit and will deflate without knowing the uncompressed code so this tidbit is unnecessary and
        // may cause issues for some .zip files.
        //
        // It's removed in here to fix those issues.
        //
        // See: https://github.com/ZipArchive/ziparchive/issues/16
        //
        
        /*
        
         
         FIXME: Upgrading to minizip 1.1 caused issues here, Uncommented the code that was commented before. 11/24/2015
         */
        
        if (len > pfile_in_zip_read_info->rest_read_uncompressed)
            pfile_in_zip_read_info->stream.avail_out = (uInt)pfile_in_zip_read_info->rest_read_uncompressed;
        
         
    
    }
'''

**Comment by Coeur** [comment]
I consider it done in #391.

**Comment by Coeur** [comment]
My fix may have interfered with #36. So I'm reopening for investigation.
