### ISSUE TITLE
Empty Directories Are Ignored

### ISSUE THREAD

**Issue by jasonboggess** [ZipArchive/ZipArchive#215]
Trying to turn a .pages folder into a .pages.zip file. Often the pages folder will have an empty data directory. When compressed with this library, the empty directory will disappear.

**Comment by jhudsonWA** [comment]
I'll see if there is something we can do, but PR's welcome.

**Comment by jasonboggess** [comment]
Not exactly sure how to fix (wish I did). I tried adding an empty file to the directory (which worked), but modifies the end file.

**Comment by jhudsonWA** [comment]
Ok. Is this behavior in current release or master? Or both?

**Comment by jasonboggess** [comment]
I believe both. I pointed my podsfile to the git repo just to be sure I had the latest.

**Comment by jasonboggess** [comment]
Here's an example pages file with and empty directory http://www.filedropper.com/essaypages

**Comment by jhudsonWA** [comment]
Thanks!

**Comment by bogo** [comment]
This should be resolved by #25.

**Comment by bogo** [comment]
This should be resolved by #250.
