### ISSUE TITLE
Create Zip Progress

### ISSUE THREAD

**Issue by MattTimmons** [ZipArchive/ZipArchive#220]
It would be awesome to have a delegate callback for creating a zip with progress.
Cheers,
Matt

**Comment by jhudsonWA** [comment]
PR's welcome. We don't have a lot of active development on this library anymore so any community involvement is welcome.

**Comment by Jacubeit** [comment]
I happen to stumble upon:
http://stackoverflow.com/questions/30232207/howto-unzip-a-big-zip-file-containing-one-file-and-get-the-progress-in-bytes-wit

**Comment by liufsd** [comment]
Also need this
+1

**Comment by Davidde94** [comment]
Just implemented this and submitted a pull request

**Comment by jhudsonWA** [comment]
Merged @Davidde94's PR. Will be a released as v1.7 soon.
