### ISSUE TITLE
Why I got a 0 file archive when I zip a folder? in iOS. 

### ISSUE THREAD

**Issue by bytegh** [ZipArchive/ZipArchive#224]
hi guys:
merry xmas.

as I test these days. I always got a 0 file archive when I zip a folder which has about 80 files in it.
In my app, I always archive a data folder and upload to server side, when the app is in background. recently, I found sometimes the library always gave me a 0-file archive file. I use the newest version which is the same. the archive will always be 0 until I relaunch the app.

Did you guys found this issue? 

thanks! 

BTW: I archive the folder in background-thread

**Comment by jhudsonWA** [comment]
We have had reports of this happening if the folder is empty. Are you trying latest release version or pull from master?

**Comment by RussellXY** [comment]
I had the same problem, dose anybody know how to fix it?

**Comment by jhudsonWA** [comment]
Would welcome a PR for a fix if anyone has any ideas. I am low on time these days.

**Comment by jhudsonWA** [comment]
Please try latest version.
