### ISSUE TITLE
Zip with password cannot unzip by Archive Utility.app, /usr/bin/unzip, etc.

### ISSUE THREAD

**Issue by spahol** [ZipArchive/ZipArchive#228]
```
I'm working on xcode7.2
I found that the zip file with password protection can unzip by SSZipArchive normally, But it cannot unzip by normal Finder on Mac !! Why !!
Anyone please suggest me, how make zip with password can work with both?
```

**Comment by PjotrC** [comment]
Same for me: if I zip with password, the created archive cannot be extracted on OS X, as well as on Windows. On Windows I could manage to unzip the archive by using WinRar.

**Comment by liufsd** [comment]
Also trouble with this : https://github.com/ZipArchive/ZipArchive/issues/303
I have test this library https://github.com/mattconnolly/ZipArchive ,it work success.But it can not keep the dict folder.

**Comment by jhudsonWA** [comment]
I'll see what I can do.

**Comment by Coeur** [comment]
Title edited to reflect the name of the app used by default by Finder:
`/System/Library/CoreServices/Applications/Archive\ Utility.app`

**Comment by Coeur** [comment]
SSZipArchive is using AES encryption by default, which is not supported by Archive Utility.
What we could do is to offer the choice of encryption (with or without AES).
Unfortunately, it is currently configurable at build time only (with C flag HAVE_AES).

Possible compression methods that I can see for curfile64_info->method:

Z_DEFLATED == 8
Z_BZIP2ED == 12
AES_METHOD == 99

I checked that keka is using Z_DEFLATED by default and that we are using AES_METHOD by default.

**Comment by Coeur** [comment]
I started a pull request on minizip to allow AES to be optional: https://github.com/nmoinvaz/minizip/pull/144

**Comment by jhudsonWA** [comment]
Runtime would be better if possible, depending on the situation. Bummer Archive Utility, etc does not allow AES.

**Comment by Coeur** [comment]
Nathan Moinvaziri is preparing a [dev branch at minizip](https://github.com/nmoinvaz/minizip/tree/dev) that will allow us to solve this issue:

**Comment by Coeur** [comment]
Nathan MiniZip2 is done according to him... but it's not simple to migrate to it. I've started https://github.com/ZipArchive/ZipArchive/tree/minizip2 if one has courage to look at it.
