### ISSUE TITLE
SSZipArchive used but how to use SSZipArchiveDelegate with +createZipFileAtPath functions

### ISSUE THREAD

**Issue by aadirappier** [ZipArchive/ZipArchive#229]
I am using your library to archive the Folder and it sub files have following questions.

1) I do see the '- (BOOL)writeFileAtPath:(NSString *)path withFileName:(NSString *)fileName;' instance function so then only can use these delegates define SSZipArchiveDelegate.
2) But How to use the same delegates for the more convenient fucntions.

// Zip
+ (BOOL)createZipFileAtPath:(NSString *)path withFilesAtPaths:(NSArray *)filenames;
+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath;
+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath keepParentDirectory:(BOOL)keepParentDirectory;

Appreciate as I need a quick help and guidance.

Thanks.

**Comment by jhudsonWA** [comment]
Still need help with this?
