### ISSUE TITLE
I'm missing the methods to archive with password

### ISSUE THREAD

**Issue by Wilson2014** [ZipArchive/ZipArchive#231]
when i add pod 'SSZipArchive' in my pod file and update it , i got it but all the methods that can archive a file with password are missing

**Comment by jhudsonWA** [comment]
The password methods are in master but have not been released. They still need more testing.

The pod only points at the latest release

**Comment by jhudsonWA** [comment]
Try now. Just released v1.1 that includes this ability.

**Comment by Wilson2014** [comment]
Thanks!
