### ISSUE TITLE
carthage update

### ISSUE THREAD

**Issue by pharen** [ZipArchive/ZipArchive#232]
Dependency "ZipArchive" has no shared framework schemes

**Comment by jhudsonWA** [comment]
Did you try master? We just merged in carthage support.

**Comment by pharen** [comment]
*** Fetching ZipArchive
*** Checking out ZipArchive at "v1.0.1"
*** Skipped building ZipArchive due to the error:
Dependency "ZipArchive" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/ZipArchive/ZipArchive/issues/new

**Comment by jhudsonWA** [comment]
That's not master. That is the last tag. Look here until a new release is created: 

https://github.com/ZipArchive/ZipArchive/pull/227

Comment by @kylejm towards the bottom.

**Comment by pharen** [comment]
Thanks, i use 
github "ZipArchive/ZipArchive" "master"

**Comment by jhudsonWA** [comment]
I'm working on a new release very soon

**Comment by jhudsonWA** [comment]
Ok, latest version released. You should be able to switch away from master now.
