### ISSUE TITLE
Reference to unz_file_info ambigouos

### ISSUE THREAD

**Issue by jiglesiasf** [ZipArchive/ZipArchive#233]
I just try to add SSZipArchive to my personal project, however when I build it I am getting an error like following: 
"Reference to unz_file_info ambigouos"
I have to say that I created also another blank project and I was able to build and run it. So I guess it is some setting I have set up but I dont know which one could be.

Thanks a lot

**Comment by jhudsonWA** [comment]
Not sure. Are you using it as a manual install or cocoapods?

**Comment by jiglesiasf** [comment]
Manual install.
Thanks

El miércoles, 27 de enero de 2016, Joshua Hudson <notifications@github.com>
escribió:

> Not sure. Are you using it as a manual install or cocoapods?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZipArchive/ZipArchive/issues/233#issuecomment-175335862>
> .
>


-- 
Juan Iglesias Fernández.

**Comment by jiglesiasf** [comment]
Hi! I just try again, cleaning the project, readding library and now I am not getting any error when build. However, when I try to unzip by: 
[SSZipArchive unzipFileAtPath:zipPath toDestination:targetFolder]; 
or
[SSZipArchive unzipFileAtPath:zipPath toDestination:targetFolder delegate:self];
 It does not do anything. I debugged it and I see that it gets and error on the following method: local unzFile unzOpenInternal(const void *path, zlib_filefunc64_32_def *pzlib_filefunc64_32_def)
At somepoint get central_pos = unz64local_SearchCentralDir(&us.z_filefunc, us.filestream); and as it gets cero go straight to err = UNZ_ERRNO; returning NULL. 

Any idea?

**Comment by jiglesiasf** [comment]
One thing I have also tried is to rename unz_file_info to unz_file_myInfo and then I am not getting any error but then [SSZipArchive unzipFileAtPath:zipPath toDestination:targetFolder]; does not work. 
When it gets unzip.c at central_pos = unz64local_SearchCentralDir(&us.z_filefunc, us.filestream); central_pos is 0 so after it gets err = UNZ_ERRNO; and then return NULL. 

Any advice? Thanks a lot!
