### ISSUE TITLE
Succeed is true when unzipping file with the wrong password

### ISSUE THREAD

**Issue by juliengomes** [ZipArchive/ZipArchive#234]
Hi,

I saw this strange behaviour : I download multiple zip files (around 15, 4 at the same time) using TCBlobDownloader. When one download finish I unzip the file using a password.
When I use the password "lol" (which is not the password for the zip files), some of the operations are failing (succeed set to false), BUT some are succeeding (succeed set to true) !
When I set the correct password everything works ok (succeed set to true all the time).
I guess it's related to NSOperation or multithreading but I didn't investigate further.

**Comment by jhudsonWA** [comment]
Thanks, I'll take a look!

**Comment by GKrishna1** [comment]
Same in my case as well:
I am unzipping a password protected file as

 `SSZipArchive.unzipFileAtPath(sourceFile, toDestination: extractHere,
                                                                                             overwrite: true,
                                                                                             password: "myPassword",
                                                                                             progressHandler: nil,
                                                                                             completionHandler: { (path, success, error) in`

Here if I give the correct password then everything works fine, but when i give wrong password it extracts a zero byte file at destination and set success to true which shouldn't be the case.

**Comment by jhudsonWA** [comment]
Is this a file that you zipped up using the library? Or was it already password protected?

**Comment by jhudsonWA** [comment]
No feedback. Closing.
