### ISSUE TITLE
Type ClassName does not conform to protocol 'NSObjectProtocol' - Swift

### ISSUE THREAD

**Issue by yogesh061** [ZipArchive/ZipArchive#235]
While using SSZipArchiveDelegate with Swift I always get this error  - Type ClassName does not conform to protocol 'NSObjectProtocol'

Is there a reason why SSZipArchiveDelegate protocol is subclass of NSObjectProtocol? To fix this issue all methods of NSObjectProtocol are supposed to be implemented.

Am I missing something here?

**Comment by jhudsonWA** [comment]
Can you show some example code? I'm using this daily with Swift and it works fine.

**Comment by yogesh061** [comment]
Sample code below

It gives this error on class declaration - _Type 'DownloadHandler' does not conform to protocol 'NSObjectProtocol'_

```
import SSZipArchive
class DownloadHandler:SSZipArchiveDelegate {
    func unzipFile(zipFileLocation:String, unzipLocation:String, moduleId:String){
        print("unzipFile  zipFileLocation::\(zipFileLocation) unzipLocation:: \(unzipLocation)")
        dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0)) { () -> Void in
            SSZipArchive.unzipFileAtPath(zipFileLocation, toDestination: unzipLocation, overwrite: true, password: nil, error: nil, delegate: self)
        }
        
    }
}

```

**Comment by jhudsonWA** [comment]
Thanks. :)
