### ISSUE TITLE
+createZipFileAtPath: bug with keepParentDirectory

### ISSUE THREAD

**Issue by kayembi** [ZipArchive/ZipArchive#239]
There's a minor bug in +createZipFileAtPath:withContentsOfDirectory:keepParentDirectory:withPassword: whereby, if keepParentDirectory is YES and there are any empty directories inside the folder being archived, those empty directories will be put in the wrong place.

This is because the if (keepParentDirectory) check is currently done inside the if (!isDir) block:

`if (!isDir)` {
`    if (keepParentDirectory)`
`    {`
`        fileName = [[directoryPath lastPathComponent] stringByAppendingPathComponent:fileName];`
`    }`
`    [zipArchive writeFileAtPath:fullFilePath withFileName:fileName withPassword:password];`
`}`
`else`
`...'

Thus, if keepParentDirectory is YES, the paths for empty directories are not updated to include the parent directory. This can be fixed by moving the if (keepParentDirectory) check out of and above the if (!isDir) check:

`if (keepParentDirectory)`
`    fileName = [[directoryPath lastPathComponent] stringByAppendingPathComponent:fileName];`

`if (!isDir)` {
`    [zipArchive writeFileAtPath:fullFilePath withFileName:fileName withPassword:password];`
`}`
`else`
`...'

Fantastic and incredibly useful class, by the way, whoever created it!

**Comment by jhudsonWA** [comment]
Thanks! I'll fix it up Monday when I'm back at my Mac :)

**Comment by jhudsonWA** [comment]
Sorry this took so long, code fix pushed in. I'll create a release soon.

**Comment by kayembi** [comment]
Great, thanks for adding the fix!
