### ISSUE TITLE
Unzip with password doesn't work with libstdc++

### ISSUE THREAD

**Issue by erwinl** [ZipArchive/ZipArchive#240]
> Note: 
> This case is only for unzipping encrypted (password protected) zip file. Normal zip file works fine.

I'm using SSZipArchive to unzip encrypted zip file and it works fine if I use `libc++ (LLVM C++ standard library with C++11 support)` as the `C++ Standard Library`.

However one of the framework I have to use in my project requires `libstdc++ (GNU C++ standard library)`, otherwise it won't compile because of missing symbols.

I tried these two routes:
- Setting `C++ Standard Library` to `libstdc++ (GNU C++ standard library)`.
- Keep `C++ Standard Library` to `libc++ (LLVM C++ standard library with C++11 support)` and link against `libstdc++.6.0.9.tbd`.

Unfortunately unzip with password fails in both cases. It fails [here](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L140):

``` objc
// SSZipArchive.m line 140
// ret is always != UNZ_OK when libstdc++ involved
ret = unzOpenCurrentFilePassword(zip, [password cStringUsingEncoding:NSASCIIStringEncoding]);
```

Any idea why is this happening? and the possible fix ?

Thanks in advance.

**Comment by jhudsonWA** [comment]
Yikes, I have no idea. Anyone else?

**Comment by daniel-beard** [comment]
@erwinl can the password be represented by ascii characters, or does it contain unicode characters?

**Comment by erwinl** [comment]
Hello @daniel-beard, I was using dummy passwords such as "password" or "12345".

I can confirm that the unzipping with password works ok if I use `libc++ (LLVM C++ standard library with C++11 support)` only. However when I add `libstdc++`, the unzipping always fail.

**Comment by jhudsonWA** [comment]
PRs welcome, but I don't personally have any projects that integrate this project this with C++ code.

**Comment by jhudsonWA** [comment]
Still an issue?

**Comment by Coeur** [comment]
@erwinl you will have to provide a sample xcode project on github that can reproduce the issue.

**Comment by jhudsonWA** [comment]
If @erwinl does mention it here and I'll reopen.

**Comment by Coeur** [comment]
Note, I tried the following:
 1. get ZipArchive from branch 2.0 including the example project with password support: https://github.com/ZipArchive/ZipArchive/tree/09e7b26686bac224e0d12dba865db344551cfcbc
 2. rename ViewController.m to ViewController.mm
 3. change CLANG_CXX_LIBRARY to libstdc++ for the ObjectiveCExample target

=> it works. The ZipArchive framework itself is probably built using [-std=c99], but I don't see why you would need to build all your dependencies using the same compiler.
