### ISSUE TITLE
No file in my zip when i zip one file

### ISSUE THREAD

**Issue by zemadara** [ZipArchive/ZipArchive#242]
Hi,

i try to zip a file, in my case it's an image and when i unzip it (manually in my finder) there is no file ... but when i zip a folder and i unzip there are files ...

My code 
`let archivePath = filepathSecure.path!.stringByAppendingString("/(self.productName.stringValue).zip")

SSZipArchive.createZipFileAtPath(archivePath, withContentsOfDirectory: self.pathURL!.path!)`

**Comment by jhudsonWA** [comment]
I'll take a look tomorrow.

**Comment by jhudsonWA** [comment]
How did you zip up  the file by the way? Can you give us a quick snippet of code?

**Comment by chirag04** [comment]
I just saw your commit. seems like what i need is `keepParentDirectory` while unzipping.

**Comment by jhudsonWA** [comment]
I agree. Let me see what I can do

**Comment by zemadara** [comment]
My code 
`let archivePath = filepathSecure.path!.stringByAppendingString("/\(self.productName.stringValue).zip")
 SSZipArchive.createZipFileAtPath(archivePath, withContentsOfDirectory: self.pathURL!.path!)`
