### ISSUE TITLE
Get error if manually add source files

### ISSUE THREAD

**Issue by StainlessStlRat** [ZipArchive/ZipArchive#244]
Perhaps I'm daft but I could not figure out my issue.

When adding the files manually (adding the SSZipArchive folder, which includes all subfolders such as minifolder), upon compilation, I get an error about aescpp.h not being found from aesopt.h

While I do have c++ functionality in my code, the lib source files are being seen as c header files. 

I'm surprised to not at least find anyone else having my issue.

**Comment by jhudsonWA** [comment]
Nothing since March. Closing.
