### ISSUE TITLE
pod file includes tvos but I cannot get it

### ISSUE THREAD

**Issue by vodkhang** [ZipArchive/ZipArchive#248]
I get the following error

Analyzing dependencies
[!] The platform of the target `Pods` (tvOS 9.0) is not compatible with `SSZipArchive (1.1)`, which does not support `tvos`.

**Comment by jhudsonWA** [comment]
You pointed at master or latest release? It's only in master until I do the next release.

**Comment by jhudsonWA** [comment]
released as pod 1.2
