### ISSUE TITLE
Error opening zip file if the File name contains space/%20 character

### ISSUE THREAD

**Issue by michaelkroll** [ZipArchive/ZipArchive#249]
Hi,

when I try to unzip a file using the follwing path:
/private/var/mobile/Containers/Data/Application/F610114A-B92A-45F4-A38B-BB20F96037F1/Documents/Inbox/test%20file.zip

the method
SSZipArchive.unzipFileAtPath(src, dest)
fails

When i instead use a filename such as:
/private/var/mobile/Containers/Data/Application/F610114A-B92A-45F4-A38B-BB20F96037F1/Documents/Inbox/test_file.zip

it works.

It seems that the call:

zipFile zip = unzOpen((const char*)[path UTF8String]); 

fails.
Any idea how to fix this?

Thanks
Michael

**Comment by t4ec** [comment]
Looks like I face the same issue when file is located in "Application Support" (with whitespace char) folder.

**Comment by jhudsonWA** [comment]
So this seems to be an issue in the minizip c library that we use where it does not handle files with spaces.

**Comment by jhudsonWA** [comment]
No feedback since July. Closing. Can reopen if there is more details.
