### ISSUE TITLE
Remove all encryption code from app binary so it will comply with Apple Export Complience rules regarding encryption.

### ISSUE THREAD

**Issue by t4ec** [ZipArchive/ZipArchive#252]
Hi!

Is there any way to prevent or remove all possible encryption code from compiling?

As I need only compression/decompression without any passwords or encryption I do not want to pass Apple Export Complience process which includes registration of my app as the one which uses or incorporates encryption in any way.

So is there way to exclude code related to aes, passwords, etc.  from lib?

Thanks!

**Comment by jhudsonWA** [comment]
I'm going to say no. That would take a lot of work and remove a ton of code. Even going back to earlier releases of this project there was basic zip password support. AES support was added about a year ago, so you could go back to before then. But again, it's always had basic unzip password support.
