### ISSUE TITLE
Unable to unCompress zip file which is saved in document directory.

### ISSUE THREAD

**Issue by narendra-ct** [ZipArchive/ZipArchive#254]
hello,

Im trying to uncompress/unzip the file which is downloaded form server and its saved in document directory with **[nsdata writetofile:testfile.zip automatic:YES];**

but it failed to unzip/decompress.Help me on this is there is any way to store in documendirectory or any specific way to use zipArchive.

Thanks,
Narendra.

**Comment by narendra-ct** [comment]
PFA , having zip file if i try to open this throws an error BADZIPFILE .
Help on this.

Thanks,
Narendra.
[Screenshots.zip](https://github.com/ZipArchive/ZipArchive/files/320107/Screenshots.zip)

**Comment by jhudsonWA** [comment]
What is your method call to decompress? Are you using the full path?

**Comment by jhudsonWA** [comment]
No feedback since July. Closing.
