### ISSUE TITLE
On MacOS 10.11.5 symlinks are not being put into zip file

### ISSUE THREAD

**Issue by ateague** [ZipArchive/ZipArchive#255]
Create a test directory as follows:
  % mkdir -p foo/a
  % cd foo
  % ln -s a b
  % ln -s a/foo c
From Objective-C run something like this using foo as the source path and foo.zip as the target path
     [SSZipArchive createZipFileAtPath:target.path withContentsOfDirectory:source.path] 
Master/1.2+5 commits yields a zip where
  a/foo is correct
  b is an empty directory
  c is a full copy of foo

**Comment by ateague** [comment]
In SSZipArchive.m: around line 458: 
if([[NSFileManager defaultManager] subpathsOfDirectoryAtPath:fullFilePath error:&err].count == 0)
evaluates to TRUE for the b symbolic link
if you add '/' to the end of fullFilePath, then it evaluates to FALSE

**Comment by jhudsonWA** [comment]
Please try the latest release. #263 merged in some fixes for symlinks. Reopen if this is still a problem.

**Comment by ateague** [comment]
As the issue is with creating the zip file not unzipping it, this change doesn't alter the behavior. Requires a change in createZipFileAtPath

**Comment by jhudsonWA** [comment]
Ah yes, you are correct. PR welcome.
 
 
On Wed, Jul 13, 2016, at 10:41 AM, ateague wrote:
> As the issue is with creating the zip file not unzipping it, this
> change doesn't alter the behavior. Requires a change in
> createZipFileAtPath
> — You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
 

Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/255#issuecomment-232431353
  2. https://github.com/notifications/unsubscribe/AAq37tH29nK726O3pqSW3Dy-NWGR8P-5ks5qVSNGgaJpZM4I32Io
