### ISSUE TITLE
i got problem to use libxlsxwriter and ZipArchive together

### ISSUE THREAD

**Issue by sanhue0302** [ZipArchive/ZipArchive#256]
while i use pod libxlsxwriter and ZipArchive together
build would failed with "Use of undeclared identifier 'MAXU32'"
i think that because pod will misunderstand include ioapi.h at Ziparchive rather than libxlsxwriter 
any idea to use these two together?

**Comment by jhudsonWA** [comment]
Sorry I'm not familiar with libxlsxwriter.

**Comment by sanhue0302** [comment]
libxlsxwriter is a lib used to create xlsx file
it also use minizip
and unfortunately the version of minizip is not the same with ziparchive
Do you have any idea to deal with this problem?

**Comment by sanhue0302** [comment]
i think it would be good if you related minizip at https://github.com/madler/zlib
instead of having a copy of file

of course, that would be having many efforts to do this
let me know how you think, thanks

**Comment by jhudsonWA** [comment]
Not really. Maybe try Carthage for one of the packages? You could try a manual install of both. We didn't really modify minizip but do use 1.1 which is the latest.

**Comment by jhudsonWA** [comment]
I can also look at that repository if that one is the authoritative source.

**Comment by jmcnamara** [comment]
@sanhue0302 I see that you also posted that same question here that you posted to the libxlsxwriter issue tracker with an equal lack of information: https://github.com/jmcnamara/libxlsxwriter/issues/55

@jhudsonWA It looks like [libxlsxwriter](https://github.com/jmcnamara/libxlsxwriter) and ZipArchive both include the source of minizip from zlib. Libxlsxwriter mainly only uses ioapi.[ch] and zip.[ch]

The ZipArchive version of these files don't include the include sentinels from the zlib version like`#ifndef _ZLIBIOAPI64_H`. Maybe ZipArchive is using an older version that the one in zlib 1.28.

John

**Comment by jmcnamara** [comment]
@jhudsonWA Apologies. It looks like SSArhiveZip does include the latest version from zlib. 

@sanhue0302 Based on the sample code in the libxlsxwriter issue it looks like you are using ZipArchive and not SArchiveZip. Is that correct? In which case did you report this issue in the wrong place?

**Comment by sanhue0302** [comment]
@jmcnamara @jhudsonWA that is my fault , i did use ZipArchive
but if i use SSZipArchive with libxlsxwriter, there are still same problem.

**Comment by jhudsonWA** [comment]
Feedback welcome if anyone else has ideas, but until then closing.
