### ISSUE TITLE
Skip the  special character file 

### ISSUE THREAD

**Issue by RadhakrishnanRakki** [ZipArchive/ZipArchive#257]
1.) When i unzip the zip file using sszipArchive and its skip the special character file.
2.) Once completed the unzip process and check the folder.
3.) Special character file is missing that folder.

Ex :-- Place_de_l'OpeÔra,_1878.jpg
![place_de_l opeora _1878](https://cloud.githubusercontent.com/assets/15377690/16444939/232a97d8-3dfe-11e6-82d8-7d6b69d49f34.jpg)
**Notes:**- I am update the new updated sszipArchive.m file in my project
any one  please give the solution...

**Comment by jhudsonWA** [comment]
So I would verify that this is still la problem in the latest builds. However, this seems to be an issue in the minizip c library that we use where it does not handle files with special characters. We are using the latest release of that library (v1.1) but there have been no updates since 2013.
