### ISSUE TITLE
Nullability Annotations

### ISSUE THREAD

**Issue by bdunayAGL** [ZipArchive/ZipArchive#259]
I'm enjoying using your framework in my apps for zipping and unzipping files. The only issue though is I'm using this framework in Swift and everything if forced unwrapped. I've actually gone a ahead and made changes adding in the Objective-C nullability annotations and would like to either put up a PR for your review or I can share them via email. What ever works best.

**Comment by jhudsonWA** [comment]
Please do a PR! Would love the contribution.

**Comment by bdunayAGL** [comment]
Cool... only problem is I don't seem to have permission to push up a branch for PR. This is the error I'm getting back:

Pushing to https://bdunayAGL@github.com/ZipArchive/ZipArchive.git
remote: Permission to ZipArchive/ZipArchive.git denied to bdunayAGL.
fatal: unable to access 'https://bdunayAGL@github.com/ZipArchive/ZipArchive.git/': The requested URL returned error: 403

First time contributing to open source (especially through GitHub) so please forgive me if I'm doing something stupid.

**Comment by jhudsonWA** [comment]
On github you should fork the project, push to your fork then use github to create the PR. 

You shouldn't need direct push access to this repository.

**Comment by bdunayAGL** [comment]
Ah, apologies. As I said before I'm new to contributing back to open source. 

I've done as you suggested and a new [PR](https://github.com/ZipArchive/ZipArchive/pull/260) awaits your review. Thanks!

**Comment by jhudsonWA** [comment]
Looks good! I'll review and make sure it passes test then merge in.

**Comment by jhudsonWA** [comment]
Released as v1.3. Thanks!
