### ISSUE TITLE
Pod install issue with v1.4

### ISSUE THREAD

**Issue by agarwalmukund** [ZipArchive/ZipArchive#265]
When I set the following in my project's Podfile:
`pod 'SSZipArchive', '~> 1.4'`

I run into the following issue when I try to install:
`$ pod install`
`Analysing dependencies`
`[!] Unable to satisfy the following requirements:`
`- SSZipArchive (~> 1.4) required by Podfile`
`None of your spec sources contain a spec satisfying the dependency: SSZipArchive (~> 1.4)`
`You have either:`
`* out-of-date source repos which you can update with pod repo update.`
`* mistyped the name or version.`
`* not added the source repo that hosts the Podspec to your Podfile.`

If I change it the Podfile entry to:
`pod 'SSZipArchive'`
then it works fine
`Analysing dependencies`
`Downloading dependencies`
`Installing SSZipArchive (1.2)`
`Generating Pods project`
`Integrating client project`
`Sending stats`
`Pod installation complete! There are 1 dependencies from the Podfile and 1 total pods installed.`

Is there an issue with the v1.4 release via CocoaPods as v1.2 seems to be the latest according to CocoaPods?

Thank you,
Mukund

**Comment by jhudsonWA** [comment]
https://cocoapods.org/?q=SSZIP 
 
Shows 1.4 on the main site.
 
I just updated yesterday in another project I have and it worked fine.
 
 
On Thu, Jul 14, 2016, at 03:05 AM, Mukund Agarwal wrote:
> When I set the following in my project's Podfile:
> pod 'SSZipArchive', '~> 1.4'
> I run into the following issue when I try to install:
> $ pod install
> Analysing dependencies
> [!] Unable to satisfy the following requirements:
> - SSZipArchive (~> 1.4) required by Podfile
> None of your spec sources contain a spec satisfying the dependency:
> SSZipArchive (~> 1.4)
> You have either:
> * out-of-date source repos which you can update with pod repo update.
> * mistyped the name or version.
> * not added the source repo that hosts the Podspec to your Podfile.
> If I change it the Podfile entry to:
> pod 'SSZipArchive'
>  then it works fine
> Analysing dependencies
> Downloading dependencies
> Installing SSZipArchive (1.2)
> Generating Pods project
> Integrating client project
> Sending stats
> Pod installation complete! There are 1 dependencies from the Podfile
> and 1 total pods installed.
> Is there an issue with the v1.4 release via CocoaPods as v1.2 seems to
> be the latest according to CocoaPods?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
 

Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/265
  2. https://github.com/notifications/unsubscribe/AAq37tyfaV5W3uiIxy7GEJzDUSNsquIXks5qVgoBgaJpZM4JMRmj

**Comment by agarwalmukund** [comment]
Thank you for checking. 
Probably its some setup issue from my side.

Kind regards,
Mukund

**Comment by jhudsonWA** [comment]
Also verify if you are using one of the other projects that depend on this one (also listed on that link). They may have their level required set different than yours. Otherwise it seems your version of cocoapods has a old list of the pods. 1.2 was released back on 5/11
