### ISSUE TITLE
oc writeData failed. 

### ISSUE THREAD

**Issue by Dada08** [ZipArchive/ZipArchive#266]
How to use writeData method to write NSData data to zip file?

`
        SSZipArchive *zipArchive = [[SSZipArchive alloc] initWithPath:selectedFilePath];

        BOOL opened = [zipArchive open];

        BOOL saved = [zipArchive writeData:data filename:@"application.zip" withPassword:nil];

        BOOL closed = [zipArchive close];

        NSLog(@"%d %d %d", opened, saved, closed);`

selectedFilePath = "/var/containers/Bundle/Application/****-****/Buzzer.app/sampleZip/app.zip".

it occurred error when close.
 "@"[SSZipArchive] Attempting to close an archive which was never opened")"

**Comment by jhudsonWA** [comment]
You ever figure this out? Closing since no additional comments since July. Can reopen if still an issue.
