### ISSUE TITLE
Common.h file name conflict

### ISSUE THREAD

**Issue by wilkowski** [ZipArchive/ZipArchive#270]
Another pod in my project also decided to use Common.h as a file name which caused the compilation to fail when only one of the files was used by the compiler.

**Comment by jhudsonWA** [comment]
Noted, I'll see if I can rename it. Don't see why not

**Comment by jhudsonWA** [comment]
Checked in. Please test master, there are not other changes from the latest release.

**Comment by jhudsonWA** [comment]
Released as 1.5
