### ISSUE TITLE
unzip password zip File not content

### ISSUE THREAD

**Issue by xiaolongiy** [ZipArchive/ZipArchive#272]
I use
[SSZipArchive createZipFileAtPath:[[JSPatchFileManage patchRootDirPath] stringByAppendingPathComponent:@"sss.zip"] withFilesAtPaths:array withPassword:@"123456"];
the zip can unzip correct files

[SSZipArchive unzipFileAtPath:savePath
                                   toDestination:outPath
                                       overwrite:YES
                                        password:@"123456"
                                           error:&error];

but I copy  TestPasswordArchive.zip to my project，unzip files（LICENSE and Readme.markdown）not content 
0 byte

sss.zip  can not unzip with password in Mac

**Comment by jhudsonWA** [comment]
I've heard reports of this in the past. I'm wondering if the Mac/Windows encryption is different. Folks on windows have had luck using winzip or winrar.
