### ISSUE TITLE
AES_DECRYPT macro redefinition

### ISSUE THREAD

**Issue by mrcararia** [ZipArchive/ZipArchive#274]
Hi there,
I'm using SSZipArchive and OpenSSL cocoapods in same project.
There are 2 warnings for a macro redefinition.
```
#define AES_ENCRYPT 
# define AES_DECRYPT
```

Is possible to refactor those macros or fix somehow these warnings?
Thanks a lot.

N.

**Comment by jhudsonWA** [comment]
PRs welcome. I don't have a ton of time to make sure multiple pods work together and don't clash.

**Comment by Coeur** [comment]
Reproduced. I've asked CocoaPods for help, as I do not know how to solve it: https://github.com/CocoaPods/CocoaPods/issues/6835

**Comment by Coeur** [comment]
I've asked minizip for help at https://github.com/nmoinvaz/minizip/issues/152

**Comment by Coeur** [comment]
I've also asked both dependencies for help:
https://github.com/BrianGladman/aes/issues/29
https://github.com/openssl/openssl/issues/4441

**Comment by Coeur** [comment]
Bah... I just noticed that the issue was gone between SSZipArchive 2.0.1 and SSZipArchive 2.0.2. I'm trying to figure out why.

**Comment by Coeur** [comment]
OK. I found why.

I changed:

    #include "aes.h"

To:

    #include "aes/aes.h"

And the warning is gone.

Issue was introduced by https://github.com/ZipArchive/ZipArchive/commit/644dedb04880e68d98e33b4ad588671989ed3ad8 in SSZipARchive 1.1 and solved by #356 in SSZipArchive 2.0.2
