### ISSUE TITLE
Can't compile 1.5

### ISSUE THREAD

**Issue by bmichotte** [ZipArchive/ZipArchive#277]
Hi there, since #270 and the release of 1.5, I (and some users too, see https://github.com/HearthSim/HSTracker/issues/586 for reference) got error with SSZipCommon.h which can't be found.

FI, the build is done by Carthage. Atm, we need to use stick to 1.4

**Comment by jhudsonWA** [comment]
Hmm, are you using the prebuilt framework? Or bulding it new? That file 
did change, but Carthage was happy with the change when I built the 
prebuilt framework.

**Comment by bmichotte** [comment]
I build it with `carthage update --platform osx`

**Comment by jhudsonWA** [comment]
Thanks. I will investigate some more.

**Comment by jhudsonWA** [comment]
This should be fixed in 1.6
