### ISSUE TITLE
ioapi.c malloc: *** mach_vm_map(size=1885536256) failed (error code=3)

### ISSUE THREAD

**Issue by oui123** [ZipArchive/ZipArchive#279]
when i use  [gvr-ios-sdk](https://github.com/googlevr/gvr-ios-sdk) with ZipArchive. It  crash in ioapi.c 
diskFilename = (char*)malloc(ioposix->filenameLength * sizeof(char)); because unified(9993,0x199ec6310) malloc: *** mach_vm_map(size=1885536256) failed (error code=3)
*** error: can't allocate region

**Comment by jhudsonWA** [comment]
Probably a duplicated library of some sort? I'm not going to do much to make sure we are compatible with other libraries. There are simply too many.

**Comment by oui123** [comment]
Thanks. This is indeed a duplicated library of some sort.I have already solved this problem.

**Comment by lansedebing** [comment]
I have the same problem when using gvr-ios-sdk. How did you solved it, thanks@oui123

**Comment by leiguang** [comment]
I also encountered this problem, create  a new project, a separate decompression can be successful, how to find a of the duplicated library ? Thanks.

**Comment by Coeur** [comment]
@leiguang maybe sharing your Podfile or Cartfile could help.

**Comment by leiguang** [comment]
I found that my podfile has a library called "OpenSSL-Universal", which has the same name as the "SSZipArchive" library file: "aes.h", and in the two libraries "aes.h", there are "#define AES_ENCRYPT "and" #define AES_DECRYPT ", I do not know if this is a conflict? @Coeur

**Comment by leiguang** [comment]
My podfile file contains:
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'MWPhotoBrowser'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'DACircularProgress'
  pod "MIHCrypto"
  pod 'MMPopupView'
  pod 'MJExtension'
  pod 'IQKeyboardManager'
  pod 'UITableView+FDTemplateLayoutCell'
  pod 'WMPageController'
  pod 'TAPageControl'
  pod 'StreamingKit'
  pod 'Activity'
  pod 'TNRadioButtonGroup'
  pod 'INTULocationManager'
  pod 'ActionSheetPicker-3.0'
  pod 'MDHTMLLabel'
  pod 'NYSegmentedControl'
  pod 'FSMediaPicker'
  pod 'GTSDK'
  pod 'FMDB'
  pod 'KGHitTestingViews'
  pod 'ShareSDK3'
  pod 'SMSSDK'
  pod 'MOBFoundation'
  pod 'ShareSDK3/ShareSDKPlatforms/QQ'
  pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
  pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
  pod 'CRToast'
  pod 'UITextView+Placeholder', '~> 1.2'
  pod 'UMengAnalytics'
  pod 'Bugtags'
  pod 'SWTableViewCell'
  pod 'SSZipArchive’
  pod 'XHLaunchAd'

When i pod install，it is beging given: [!] The 'Pods-ObjectiveCExample' target has transitive dependencies that include static binaries: (/Users/leiguang/Downloads/ZipArchive-master/ObjectiveCExample/Pods/OpenSSL-Universal/lib-ios/libcrypto.a and /Users/leiguang/Downloads/ZipArchive-master/ObjectiveCExample/Pods/OpenSSL-Universal/lib-ios/libssl.a)

**Comment by Coeur** [comment]
Then, it's a duplicate of issue #274, where I stated that I did not know how to solve it and for which I opened an unresolved ticket at cocoapods: https://github.com/CocoaPods/CocoaPods/issues/6835
