### ISSUE TITLE
Unable to use ZipArchive in a Swift 2.3 Xcode 8 project

### ISSUE THREAD

**Issue by JDurantFM** [ZipArchive/ZipArchive#286]
I'm trying to use ZipArchive 1.5 in a Swift 2.3 Xcode 8 project, but I get an error that the framework was built by an older version of the compiler.  If I build using ZipArchive 1.6 or later, it says "module compiled with Swift 3.0 cannot be imported in Swift 2.3"

Is there a branch or release that has ZipArchive Swift 2.3/Xcode 8 support?

Thanks.

**Comment by jhudsonWA** [comment]
I was told the current release worked in Swift 2.3 and earlier. Sounds
like that was bad information. I'll create a branch tomorrow.

--
  Joshua Hudson
  joshua@hudsons.io



On Tue, Sep 20, 2016, at 10:02 PM, JDurantFM wrote:
> I'm trying to use ZipArchive 1.5 in a Swift 2.3 Xcode 8 project, but I
> get an error that the framework was built by an older version of the
> compiler.  If I build using ZipArchive 1.6 or later, it says "module
> compiled with Swift 3.0 cannot be imported in Swift 2.3"
> Is there a branch or release that has ZipArchive Swift 2.3/Xcode 8
> support?
> Thanks.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/286

**Comment by JDurantFM** [comment]
Ok great, thanks Joshua.

**Comment by jhudsonWA** [comment]
Please try the new swift23 branch. It is identical to current 1.6 release but targeted to swift 2.3
