### ISSUE TITLE
Library not loaded: @rpath/libswiftCore.dylib

### ISSUE THREAD

**Issue by LnsooXD** [ZipArchive/ZipArchive#288]
I use this framework in pure Object-c project. It crack like blew:

```
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/xxxx-xxx-xxx-xxx/xxx.app/Frameworks/ZipArchive.framework/ZipArchive
  Reason: image not found
```

**Comment by jhudsonWA** [comment]
How did you load it?

**Comment by RomeHein** [comment]
Same issue here when using in an iOS extension

**Comment by jhudsonWA** [comment]
http://stackoverflow.com/a/26949219 Can you try this and let me know if it works on your side? If yes I'll see if I can modify the project to make this work.

**Comment by tjozsa** [comment]
I had the same issue. This helped me. I suggest to close this issue.

**Comment by alessionunzi** [comment]
I had the same issue, I fixed as mentioned in http://stackoverflow.com/a/26949219 but not exactly, I changed the flag ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to yes instead of the suggested EMBEDDED_CONTENT_CONTAINS_SWIFT because I couldn't find it (I suspect because I don't have embedded frameworks in my project settings).

But now when I run pod update I get a warning message like
`target overrides the ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES build setting defined in 'Pods/Target Support Files/Pods-Blubel/Pods-Blubel.release.xcconfig'. This can lead to problems with the CocoaPods installation`

**Comment by jhudsonWA** [comment]
@alessionunzi I get that for all my Cocoapods projects that have swift code in them now. Wondering if it is a xcode thing or cocoapods thing. I'll keep looking to see if I can resolve at project level.

**Comment by hite** [comment]
my problem is `Library not loaded: @rpath/libswiftDarwin.dylib` , and  http://stackoverflow.com/a/26949219  resolves it

**Comment by Coeur** [comment]
I believe this was a CocoaPods issue. I'll close this issue for now, but if it happens again for someone, then:
1. please be sure to test with CocoaPods 1.2.0 or higher
2. you must share a project that can reproduce the issue

**Comment by JoJoTawk** [comment]
I am having the same issue none of the previous solutions worked for me 
that's the error I am getting :
**dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/ziadtawk/Library/Developer/CoreSimulator/Devices/B0ECFE80-1882-4A5B-ADE8-D547298E92D1/data/Containers/Bundle/Application/8464DBFD-8ADC-4B93-BD5E-2872645BEAFF/Slybroadcast.app/Frameworks/Charts.framework/Charts
  Reason: image not found**

**Comment by jhudsonWA** [comment]
> Slybroadcast.app/Frameworks/Charts.framework/Charts

Charts framework? Wrong library? Have you checked with them?

**Comment by ngokul3** [comment]
Did anyone find a fix apart from turning off Embed Swift file option in the project file?

**Comment by Coeur** [comment]
@ngokul3 as written above:
>you must share a project that can reproduce the issue

No help will be given if we can't reproduce/analyze the issue.
