### ISSUE TITLE
Update manual installation on README

### ISSUE THREAD

**Issue by leolobato** [ZipArchive/ZipArchive#294]
The `minizip` folder is now inside `SSZipArchive`, so it is not clear if the `aes` folder should also be included on the project.

Also, there is an `Info.plist` file inside `SSZipArchive`, which most likely is not needed to be included.

Maybe it would be better to move all the required files into a single folder and mention that folder (along it's subfolders) on `README`?

**Comment by jhudsonWA** [comment]
If you could suggest new language that would be very helpful and I would
love to include it. Not many folks do manual installs anymore, but for
those that do having the correct instructions would help.

--
  Joshua Hudson
  joshua@hudsons.io



On Sat, Oct 29, 2016, at 02:28 AM, Leo Lobato wrote:
> The minizip folder is now inside SSZipArchive, so it is not clear if
> the aes folder should also be included on the project.
> Also, there is an Info.plist file inside SSZipArchive, which most
> likely is not needed to be included.
> Maybe it would be better to move all the required files into a single
> folder and mention that folder (along it's subfolders) on README?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/294

**Comment by leolobato** [comment]
Sure, no problem. I'll update a fork with the README wording, move the `Info.plist` file out of that folder and do a pull request.

**Comment by jhudsonWA** [comment]
That would be amazing. Thanks!

--
  Joshua Hudson
  joshua@hudsons.io



On Tue, Nov 1, 2016, at 10:13 AM, Leo Lobato wrote:
> Sure, no problem. I'll update a fork with the README wording, move the
> Info.plist file out of that folder and do a pull request.
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/294#issuecomment-257627984

**Comment by garrettmaring** [comment]
I second this! Simply dragging the files over didn't seem to do enough for my project. It still isn't able to see the SSZipArchive class.

**Comment by ahmedk92** [comment]
@garrettmaring 
Did you manage to add SSZipArchive manually?

**Comment by Coeur** [comment]
Note: on branch [2.0](https://github.com/ZipArchive/ZipArchive/tree/2.0), `aes` is now inside the `minizip` folder.

**Comment by jhudsonWA** [comment]
Yep, I'm going to close this as it is resolved to be as desired on the 2.0 branch.
