### ISSUE TITLE
Zip add file comments

### ISSUE THREAD

**Issue by JsonLeecoder** [ZipArchive/ZipArchive#295]
I want to use ZipArchive to add file comments,that means to use file compressed,I want to know the api of file comments  how to use? exist？

**Comment by jhudsonWA** [comment]
ZipArchive simply compresses or decompresses. There is probably not support for what you want.

**Comment by JsonLeecoder** [comment]
Thank you very much ,later ,I found the way，the method is “zipClose (file, global_comment) ”，the global_comment  I want to set it!In the usual，the global_comment is set NULL.
