### ISSUE TITLE
Dont Zip File (stay in createZipFileAtPath)

### ISSUE THREAD

**Issue by Mohsenkhodadadzadeh** [ZipArchive/ZipArchive#297]
when i want upzip file by SSZipArchive.unzipFileAtPath , i can unzip file but after i want zip file by SSZipArchive.createZipFileAtPath( : _ , withFilesAtPaths: _ ) waiting and not finished (cpu and memory is full used when run this code . but not finished)
my code is 
  SSZipArchive.createZipFileAtPath("\(downloadpath)/App.zip", withFilesAtPaths: ["\(test2path)"])

swift 2.2
xcode 7.2.1
 release version (v 1.5 and v1.4 tested)

**Comment by brookslyrette** [comment]
Did you ever solve this? I'm seeing similar behaviour.

**Comment by jhudsonWA** [comment]
Is (downloadpath) different than (test2path)?

**Comment by brookslyrette** [comment]
I was using NSURL.absolutePath, This includes `file://` as part of the string. Removing that fixed my issue.

**Comment by Mohsenkhodadadzadeh** [comment]
yes . download path defferent than test2path

**Comment by jhudsonWA** [comment]
Still an issue? Reopen if yes.
