### ISSUE TITLE
Can't import and compile files manually

### ISSUE THREAD

**Issue by kiarafrobles** [ZipArchive/ZipArchive#298]
I've tried installing with Cocopods, Carthage, and manually, but I can't resolve the this complier issue.

```
Undefined symbols for architecture arm64:
     "_OBJC_CLASS_$_SSZipArchive", referenced from:
         objc-class-ref in ActionViewController.o
   ld: symbol(s) not found for architecture arm64
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Mohsenkhodadadzadeh** [comment]
Solved Your Problem in this link
[http://stackoverflow.com/questions/19213782/undefined-symbols-for-architecture-arm64](Undefined symbols for architecture arm64)
