### ISSUE TITLE
append example

### ISSUE THREAD

**Issue by isaac-oshima** [ZipArchive/ZipArchive#300]
Is there an example (swift) of the append to zip process? 
or do you use createZipFileAtPath to an existing... 
Thank you...

**Comment by Mohsenkhodadadzadeh** [comment]
i needed it too
and when i unzip and then zip again , this resource added .DS_Store to my emptyForlder 🙁

**Comment by isaac-oshima** [comment]
Append to existing zip files; is a listed function in the readme file.  I tried createZipFileAtPath to an existing, but of course that overwrote the zip.  Anyone?

**Comment by yostyle** [comment]
I agree with isaac-oshima. How to append file or directory to an existing zip file as written in the readme ? Please re-open this issue.
