### ISSUE TITLE
failed to open zip file

### ISSUE THREAD

**Issue by freekmurze** [ZipArchive/ZipArchive#31]
unzipping results in an error "2012-10-25 13:50:47.674 Appname[5940:c07] zip error : Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file" UserInfo=0x83a4f90 {NSLocalizedDescription=failed to open zip file}"
I've added libz.dylib to my project and made sure the file I want to unzip exists. 

How can this be solved?

**Comment by petrapamela** [comment]
I also solve my problem..Thanks

**Comment by istx25** [comment]
:+1:

**Comment by abhiiosraz** [comment]
For the first time when I download and save the zip file, it works fine but when I run the app again then it shows below error.

Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file" UserInfo={NSLocalizedDescription=failed to open zip file}
