### ISSUE TITLE
NSPOSIXErrorDomain Error "Permission denied" when read the unzip file

### ISSUE THREAD

**Issue by zxl777** [ZipArchive/ZipArchive#310]
SSZipArchive 1.7 by using Swift 
`

        do {
            let str = try String(contentsOf: txtfile)
            return str
        }
        catch let err as NSError {
            print(err)
        }

`

`
Error Domain=NSCocoaErrorDomain Code=257 "The file “levelname.txt” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/var/mobile/Containers/Data/Application/EAB9373F-119E-4557-8E6A-48B3A4A8D242/Documents/unzip/levelname.txt, NSUnderlyingError=0x1704514c0 {Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied"}}
`

Please try 
[TEST.ZIP](https://github.com/ZipArchive/ZipArchive/files/730475/TEST.ZIP)

**Comment by Coeur** [comment]
Cannot reproduce on version 2.0.6. `print(str)` gives _§l§o§5Disney§1Park_.
Note that some permission overrides have been added with commit https://github.com/ZipArchive/ZipArchive/commit/d1d501d1d9a02d2cedaf5ec5a61b9f7f0677b118
