### ISSUE TITLE
[Bug] createZipFileAtPath works incorrect for symbolic links

### ISSUE THREAD

**Issue by jimwan** [ZipArchive/ZipArchive#313]
when zip a directory including symbolic link, it will save the original file. This doens't happen when unzip using "unzipFileAtPath"
Do you have any plan to fix this issue

**Comment by jhudsonWA** [comment]
"Do you have any plan to fix this issue"

You just told us about it, so no. I need to do some testing. Do you have an example zip that shows the problem?

**Comment by jimwan** [comment]
@jhudsonWA , yes. But how can i send the file to you?
In fact, you can use "ln -s 1.txt 2.txt" to create the symbolic link and then zip the file. Wish you can fix this issue as soon as possible, any problem or information request please let me know. Thanks

**Comment by jhudsonWA** [comment]
I'll do a bit of digging then. There are tests specially for these cases and they appear to be passing, but maybe they are not checking the correct thing.

**Comment by jimwan** [comment]
@jhudsonWA , you can try some apps(such as Dash.app).  There are some symbolic links in the app's content folder, after compress, the symbolic link get lost and the app can not be opened again after uncompress it.

**Comment by jimwan** [comment]
@jhudsonWA , please also test the scenario that compress a symbolic folder.  You can use Dash.app for testing two, there are some symbolic link directories in its content

**Comment by Coeur** [comment]
Any update on this, @jhudsonWA ?
Where is Dash.app content folder?

**Comment by jhudsonWA** [comment]
Not sure. I never got a chance to take a look. We do have tests that test symbolic links, but those tests run on the iOS target so maybe they are not a great test. 

And I'm assuming they are talking about https://kapeli.com/dash as an app that creats symbolic folders.

**Comment by Coeur** [comment]
Note that the tests are running on iOS, macOS and tvOS since yesterday: https://github.com/ZipArchive/ZipArchive/commit/6ec780b26a585a9dcfe518ae18502cb2b15ed1ee
And they pass (on simulator).
But I need to configure travis to automate it for each commit.

**Comment by jhudsonWA** [comment]
PR #560 merged into master. This should fix this bug if you use the right method signature (keepSymlinks:(BOOL)keeplinks)
