### ISSUE TITLE
This zip file can not been unzip (GB2312 encoding)

### ISSUE THREAD

**Issue by zxl777** [ZipArchive/ZipArchive#315]
the bug may be in the minizip, the path have GB2312 strings.
Please fix ,thank you.

[Calculator.zip](https://github.com/ZipArchive/ZipArchive/files/769125/Calculator.zip)
<img width="178" alt="2017-02-12 2 36 59" src="https://cloud.githubusercontent.com/assets/816448/22860177/cbab3c06-f130-11e6-969c-3c71e1851af7.png">

**Comment by Coeur** [comment]
I've reported the issue on https://github.com/nmoinvaz/minizip/issues/154
