### ISSUE TITLE
Wrong Password opening the file

### ISSUE THREAD

**Issue by kalimsayyad** [ZipArchive/ZipArchive#316]
Hi,

I am using this library with swift 3 for my project. It allows me to create password protected file but when i try to open this file, it asks for a password which is expected. But when i put the wrong password then also it opens the file. Is it happening with me only or someone else is also facing the same issue. Please reply.

**Comment by jhudsonWA** [comment]
So I wanted to make sure and I added a test for this case. You don't get an Error set on invalid password but the files in the zip are not created.
