### ISSUE TITLE
What is the expected behavior of unzipping a zip of zips?

### ISSUE THREAD

**Issue by mrubin** [ZipArchive/ZipArchive#319]
What is the expected behavior when you unzip (via `SSZipArchive.unzipFile(atPath: ..., toDestination: ...)` in Swift) a .zip file which contains only other zip files?

e.g.:

A.zip
|_ B.zip
|_ C.zip
|_ D.zip

I am unzipping A.zip. What I observe is that I get the contents of D.zip in my destination directory. This is unexpected.

Thank you very much

**Comment by Coeur** [comment]
I agree automatically unzipping zip files is a bug. It should be optional.
