### ISSUE TITLE
branch for latest minizip

### ISSUE THREAD

**Issue by Coeur** [ZipArchive/ZipArchive#320]
Hi @jhudsonWA ,

May we have an SSZipArchive branch/release with latest https://github.com/nmoinvaz/minizip ? [Xcode 8.3 is being quite verbose on some warnings that were recently fixed](https://github.com/nmoinvaz/minizip/pull/85).

**Comment by jhudsonWA** [comment]
Thanks. I'm trying to finish up on a real life project but I'll revisit this next week.

**Comment by Coeur** [comment]
yesterday commit by @nmoinvaz broke compatibility with __APPLE__, so please wait for https://github.com/nmoinvaz/minizip/pull/94 to be reviewed.

**Comment by Coeur** [comment]
hum, I'm also concerned about https://github.com/nmoinvaz/minizip/issues/95, so I wonder if Nathan Moinvaziri has done safe changes. They are too complex lately for me to review.

**Comment by Coeur** [comment]
Xcode 8.3 is out. Warnings are everywhere.

**Comment by jhudsonWA** [comment]
Yep, i'm working on them now

**Comment by jhudsonWA** [comment]
I attempted to pull in the minizip and I was running into errors due the changes and still a bunch of Xcode 8.3 warnings. A PR would be welcome if you have time to tackle it. I only had a few minutes today.

**Comment by Coeur** [comment]
https://github.com/ZipArchive/ZipArchive/pull/341
