### ISSUE TITLE
Crash on unzip with password: Bad characters in password?

### ISSUE THREAD

**Issue by beseder42** [ZipArchive/ZipArchive#323]
My tests most the time (not always!) crash, when I test unzipping some password protected files.

It crashes at this function in `fielenc.c`

```
static void encr_data(unsigned char data[], unsigned long d_len, fcrypt_ctx cx[1])
{
    unsigned long i = 0, pos = cx->encr_pos;

    while (i < d_len) {
        if (pos == AES_BLOCK_SIZE) {
            unsigned int j = 0;
            /* increment encryption nonce   */
            while (j < 8 && !++cx->nonce[j])
                ++j;
            /* encrypt the nonce to form next xor buffer    */
            aes_encrypt(cx->nonce, cx->encr_bfr, cx->encr_ctx);
            pos = 0;
        }

        data[i++] ^= cx->encr_bfr[pos++];    // <<<--- THIS LINE CRASHES
    }

    cx->encr_pos = (unsigned int)pos;
}
```
Variables: 
```
data	unsigned char *:  NULL	
d_len	unsigned long:    unavailable	
cx	fcrypt_ctx *:     NULL	
i	unsigned long:    0
pos	unsigned long:    1864865580
j	unsigned int:	  unavailable 
```

Stopping the test and unzipping the file with other zip software on Mac OS works always without problems. So the zip file seems ok.

I use randomly generated passwords with high complexity so I suspect that there might be some spacial characters in the zip password.

Might it be the password? Is UTF-8 ok for password or does it need ASCII? What else could be the problem?

**EDIT**
Using this character set for passwords seems to fix it:

`ABCDEFGHIJKLARMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890!#*+-=${}[]<>()_?.,`

The characters I used before also were ASCII, but also some characters like @~´`%'

**Comment by Coeur** [comment]
From your examples, one character is non-ascii, `´`.
I reproduced a problem with this non-ascii character `´`, as well as with a random Chinese characters like `宝`. I'll investigate why we do not support Unicode for passwords.
