### ISSUE TITLE
How to control the memory of iphone when unzip the file?

### ISSUE THREAD

**Issue by wangkangwei** [ZipArchive/ZipArchive#324]
I get trouble with this. When unzip a zip file contains a large of photos,the memory get jump useage so that the progress be killed by iOS system.Could you explain or solve this problem? Thank you very much.

**Comment by DanielBalsalobre** [comment]
Same here

**Comment by DanielBalsalobre** [comment]
Same here

**Comment by DanielBalsalobre** [comment]
When i try to unzip a 600mb zip it eats 2Gb of ram, unacceptable

**Comment by jhudsonWA** [comment]
Any details about the zip in question? I tested with a 300 mb zip and I don't really see a spike in memory as it unzips as a steam. Is it password protected?

**Comment by jhudsonWA** [comment]
Please reopen if you are still having issues with this.

**Comment by wangkangwei** [comment]
thanks! I still have issues with this. 

1. The zip contains 
<img width="208" alt="8f424366-a023-495f-9597-ceb6fc7e4a60" src="https://user-images.githubusercontent.com/20127920/34028553-db642004-e19e-11e7-838a-4c308f48f572.png"> something like the image shows. The three directories(resources-iphone/iphonehd/ipadhd) contains a lot of images only,like this
<img width="205" alt="016f87aa-5ddc-4057-977d-15da788ceca5" src="https://user-images.githubusercontent.com/20127920/34028624-4f329c9a-e19f-11e7-91f1-24128d8684af.png"> 

2. The problem almost happens in ipad mini1 and so on. iphone seems have no problem.
so in ipad mini1 when unzip it my app crashed. I use instrument tool to monitor the memory useage, then the memory get jump useage and shut down.
I used this method:
```
[SSZipArchive unzipFileAtPath:[zipFileURL path] toDestination:path];
```
Looking forward to reply. ^-^

**Comment by jhudsonWA** [comment]
Are you using the latest version?

**Comment by shana-jonckheere** [comment]
We are having the same issue. Memory spikes to 500 MB. Then closes the app.
Looks like the images are never cleared from memory.
Any workaround for this issue?
