### ISSUE TITLE
Unable to unzip the following file

### ISSUE THREAD

**Issue by AhmadFayyas** [ZipArchive/ZipArchive#325]
I have the following file (which is a _.doc_ zipped file):
https://drive.google.com/file/d/0B77zupnViflLTmZBdTliRjI1a00/view

I am unable to unzip it and can't find what is the reason.

Note that on the macOS, I am able to unzip it, via [UnRAR Unarchiver - Zip, Rar Extractor,Expander](https://itunes.apple.com/us/app/unrar-unarchiver-zip-rar-extractor-expander/id1071663619?mt=12).

Please advise.

**Comment by jhudsonWA** [comment]
Try to 2.0 branch if possible. It has enhancements to the unzip algorithms. If the issue still exists we can reopen.

**Comment by Coeur** [comment]
macOS Sierra's Archive Utility can't open your zip file.
![screen shot 2017-07-12 at 15 41 35](https://user-images.githubusercontent.com/839992/28107035-b8f7bd6a-6718-11e7-9c70-2a366a338fc8.png)
