### ISSUE TITLE
fileSystemRepresentation instead of UTF8String

### ISSUE THREAD

**Issue by dave256** [ZipArchive/ZipArchive#326]
When getting the path to files, the code uses the NSString method UTF8String. I think you want to use the fileSystemRepresentation method instead of UTF8String. This matters because the way HFS+ and APFS treat filenames. A zip file created with iOS 10.2 (with some non-ASCII characters in the filename) using UTF8String cannot be opened on iOS 10.3 because (I think) HFS+ does its own decomposition/normalization while APFS+ does not. I believe using fileSystemRepresentation fixes this but I am not certain.

More info here: http://mjtsai.com/blog/2017/03/24/apfss-bag-of-bytes-filenames/

**Comment by Coeur** [comment]
Change was merged, so it should be good for next release.

**Comment by xaphod** [comment]
Just hit this issue. I can verify this commit fixes it for me! filename had an umlaut in it. Note that this didn't only occur for me for 10.2->10.3, this error occurred (in the much more frequent case) for pure-10.3 scenarios (file created on 10.3, then cannot be read in 10.3)

**Comment by jhudsonWA** [comment]
I'll push a release tomorrow morning first thing. Thanks all.

**Comment by jhudsonWA** [comment]
v1.8 released. This should be fixed. Thanks!

**Comment by ljw215** [comment]
zipFile zip = unzOpen(path.fileSystemRepresentation);   Crashes when I execute this method，crash at this method
 static int ZCALLBACK fclose_file_func(ZIP_UNUSED voidpf opaque, voidpf stream)
{
    FILE_IOPOSIX *ioposix = NULL;
    int ret = -1;
    if (stream == NULL)
        return ret;
    ioposix = (FILE_IOPOSIX*)stream;
    if (ioposix->filename != NULL)
        free(ioposix->filename);
    ret = fclose(ioposix->file);
    free(ioposix);
    return ret;
}

---> if (ioposix->filename != NULL)
        free(ioposix->filename);
can you help me what happed?Thanks!

**Comment by willson-chen** [comment]
Hi @ljw215 . Is your issue related to issue 326? If not, could you please create [a new issue](https://github.com/ZipArchive/ZipArchive/issues/new) ? :)
