### ISSUE TITLE
Failed to open zip file

### ISSUE THREAD

**Issue by BillHai** [ZipArchive/ZipArchive#329]
At first，it works well，and after handling some zip files，there comes a problem that two zip files cannot be opened，but what is most confusing me is that two files is as same as other files，same path，same way of naming。Now I have no idea what happens there，who can tell me why，thank you～

**Comment by huaTJ0210** [comment]
I also have this problem，but  only in iOS8.4.1；

**Comment by hite** [comment]
can open zip file which zipped by `commend line`, as follow:
>>2017-04-13 00:28:23:377 MyFitment[79597:4387337] success = 0, err = Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file"

**Comment by BillHai** [comment]
I found the reason，because our server engineer changed the algorithm of compress，there was some problem with zip files😂

**Comment by jhudsonWA** [comment]
Safe to close then?

**Comment by BillHai** [comment]
OK，I will close it then，but maybe haven't helped others too much.

**Comment by hite** [comment]
@jhudsonWA I found the reason of 'can't open a zip' : unzipFileAtPath don't support gzip files or something like that .just `zip a.zip a.file b.file`

**Comment by jhudsonWA** [comment]
No it wouldnt. This software only works with .zip files using the zip compression.
