### ISSUE TITLE
UTF8 file name string is corruption

### ISSUE THREAD

**Issue by hieunh161** [ZipArchive/ZipArchive#331]
Zip a file with special character and send it through network. When unzip the file name is corruption.
minizip/zip.c => Line995 should be
`
zi->ci.flag = 2056;
`
If dont change source, please public api for setting flag dynamically.

**Comment by jhudsonWA** [comment]
@Coeur Anything thoughts on this one? You have more experience with the latest minizip. This code has not changed from the minizip we use in 1.x vs 2.x.

**Comment by jhudsonWA** [comment]
Do you have documentation that shows what 2056 stands for? Right now it uses a 0 as the base flag for all calls. I'd be willing to entertain the idea of adding a override to allow a flag to be passed in (or a enum) but want to better understand this issue first.

**Comment by Coeur** [comment]
@hieunh161 on our [branch 2.0](https://github.com/ZipArchive/ZipArchive/tree/2.0), `zi->ci.flag = flagBase;` has been changed to `zi->ci.flag = flag_base | 8;`, as seen on https://github.com/nmoinvaz/minizip/blob/master/zip.c#L969, thanks to commit https://github.com/nmoinvaz/minizip/commit/c798d49c520350452df686afe91ac3b87f379731. Can you test it? If it's still an issue, can you report it on the minizip issue tracker?

**Comment by Coeur** [comment]
I'm closing this issue as there were no feedback for 2 months regarding the changes from version 2.0+
