### ISSUE TITLE
Xcode 8.3.1 warnings.

### ISSUE THREAD

**Issue by shahenantonyan** [ZipArchive/ZipArchive#332]
Gives warnings after updating Xcode 8.3.1.
1. SSZipArchive/SSZipArchive/minizip/unzip.c:1209:72: Passing 'const char *' to parameter of type 'const unsigned char *' converts between pointers to integer types with different sign.
2. SSZipArchive/SSZipArchive/minizip/unzip.c:1209:51: Implicit conversion loses integer precision: 'uLong' (aka 'unsigned long') to 'int'.
3. SSZipArchive/SSZipArchive/minizip/unzip.c:1209:82: Implicit conversion loses integer precision: 'unsigned long' to 'unsigned int'.

**Comment by jhudsonWA** [comment]
Yep, all of these are in another library that is used. I'm looking into it.

**Comment by jhudsonWA** [comment]
Fixed and deployed new version.
