### ISSUE TITLE
If file path has cyrillic symbols - this files ignores while zipping

### ISSUE THREAD

**Issue by Dalein** [ZipArchive/ZipArchive#334]

**Comment by jhudsonWA** [comment]
Try the [2.0](https://github.com/ZipArchive/ZipArchive/tree/2.0) branch. It has the latest upgrades to the unziping engine we use. Not sure if changes to symbol support have been included, but there have been a lot of chances from the one that ships in the 1.x branch.

**Comment by Coeur** [comment]
Try 2.0.8 once released, or the master branch now.

If any issue left, please provide a way for us to reproduce it.
