### ISSUE TITLE
unzip fails the first time, but then works on second try.

### ISSUE THREAD

**Issue by julapy** [ZipArchive/ZipArchive#336]
hi, have an issue which has been introduced into my app recently with the release of iOS (10.3 or 10.3.1) - prior to this unzipping was working fine.

im downloading a zip file from AWS using AFHTTPRequestOperation (AFNetworking lib).
on download completion i attempt to unzip the file.
the first attempt to unzip gives the error - `Error Domain=SSZipArchiveErrorDomain Code=-2 "failed to open file in zip file" UserInfo={NSLocalizedDescription=failed to open file in zip file}
Printing description of path:`
second attempt to download and unzip the file works.

i thought maybe there was an issue with the file not being available straight away after download so i put some delays before unzipping but this made no difference.

i have also tried downloading the zip files into the docs folder, copying them from the device via iTunes file sharing and they are totally fine, not corrupt and im able unzip them on my Mac.

drilling down into the ZipArchive code in `unzip.c` it fails at this point,
```
    if (err == UNZ_OK) {
        if (unz64local_getLong(&s->z_filefunc, s->filestream, &uMagic) != UNZ_OK)
            err = UNZ_ERRNO;
        else if (uMagic != LOCALHEADERMAGIC)
            err = UNZ_BADZIPFILE;
    }
```

the other thing is that sometimes (like 1 in 20) it will work on the first go.
such a weird bug!

any suggestions or ideas would be most appreciated.

im using latest ZipArchive release (v1.8.1)

cheers.

**Comment by julapy** [comment]
seems this issue is only occurring when the zip files are downloaded from AWS with `http` but the issue goes away when using `https` - no idea why... need to investigate.
please feel free to close this issue if indeed this doesn't have anything to do with ZipArchive.

**Comment by julapy** [comment]
ok getting closer to working this one out.
seems that sometimes when i download the zip from AWS,
extra bytes are being added to the beginning of the zipfile. 
i was able to compare and inspect successful and unsuccessful unzips using `zipinfo` terminal tool.
this is now looking like a server issue or something to do with AFNetworking...

but im now wondering if there is a way for ZipArchive to ignore these extra bytes at the beginning?

```
Zip file size: 10429142 bytes, number of entries: 20
warning [170428_spurs_mural_2_960.zip]:  5760 extra bytes at beginning or within zipfile
  (attempting to process anyway)
```

**Comment by jhudsonWA** [comment]
What are you using to download the files?

**Comment by jhudsonWA** [comment]
Ah AFNetworking. I'm more curious why extra bytes are being added (and not on https connections).

**Comment by julapy** [comment]
yeah thats what we're trying to work out... so strange!

**Comment by jhudsonWA** [comment]
If this is still an issue please reopen.
