### ISSUE TITLE
Unzip of a password protected zip file returns success, even with the wrong password

### ISSUE THREAD

**Issue by agreensh** [ZipArchive/ZipArchive#338]
The unzip gives lots of debug statements
`Set attributes failed for directory: /.../.../.../SOME_EXAMPLE_DIR`
so it hasn't successfully unzipped, but still reports success.

There is plenty of free disk space.
iOS 10.3.1, iPhone7

The zip file cannot be unzipped on Mac, Linux, Windows with an incorrect password, which correctly report password is incorrect.

**Comment by jhudsonWA** [comment]
Do have an example zip file you can share?

**Comment by Coeur** [comment]
I tried it, zipping with a password, unzipping with a wrong one.

With a wrong password:
* [`unzOpenCurrentFilePassword`](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/minizip/unzip.c#L1274) returns `UNZ_BADPASSWORD`
* [`int ret` becomes `UNZ_BADPASSWORD` at line 276](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L276)
* [`BOOL success` becomes `NO` at line 281](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L281)
* [We never enter the preserveAttributes block at line 554](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L554)
* [We never print "[SSZipArchive] Set attributes failed for directory" at line 558](https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L558)

I checked the logic of the code at the time of your message (code from 28th March 2017), and it was the same.

So your problem can't be really reproduced by me with the description that you gave. So I'll remove the "bug" label and close the issue for now. If you can provide more information or a reproducible case with ZipArchive 2.0.7 or newer, we'll re-open it.
