### ISSUE TITLE
2.0 Branch. Please test!

### ISSUE THREAD

**Issue by jhudsonWA** [ZipArchive/ZipArchive#347]
Hey all,

A new branch [2.0](https://github.com/ZipArchive/ZipArchive/tree/2.0) has been added. It merges in all the latest work to the base minizip library (Thanks @Coeur!), fixes some long standing bugs and does some code and project cleanup. As the minizip library is the brain of this library we would like some more testing before we make it live. If we could get some of you fine folks to give it a try that would be awesome. 

Thanks!

**Comment by Coeur** [comment]
Let's release it, and if anyone reports anything, we'll do a 2.0.1?

**Comment by jhudsonWA** [comment]
Alright! Merging into master and will release as 2.0!

**Comment by jhudsonWA** [comment]
Released!
