### ISSUE TITLE
the list of files in a password protected zip can be seen with 7zip

### ISSUE THREAD

**Issue by shalafi83** [ZipArchive/ZipArchive#349]
Hi,
that's the problem: if I create a password protected zip archive, using 7zip on Windows platform makes possible to open the zip and see the list of file that are inside the archive. 
If I try to extract even one of them, I'm correctly asked for the password, but I'd like that the user could not see the content.

Is there a way to avoid this?

Thank you

**Comment by Coeur** [comment]
That's by design. http://kb.winzip.com/kb/entry/147/
>To hide the names of the files in your encrypted Zip file, you can double zip them.
