### ISSUE TITLE
Possible folder inside the file name is too long, decompression success, but there is no unpacked folder

### ISSUE THREAD

**Issue by LiuQingying** [ZipArchive/ZipArchive#351]
This file.   http://administrator.yunoso.cc:8080/Uploads/Expression/2017-07-14/5968688d4e941.zip

I change the name of the file and unpack it properly。
Thanks for the answer。

**Comment by Coeur** [comment]
Thanks for reporting.
But just to be clear: iOS or macOS? Under which filesystem?

**Comment by Coeur** [comment]
In your example, folder name is `乖巧宝宝`.
* /usr/bin/unzip (on macOS Sierra) fails and name it `%A6%C8%C3+%A6%AA%A6%AA`
* Archive Utility.app (on macOS Sierra) fails and name it `π‘«…±¶±¶`
* Kekka succeeds
* ZipArchive 2.0.6 succeeds on iOS Simulator 11.0

The folder is obviously not _too long_. So I'll close this issue as not reproduced. Please clarify the problematic if you found a bug, and we'll reopen the issue if any and fix it.
