### ISSUE TITLE
Compiler Warnings in 2.0

### ISSUE THREAD

**Issue by jhudsonWA** [ZipArchive/ZipArchive#352]
@Coeur I did notice we are getting two warnings in 2.0

Implicit conversion loses integer precision: 'uLong' (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int')

from this line: zipInfo.external_fa = permissionsLong << 16L;

external_fa is defined as uint32_t in unz_file_info64_s (SSZipCommon.h) but it is assigned to by a long. Do you know, in any of the work you did if it is safe to cast down or make the uInt32_t a uint64_t?

**Comment by Coeur** [comment]
I think minizip reduced (or stabilized) its precision on that. One day I may look at it, but I can't predict when. Hum... let's say that if no one else finds an answer, I'll solve it in August 2017.

**Comment by jhudsonWA** [comment]
I see the change on the minizip project. Looks like it was made an int about 9 months ago. I'll just cast it down to remove the warning, and we can watch to see if it causes issues. I believe it should not.
