### ISSUE TITLE
Distinguish Between Different Files Unzipping Progress

### ISSUE THREAD

**Issue by tingxins** [ZipArchive/ZipArchive#358]
As the issue title. The question is that how to distinguish between different files unzipping progress?

As the progress delegate method, only passed two parameters(loaded & total), which **can not identify unzipping progress for different zip file**.

**- (void)zipArchiveProgressEvent:(unsigned long long)loaded total:(unsigned long long)total;**

**thanks!**

**Comment by Coeur** [comment]
Do you mean you wish to have the name of the previous/next file being unzipped sent to delegate? Or do you wish more precise size progress when there is one big file?

**Comment by tingxins** [comment]
Yeah. I mean that if the progress delegate passing the identified parameter of file , it could be better. Such as unzipping file name or others which can identify unzipping progress for different zip file.

**Comment by Coeur** [comment]
I see. For now you may to use the block callbacks instead of a delegate:

```
+ (BOOL)unzipFileAtPath:(NSString *)path
    toDestination:(NSString *)destination
    progressHandler:(void (^)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
    completionHandler:(void (^)(NSString *path, BOOL succeeded, NSError * __nullable error))completionHandler;

+ (BOOL)unzipFileAtPath:(NSString *)path
    toDestination:(NSString *)destination
    overwrite:(BOOL)overwrite
    password:(nullable NSString *)password
    progressHandler:(void (^)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
    completionHandler:(void (^)(NSString *path, BOOL succeeded, NSError * __nullable error))completionHandler;
```

In the `progressHandler`, you'll have access to what you want about the zip file.

Example:

```
    [SSZipArchive unzipFileAtPath:zipPath
                    toDestination:unzipPath
                        overwrite:YES
                         password:nil
                  progressHandler:^(NSString *entry, unz_file_info zipInfo, long entryNumber, long total) {
                      // access to zipPath, unzipPath, entry and zipInfo
                      // ...
                  }
                completionHandler:^(NSString *path, BOOL succeeded, NSError * __nullable error) {
                    // ...
                }];
```

**Comment by tingxins** [comment]
Got it! block maybe better. thanks.
