### ISSUE TITLE
Error Domain=SSZipArchiveErrorDomain Code=-3 "crc check failed for file"

### ISSUE THREAD

**Issue by shaolelng** [ZipArchive/ZipArchive#359]
I have a problem.
Error Domain=SSZipArchiveErrorDomain Code=-3 "crc check failed for file" UserInfo={NSLocalizedDescription=crc check failed for file}，
I don't know how to solve it?

**Comment by shaolelng** [comment]
I know why.My zip pack has been damaged.

**Comment by Coeur** [comment]
Did you put any empty folder or empty file in your archive? we have a known pending issue with empty files/folders when archiving with password.

Otherwise, was your zip damaged by SSZipArchive? If yes, can you describe how to reproduce the issue?

**Comment by derick182** [comment]
If it is helpful it happened to me when trying to compress files without extension

**Comment by Coeur** [comment]
@derick182 thank you for reporting your case, but I was not able to reproduce it. I took the SwiftExample from https://github.com/ZipArchive/ZipArchive/tree/master/SwiftExample and I renamed `1.md` to `1` and I was able to compress/uncompress with and without password without issue.

Please provide a sample that can reproduce the issue.

**Comment by Coeur** [comment]
Closing. Please provide more details if it's still an issue with version 2.0.6 or newer.
