### ISSUE TITLE
 Unknown type name 'z_crc_t'

### ISSUE THREAD

**Issue by ssladn** [ZipArchive/ZipArchive#360]
when i remove the SSZipArchive+Swift.swift then failed: Unknown type name 'z_crc_t' ？？？
this is i create a new prj in the Xcode 7.3

**Comment by jhudsonWA** [comment]
This library is only designed to work with Swift 3+. There is a branch with swift 2.3 support but it is older code and will not be updated.

We are not going to support back porting to older versions of Swift. If you want to try then it will be up to you to support yourself.

**Comment by jhudsonWA** [comment]
I assumed you meant you were using Swift but if not I should add that it is also designed for Xcode 8+ as well. 

That error tells me it can’t find the internal structures as defined in the .h files

**Comment by jhudsonWA** [comment]
Last one: is this a pod install or manual?

**Comment by ssladn** [comment]
Thank you! when i used pods is success. But if i down load the demo project and copy the SSZipArchive file to my project .It will show the error  Unknown type name 'z_crc_t'  in Xcode 7.3 and use the OC code. But in the Xcode 8.3 it was success. I don't know what happen.After that i use pods to install this is success.

**Comment by jhudsonWA** [comment]
Probably needed a library added (zlib). Glad it is working for you now.

Out of curiosity what iOS version were you trying to target and in what language?

**Comment by jhudsonWA** [comment]
Also did you copy all the SSZipArchive files in? It would need everything for a manual install.

**Comment by loyalwind** [comment]
The problem can be resolved perfectly when you write the following code in the crypt.h file!

```objc
typedef unsigned long z_crc_t; 
```

**Comment by Coeur** [comment]
@loyalwind 

Oh I see. Then I made this pull request to fix your issue: https://github.com/nmoinvaz/minizip/pull/136

Feel free to review it.

**Comment by Coeur** [comment]
I just installed Xcode 7 and I faced your issue! Actually, `typedef unsigned long z_crc_t;` is missing on older versions of zlib. I'll fix it properly.
