### ISSUE TITLE
Unzipping with `*progressHandler:completionHandler:` crashes when no space on device

### ISSUE THREAD

**Issue by markonikolovski** [ZipArchive/ZipArchive#361]
When unzipping in low space conditions, the library crashes on line 391 of `SSZipArchive.m`:

```obj-c
*error = [NSError errorWithDomain:@"SSZipArchiveErrorDomain" code:SSZipArchiveErrorCodeFailedToWriteFile userInfo:@{NSLocalizedDescriptionKey: message}];
```

As far as I can see, the `NSError` object is not assigned to the correct parameter. Instead of assigning to `*error` it should be assigned to `unzippingError`. 

```obj-c
unzippingError = [NSError errorWithDomain:@"SSZipArchiveErrorDomain" code:SSZipArchiveErrorCodeFailedToWriteFile userInfo:@{NSLocalizedDescriptionKey: message}];
```

When making this change the library correctly calls the completion block.

**Comment by jhudsonWA** [comment]
You are correct. I'll make the change and push a new version. Good catch. This particular case is hard to test for.

**Comment by jhudsonWA** [comment]
2.0.3 released. Thanks again! Please test if you can to confirm what you were seeing is indeed fixed.

**Comment by markonikolovski** [comment]
That's was really fast! Thanks a lot. I tested this earlier today, and the completion handler is properly called with the correct error.

**Comment by markonikolovski** [comment]
By the way, I used this small utility app to quickly fill the testing device's space: https://github.com/AppWerkstatt/NoMoreStorage

**Comment by jhudsonWA** [comment]
Won't let us do it as a automated test, but great for testing time to time. Thanks again!

**Comment by Coeur** [comment]
Thanks. For reference, the issue may have been introduced only in 2.0.2: #355

**Comment by jhudsonWA** [comment]
Yep, that’s what I noticed. Should of caught it. :)
