### ISSUE TITLE
exc_bad_access code=1 address=0x7

### ISSUE THREAD

**Issue by thereqwe** [ZipArchive/ZipArchive#362]
when i using [SSZipArchive unzipFileAtPath:zipPath toDestination: unzipPath]
 i meet the err msg:
 [directoriesModificationDates addObject: @{@"path": fullPath, @"modDate": modDate}];
 (NSMutableArray *) directoriesModificationDates = 0x0000000000000007
 what can i do to avoid this?

**Comment by wwwang89** [comment]
oh NO ,,,I meet the same crash error!!  when I use old SSZipArchive 1.4  version，the same zip Can unzip，but use the latest version ，It crashed，，Is there anything wrong，hope the author‘s Reply ，Thanks ~~

**Comment by jhudsonWA** [comment]
Is this using the latest version? Can you post some sample code you are using to unzip?

**Comment by jhudsonWA** [comment]
Meaning what are the paths for unzipPath

**Comment by Coeur** [comment]
@wwwang89 please provide a sample zip and we'll investigate.

**Comment by thereqwe** [comment]
[zipPath_gif_9c6cadb2623c95750f3c534518c838b7.zip](https://github.com/ZipArchive/ZipArchive/files/1192563/zipPath_gif_9c6cadb2623c95750f3c534518c838b7.zip)
this is my zip file

**Comment by wwwang89** [comment]
yeah，It's very strange，when I use  SSZipArchive 2.02 or 2.0.3 version in my company project, It crashed,whether it is a Chinese or English name，when I new a project or use SSZipArchive  ObjectiveCExample，the same ZIp file，it‘s ok！and I guess there some conflict files between my project and SSZipArchive ？

**Comment by wwwang89** [comment]
the crash picture below ：
![Uploading WX20170802-101812@2x.png…]()

**Comment by wwwang89** [comment]
<img width="976" alt="wx20170802-101812 2x" src="https://user-images.githubusercontent.com/3423535/28857054-1d898770-7779-11e7-97c4-b69a79e1b02b.png">

**Comment by Coeur** [comment]
@thereqwe no crash or error unzipping it with SSZipArchive 2.0.3

![screen shot 2017-08-02 at 13 55 37](https://user-images.githubusercontent.com/839992/28859532-5e7af6ae-778a-11e7-8836-eb980b37e1d3.png)

**Comment by thereqwe** [comment]
@wwwang89 zip file is not the reason.   i agree with u, maybe the project's configuration casue the crash.

**Comment by Coeur** [comment]
@wwwang89 you need to clean the derived data folder before re-building your company project: option+shift+command+K

**Comment by wwwang89** [comment]
@thereqwe yeah,I agree With you，Zip File is ok，when  I clean my cache，and  Rebuild my project ，I   Met the same problem，，So I‘m  confused。。really strange。。

**Comment by wwwang89** [comment]
@Coeur thanks,I do as you said ,but it's a pity,donot solve my problem，confused。。really strange。。

**Comment by Coeur** [comment]
@wwwang89 , I still believe it's a DerivedData issue:

1. close Xcode fully (CMD+Q): there should be no dot under the icon.
2. Delete `~/Library/Developer/DerivedData`
3. Empty the trash
4. re-install your pods: `pod deintegrate` then `pod install` then `pod update`
5. finally, and only now, re-open Xcode

**Comment by ksi1024** [comment]
Hi.
My app is also crashing on exactly the same line.
I've tried deleting DerivedData, but didn't solve the problem.

It seems directoriesModificationDates some how gets deallocated.

**Comment by Coeur** [comment]
Well, then please, anyone, share a project with the issue.

**Comment by li-jun** [comment]
Sorry for my bad english！I single-step debugging found that unzGetCurrentFileInfo returns the fileinfo, size_filename is always equal to 8, the file name is truncated, resulting in the back of the crash

**Comment by li-jun** [comment]
Solution: roll back to version 1.8.1

**Comment by Coeur** [comment]
Interesting, but can you share a project or git repository or full code where I can reproduce your issue?

**Comment by Coeur** [comment]
Lacking ways to reproduce the issue, I'm closing this now.
If you experience anything, share something that can reproduce the problem with SSZipArchive 2.0.7 or newer and we'll reopen the issue.

**Comment by Coeur** [comment]
@CrazyFanFan Thank you for your analysis. I'm reopening the issue, but I need to understand why we still need `unz_file_info_s`: maybe we could remove it?

**Comment by yishuiliunian** [comment]
看你坐标在上海，我还是中文描述吧。问题比较复杂。我们也遇到了这个crash，追查了一下是因为引入的多个库中都有结构体unz_file_info，但是他们的定义不一样（一个库是ZipArchive一个是Zip，还有是引入的.a中也存在这个结构体，我们在继续看为啥没报符号表冲突的问题）。在实际运行的时候，变量directoriesModificationDates被污染了。找了一下原因，是因为实际使用的unz_file_info的定义不是ZipArchive库中的，而是其他的。在Runtime时unz_file_info与ZipArchive中的定义的内部布局不一致。于是污染了堆栈，于是directoriesModificationDates指针就意外的被换成了脏数据。这也就是为什么，在调用之前加了一个没有啥用的fileInfoFake，就能正常使用的原因。 fileInfoFake所在的内部被污染了，防止了其他变量被污染。

造成这个问题的原因，是库冲突导致的。看了一下Zip、ZipArchive都直接源码引用了minizip的代码。为了避免这种冲突的问题，还是建议要么直接把minizip抽成一个库。要么重命名一下使用到的minizip符号。避免这种隐藏极深的问题。

**Comment by Coeur** [comment]
@yishuiliunian, please post in English: we can't read Chinese.

**Comment by Coeur** [comment]
@yishuiliunian can you link to this other `Zip` source code so that I can test the conflict?

**Comment by yishuiliunian** [comment]
https://github.com/marmelroy/Zip

**Comment by yishuiliunian** [comment]
sorry, i will use english. :)

**Comment by Coeur** [comment]
@yishuiliunian I was not able to reproduce the issue, despite building with both pods (SSZipArchive and Zip).

So I will need more informations:
* Is your project ObjC or Swift?
* What is your version of Xcode?
* Which version of Zip are you using: 1.1.0 or master?

All in all, https://github.com/marmelroy/Zip is a dangerous dependency to have because it's vulnerable to https://github.com/marmelroy/Zip/issues/151. So it's pointless to use it for now.

**Comment by Coeur** [comment]
@CrazyFanFan many methods in SSZipArchive.h have `unz_file_info` in their signature, so it's not possible to rename it without it being a breaking change.
Also, please read my previous comment regarding pod Zip being a dangerous dependency as it is, so compatibility with it is not meaningful for now.

I'll close this issue for now: if you happen to have a reproducible scenario, then please open a new issue.

**Comment by YangYiBo23** [comment]
> 看你坐标在上海，我还是中文描述吧。问题比较复杂。我们也遇到了这个crash，追查了一下是因为引入的多个库中都有结构体unz_file_info，但是他们的定义不一样（一个库是ZipArchive一个是Zip，还有是引入的.a中也存在这个结构体，我们在继续看为啥没报符号表冲突的问题）。在实际运行的时候，变量directoriesModificationDates被污染了。找了一下原因，是因为实际使用的unz_file_info的定义不是ZipArchive库中的，而是其他的。在Runtime时unz_file_info与ZipArchive中的定义的内部布局不一致。于是污染了堆栈，于是directoriesModificationDates指针就意外的被换成了脏数据。这也就是为什么，在调用之前加了一个没有啥用的fileInfoFake，就能正常使用的原因。 fileInfoFake所在的内部被污染了，防止了其他变量被污染。
> 
> 造成这个问题的原因，是库冲突导致的。看了一下Zip、ZipArchive都直接源码引用了minizip的代码。为了避免这种冲突的问题，还是建议要么直接把minizip抽成一个库。要么重命名一下使用到的minizip符号。避免这种隐藏极深的问题。

我直接修改这个unz_file_info_s结构体名字可不可以解决这个问题呢?

**Comment by CrazyFanFan** [comment]
> > 看你坐标在上海，我还是中文描述吧。问题比较复杂。我们也遇到了这个crash，追查了一下是因为引入的多个库中都有结构体unz_file_info，但是他们的定义不一样（一个库是ZipArchive一个是Zip，还有是引入的.a中也存在这个结构体，我们在继续看为啥没报符号表冲突的问题）。在实际运行的时候，变量directoriesModificationDates被污染了。找了一下原因，是因为实际使用的unz_file_info的定义不是ZipArchive库中的，而是其他的。在Runtime时unz_file_info与ZipArchive中的定义的内部布局不一致。于是污染了堆栈，于是directoriesModificationDates指针就意外的被换成了脏数据。这也就是为什么，在调用之前加了一个没有啥用的fileInfoFake，就能正常使用的原因。 fileInfoFake所在的内部被污染了，防止了其他变量被污染。
> > 造成这个问题的原因，是库冲突导致的。看了一下Zip、ZipArchive都直接源码引用了minizip的代码。为了避免这种冲突的问题，还是建议要么直接把minizip抽成一个库。要么重命名一下使用到的minizip符号。避免这种隐藏极深的问题。
> 
> 我直接修改这个unz_file_info_s结构体名字可不可以解决这个问题呢?

确保但个库内全部修改理论上可行；时间太久，有些记不清楚了，如果这个Struct最终传给了系统库的话，不建议修改，因为会引入别的问题。

**Comment by CrazyFanFan** [comment]
> > 看你坐标在上海，我还是中文描述吧。问题比较复杂。我们也遇到了这个crash，追查了一下是因为引入的多个库中都有结构体unz_file_info，但是他们的定义不一样（一个库是ZipArchive一个是Zip，还有是引入的.a中也存在这个结构体，我们在继续看为啥没报符号表冲突的问题）。在实际运行的时候，变量directoriesModificationDates被污染了。找了一下原因，是因为实际使用的unz_file_info的定义不是ZipArchive库中的，而是其他的。在Runtime时unz_file_info与ZipArchive中的定义的内部布局不一致。于是污染了堆栈，于是directoriesModificationDates指针就意外的被换成了脏数据。这也就是为什么，在调用之前加了一个没有啥用的fileInfoFake，就能正常使用的原因。 fileInfoFake所在的内部被污染了，防止了其他变量被污染。
> > 造成这个问题的原因，是库冲突导致的。看了一下Zip、ZipArchive都直接源码引用了minizip的代码。为了避免这种冲突的问题，还是建议要么直接把minizip抽成一个库。要么重命名一下使用到的minizip符号。避免这种隐藏极深的问题。
> 
> 我直接修改这个unz_file_info_s结构体名字可不可以解决这个问题呢?

我们当时的做法是去掉了功能重复的库，仅保留了其中一个；这样也避免了冲突

**Comment by hzw0407** [comment]
> uLong disk_offset;

How do you specifically modify the amendment

**Comment by hzw0407** [comment]
> I got this crash too. I import Zip and SSZipArchive. and crash at
> 
> ```
>             if (preserveAttributes) {
>                 NSDate *modDate = [[self class] _dateWithMSDOSFormat:(UInt32)fileInfo.dos_date];
>                 directoryAttr = @{NSFileCreationDate: modDate, NSFileModificationDate: modDate};
>   this line    >>>>[directoriesModificationDates addObject: @{@"path": fullPath, @"modDate": modDate}];
>             }
> ```
> 
> after many analytics, I found that if i add an instance of struct (unz_file_info) ,it is ok.
> 
> ![2018-10-08 4 17 20](https://user-images.githubusercontent.com/15794964/46598172-bbc80600-cb15-11e8-82ba-e04129099430.png)
> 
> So I suspect that this function is internally polluting my pointer. A look at the definition of this struct in Zip and SSziparchive shows a difference. Zip has one more variable "tmu_date". so the layout of memory in the two libriary is difference. and in the runtime, it use the zip's one. then crash.
> 
> ```
> typedef struct unz_file_info_s
> {
>     uint16_t version;               /* version made by                 2 bytes */
>     uint16_t version_needed;        /* version needed to extract       2 bytes */
>     uint16_t flag;                  /* general purpose bit flag        2 bytes */
>     uint16_t compression_method;    /* compression method              2 bytes */
>     uint32_t dos_date;              /* last mod file date in Dos fmt   4 bytes */
>     uint32_t crc;                   /* crc-32                          4 bytes */
>     uint32_t compressed_size;       /* compressed size                 4 bytes */
>     uint32_t uncompressed_size;     /* uncompressed size               4 bytes */
>     uint16_t size_filename;         /* filename length                 2 bytes */
>     uint16_t size_file_extra;       /* extra field length              2 bytes */
>     uint16_t size_file_comment;     /* file comment length             2 bytes */
>     
>     uint16_t disk_num_start;        /* disk number start               2 bytes */
>     uint16_t internal_fa;           /* internal file attributes        2 bytes */
>     uint32_t external_fa;           /* external file attributes        4 bytes */
>     
>     uint64_t disk_offset;
> } unz_file_info;
> ```
> 
> ```
> typedef struct unz_file_info_s
> {
>     uLong version;              /* version made by                 2 bytes */
>     uLong version_needed;       /* version needed to extract       2 bytes */
>     uLong flag;                 /* general purpose bit flag        2 bytes */
>     uLong compression_method;   /* compression method              2 bytes */
>     uLong dosDate;              /* last mod file date in Dos fmt   4 bytes */
>     uLong crc;                  /* crc-32                          4 bytes */
>     uLong compressed_size;      /* compressed size                 4 bytes */
>     uLong uncompressed_size;    /* uncompressed size               4 bytes */
>     uLong size_filename;        /* filename length                 2 bytes */
>     uLong size_file_extra;      /* extra field length              2 bytes */
>     uLong size_file_comment;    /* file comment length             2 bytes */
> 
>     uLong disk_num_start;       /* disk number start               2 bytes */
>     uLong internal_fa;          /* internal file attributes        2 bytes */
>     uLong external_fa;          /* external file attributes        4 bytes */
> 
>     tm_unz tmu_date;  <------ this line
>     uLong disk_offset;
> } unz_file_info;
> ```
> 
> the unzip.h from minizip. so please modify it.

请问修改具体指的是什么呢？

**Comment by hzw0407** [comment]
> 接把minizip

重命名一下使用到的minizip符号 这个是什么意思呢

**Comment by YangYiBo23** [comment]
> > 接把minizip
> 
> 重命名一下使用到的minizip符号 这个是什么意思呢

我修改的是unz_file_info_s这个结构体名称, 但是不行, 还是crash

**Comment by hzw0407** [comment]
> > > 接把minizip
> > 
> > 
> > 重命名一下使用到的minizip符号 这个是什么意思呢
> 
> 我修改的是unz_file_info_s这个结构体名称, 但是不行, 还是crash
我也是 实在不知道怎么修改了

**Comment by YangYiBo23** [comment]
> > > > 接把minizip
> > > 
> > > 
> > > 重命名一下使用到的minizip符号 这个是什么意思呢
> > 
> > 
> > 我修改的是unz_file_info_s这个结构体名称, 但是不行, 还是crash
> > 我也是 实在不知道怎么修改了

因为SSZipCommon.h里边和minizip中都定义了一个unz_file_info_s结构体, 根据yishuiliunian大神的说法, 应该是这两个结构体指针在运行时污染了, 我的做法是删除SSZipCommon.h直接使用minizip进行解压, 然后可以了,

**Comment by hzw0407** [comment]
> > > > > 接把minizip
> > > > 
> > > > 
> > > > 重命名一下使用到的minizip符号 这个是什么意思呢
> > > 
> > > 
> > > 我修改的是unz_file_info_s这个结构体名称, 但是不行, 还是crash
> > > 我也是 实在不知道怎么修改了
> 
> 因为SSZipCommon.h里边和minizip中都定义了一个unz_file_info_s结构体, 根据yishuiliunian大神的说法, 应该是这两个结构体指针在运行时污染了, 我的做法是删除SSZipCommon.h直接使用minizip进行解压, 然后可以了,

我刚刚也改了 我是直接在SSZipCommon.h里面做了修改 新增了tm_unz这个结构体 也可以了

**Comment by mqlsq** [comment]
> tm_unz



> > > > > > 接把minizip
> > > > > 
> > > > > 
> > > > > 重命名一下使用到的minizip符号 这个是什么意思呢
> > > > 
> > > > 
> > > > 我修改的是unz_file_info_s这个结构体名称, 但是不行, 还是crash
> > > > 我也是 实在不知道怎么修改了
> > 
> > 
> > 因为SSZipCommon.h里边和minizip中都定义了一个unz_file_info_s结构体, 根据yishuiliunian大神的说法, 应该是这两个结构体指针在运行时污染了, 我的做法是删除SSZipCommon.h直接使用minizip进行解压, 然后可以了,
> 
> 我刚刚也改了 我是直接在SSZipCommon.h里面做了修改 新增了tm_unz这个结构体 也可以了

能不能指导一下，你的SSZipCommon.h增加tm_unz后是怎么样的结构

**Comment by BiYJ** [comment]
SSZipArchive.m 增加一行 unz_file_info fileInfoFake; 之后不报错了
![image](https://github.com/ZipArchive/ZipArchive/assets/49390558/59fac36e-27bd-4e2a-8ad5-23ccf3890058)

**Comment by lirongfei123** [comment]
In my case, i just rename all the funtion that name start with unz+[A-Z]
the regex is unz([A-z])
replace unz$1
solved my problem
