### ISSUE TITLE
Error reporting on Cordova project

### ISSUE THREAD

**Issue by tianxiawoyougood** [ZipArchive/ZipArchive#366]
There are 20 errors in the ioapi_buf.c file.

**Comment by Coeur** [comment]
Please
* share your project,
* or share your error messages,
* or describe how you installed ZipArchive (did you use https://github.com/blakgeek/cordova-plugin-cocoapods-support ?)
* or report the issue directly to the maintainer of ioapi_buf.c, which is https://github.com/nmoinvaz/minizip/

thank you

**Comment by Coeur** [comment]
Curious, I took the trouble to try ZipArchive with Cordova. I read the doc, and I performed all the following commands for the first time.

First install npm:

    $ brew install node

Then install cordova:

    $ npm install -g cordova

Then create an app for ios:

    $ cordova create MyApp
    $ cd MyApp
    $ cordova platform add ios

Then add cocoapods support:

    $ cordova plugin add cordova-plugin-cocoapod-support --save

Then add SSZipArchive in config.xml:

    <platform name="ios">
        <pod name="SSZipArchive" />
    </platform>

Then fix [some current bug in cordova](https://github.com/phonegap/ios-sim/issues/210):

    $ cd platforms/ios/cordova/node_modules/
    $ npm install ios-sim@latest
    $ cd ../../../..

Then build:

    $ cordova build ios

There were no warning at all for *ioapi_buf.c*.

**Comment by jhudsonWA** [comment]
@Coeur :)

**Comment by tianxiawoyougood** [comment]
![wx20170810-113836](https://user-images.githubusercontent.com/9163388/29153506-7d3eaf90-7dc0-11e7-9faf-2bc99c23fe5b.png)
I've solved the problem.
