### ISSUE TITLE
watchOS and tvOS targets would be nice to have

### ISSUE THREAD

**Issue by ezathashim** [ZipArchive/ZipArchive#367]

**Comment by Coeur** [comment]
The podspec does have such targets: https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive.podspec

Do you mean example targets for testing?

**Comment by ezathashim** [comment]
No, I like to compile frameworks as a subproject in my Main Project. For this to work, I would need an actual watchOS target in the ZipArchive project.

I guess there are other ways to do it, but it's much clearer to me when I do it this way.

**Comment by Coeur** [comment]
It's the same, that's also how Carthage works, by looking at the actual available targets.
I've added tvos in 75dad5ea8db8bd173f09ccd81c713ec9c8049067  and watchos in 94da75db53e2075e0feec48bdf9b821cde641a20. But I haven't tested it.

**Comment by Coeur** [comment]
OK, I tested it for tvOS and it was working. I can assume it works for watchOS too. It will be available with ZipArchive 2.0.5, or you can simply target the branch "master" to get the latest commit.

**Comment by ezathashim** [comment]
Really? When I compiled before adding the 2 files, the compiler gave me warnings in XCode. Maybe it’s because I don’t use Carthage?

**Comment by Coeur** [comment]
Please describe the warnings that you are facing. Your initial request was only to add targets, which I did. :)

**Comment by ezathashim** [comment]
Sorry for the last comment. It was a post to a wrong thread.

Thanks!
