### ISSUE TITLE
Add compression level to zip creation methods

### ISSUE THREAD

**Issue by luckyclan** [ZipArchive/ZipArchive#369]
I was thinking of filing a pull request to add the following methods:

```objectivec
+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath keepParentDirectory:(BOOL)keepParentDirectory withPassword:(nullable NSString *)password withCompressionLevel:(int)level andProgressHandler:(void(^ _Nullable)(NSUInteger entryNumber, NSUInteger total))progressHandler;
- (BOOL)writeFileAtPath:(NSString *)path withFileName:(nullable NSString *)fileName withPassword:(nullable NSString *)password withCompressionLevel:(int)level;
- (BOOL)writeData:(NSData *)data filename:(nullable NSString *)filename withPassword:(nullable NSString *)password withCompressionLevel:(int)level;
```

to be able to customize the compression level (we currently need a lower compression level to make zipping faster in our project).

However, would that still be within the scope of the ZipArchive repo (i.e. is there a chance it would be merged upstream)?

**Comment by luckyclan** [comment]
Could you reply our question  - will you accept pull request we will prepare with that feature?

**Comment by Coeur** [comment]
Please create a pull request, it's always welcome.
Then I'll be commenting on it if changes are needed before merging.

**Comment by jhudsonWA** [comment]
Yep, just want to backup @Coeur. Pull requests are always welcome. The only thing I would say is if changes are required in the minizip to support these methods files those should first be proposed for merge here: https://github.com/nmoinvaz/minizip

**Comment by Coeur** [comment]
Don't worry @jhudsonWA, there won't need any change on minizip, as we're currently using `zipOpenNewFileInZip3()` which already support a compression level parameter, currently set at `Z_DEFAULT_COMPRESSION`.

**Comment by Coeur** [comment]
Oh, well, I'm writing this feature currently. It will be ready soon.
