### ISSUE TITLE
Unzip to special path, but nothing

### ISSUE THREAD

**Issue by JasonYaoSiXu** [ZipArchive/ZipArchive#370]
for example:
  zipfilepath:a/b/c.zip
  destination: a/b/d
  when i called [SSZipArchive unzipFileAtPath:zipfilepath toDestination: destination]; in ios
  destination a/b/d/ nothing, but have a/b/c and a/b/c.zip why

**Comment by Coeur** [comment]
Thank you for trying ZipArchive, Jason.

The [example usage of ZipArchive in ObjectiveC](https://github.com/ZipArchive/ZipArchive/tree/master/ObjectiveCExample) is exactly doing what you are describing:
* zipfilepath is temp/cache/udid1.zip
* destination is temp/cache/udid2/

It's been the reference for testing ZipArchive for quite some time. Did you create folder `d` in your example? Do you have write permissions in folder `d`? Can you fork ZipArchive and modify the example project to demonstrate the issue that you are facing?
