### ISSUE TITLE
Background Unzipping

### ISSUE THREAD

**Issue by tharhtet** [ZipArchive/ZipArchive#371]
Since I extract the zip file around 600M, if the app will sleep, is there any problem? Does this library already support background unzip process? Thanks.

**Comment by jhudsonWA** [comment]
I've always just told the OS to not sleep during the unzip process. In Swift that looks like this:

UIApplication.shared.isIdleTimerDisabled = true

**Comment by Coeur** [comment]
@tharhtet does that answer your question?

**Comment by jhudsonWA** [comment]
As for background unzipping that would be up to you to wrap in a background process. But I still suggest just not allowing the system to go to sleep while you are unzipping. I'm going to close this. Re-open if you have more questions.
