### ISSUE TITLE
Nested zip files not unzipped

### ISSUE THREAD

**Issue by Alyn-zz** [ZipArchive/ZipArchive#380]
Hi,
I have some issues to unzip nested zip files.

In breakpoint mode (just after log `"Unzipping nested .zip file:  %@"`, line 423), if I tried to manually unzip file in simulator's folder, i've got an error (in french: 'Erreur 2 - Fichier ou répertoire inexistant'). If I wait until all the extraction process is done, I can manually unzip these nested files.

In SSZipArchive.m file, if I move the line 429 (`fclose(fp);`) before `if` statement, it works.
EDIT: sorry moving this line doesn't work (only in breakpoints mode ...). So I had to browse unzipped directory to search for nested .zip files.

Is it a bug ? Or is there something I've missed to allow unzipping nested files ?
If this is a bug, can you unzip the file within a folder with the same name as the zip file ?

Thx in advance,

**Comment by Coeur** [comment]
maybe related: https://github.com/ZipArchive/ZipArchive/issues/319

**Comment by Coeur** [comment]
@Alyn-zz can you give us a sample zip with with the issue?

**Comment by Alyn-zz** [comment]
Hi,
Please find attached a zip file.
I'm using XCode 9.0, with iOS 11.
Thx a lot,
Aline
[randstad.zip](https://github.com/ZipArchive/ZipArchive/files/1367964/randstad.zip)

**Comment by Coeur** [comment]
Confirmed. It looks like `unzSearchCentralDir(&us.z_filefunc, &central_pos, us.filestream)` is returning an error when nested.

**Comment by Coeur** [comment]
Seems it was broken since at least 24th October 2015. Well, I made a pull request to fix it.

**Comment by Alyn-zz** [comment]
Hi,
I've updated pod to 2.1.1 but it still doesn't work :(
Is it already available ?

Thx,

Aline

**Comment by Coeur** [comment]
@Alyn-zz did you try with the new function?

```
+ (BOOL)unzipFileAtPath:(NSString *)path
          toDestination:(NSString *)destination
     preserveAttributes:(BOOL)preserveAttributes
              overwrite:(BOOL)overwrite
         nestedZipLevel:(NSInteger)nestedZipLevel
               password:(nullable NSString *)password
                  error:(NSError **)error
               delegate:(nullable id<SSZipArchiveDelegate>)delegate
        progressHandler:(void (^_Nullable)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
      completionHandler:(void (^_Nullable)(NSString *path, BOOL succeeded, NSError * _Nullable error))completionHandler;
```

As documented, it will only work with this function and a nestedZipLevel != 0.

**Comment by Alyn-zz** [comment]
Arf yes it's unzipped, sorry...
Unfortunately, I need zip files to be unzipped in a separate folder so I can't use this new functionality yet :( (because there are multiple nested zip files actually).
I saw this request was already submitted so I'll do it manually until then !

Thank you for your reactivity !

Aline
