### ISSUE TITLE
SSZipArchiveErrorDomain Code=-3 "crc check failed for file"

### ISSUE THREAD

**Issue by shaolelng** [ZipArchive/ZipArchive#382]
Error Domain=SSZipArchiveErrorDomain Code=-3 "crc check failed for file" UserInfo={NSLocalizedDescription=crc check failed for file}

ZipArchive, 2.0.7.

Hello, I used ZipArchive to unzip a zip file a few days ago,which shows this error.But  after 3 days,It  works very well.

Now it shows the same error on my another zip file.I need your help.
I wonder what caused this  error.

<img width="898" alt="2017-09-21 5 01 52" src="https://user-images.githubusercontent.com/12619761/30687697-9c24a8f2-9eee-11e7-8ce4-7c45f3149319.png">
Thank you.

**Comment by Coeur** [comment]
Can you share the zip file?

**Comment by shaolelng** [comment]
I'm so sorry,ZipArchive has no problem.
It was my zip file has a problem.I found that the zip file I downloaded using the Google browser can unzip archive.But  the zip file  downloaded  using my app,or using other browsers  can't  unzip.
Finally, we found that the problem was caused by our service.And now they have solved the problem completely.
Thank you very much.
I will close this issue.
Thx.
