### ISSUE TITLE
why I run analyze the code has so many warning？

### ISSUE THREAD

**Issue by YanYuYunYuan** [ZipArchive/ZipArchive#386]
<img width="342" alt="6a06aac2-09ef-4c70-b99b-e4a0d435082c" src="https://user-images.githubusercontent.com/13757389/30997003-5ce15622-a4f7-11e7-9b8a-8602460b652e.png">
How can I fix them?

**Comment by Coeur** [comment]
May I suggest to upgrade to latest version of SSZipArchive?
