### ISSUE TITLE
Support unzipping IncorrectHeaders.zip

### ISSUE THREAD

**Issue by Coeur** [ZipArchive/ZipArchive#389]
File with Incorrect Headers: https://github.com/ZipArchive/ZipArchive/blob/master/ObjectiveCExample/ObjectiveCExampleTests/Fixtures/IncorrectHeaders.zip

We have a test for it, `testUnzippingTruncatedFileFix`, disabled because we don't support unzipping it correctly yet.

My tests with third parties on macOS:
* Archive Utility 10.10 (81) succeeds at unzipping it
* Keka 1.0.12 (1786) fails
* The Unarchiver 3.11.3 (115) succeeds
* /usr/bin/unzip 6.00 of 20 April 2009 succeeds

**Comment by Coeur** [comment]
I've made a request at minizip too: https://github.com/nmoinvaz/minizip/issues/159

**Comment by Coeur** [comment]
Oh, strange, unzipping this file was working in version 0.3.2 of SSZipArchive.

**Comment by Coeur** [comment]
Actually, the fix is available in #19. I would just need to reapply it.

**Comment by Coeur** [comment]
Hum not so fast, it makes the test `testUnzippingWithUnicodeFilenameInside` to fail.

**Comment by jhudsonWA** [comment]
Yep, I disabled the test because it required that fix to minizip. But once I reapplied the fix to the latest minizip (at the time), it broke other tests. The hope was to keep minizip as close to upstream as possible so I kept the test disabled as most headers will fine (in theory)

**Comment by Coeur** [comment]
I made a pull request for minizip here https://github.com/nmoinvaz/minizip/pull/160.

I found https://github.com/ZipArchive/ZipArchive/issues/143 saying there is an example of what would be broken. I need to investigate that.

I also just discovered that it's a duplicate of https://github.com/ZipArchive/ZipArchive/issues/211

**Comment by Coeur** [comment]
I've tested the 3 tests and files from #143, and they all pass with my fix. So it's good. :)

**Comment by jhudsonWA** [comment]
Great! : )

**Comment by Coeur** [comment]
I consider it done in #391.
