### ISSUE TITLE
Incorrect password always returning success

### ISSUE THREAD

**Issue by eytanschulman** [ZipArchive/ZipArchive#395]
When calling this method in Swift: SSZipArchive.unzipFile(atPath: <#T##String#>, toDestination: <#T##String#>, overwrite: <#T##Bool#>, password: <#T##String?#>, progressHandler: <#T##(String, unz_file_info, Int, Int) -> Void#>, completionHandler: <#T##(String, Bool, Error?) -> Void#>),

with an incorrect password, the completion handler's success property always returns true. 

The same is true for the Bool that this function returns, and is true for the version of the function that throws an error.

**Comment by Coeur** [comment]
I think I made a fix for that recently. Please test version 2.1.0 when it will be released (in the coming 48h), or test the master branch from git.

**Comment by eytanschulman** [comment]
Pulling from master seems to work, thanks for your work! @Coeur
