### ISSUE TITLE
[SSZipArchive] Failed to set attributes - whilst setting permissions

### ISSUE THREAD

**Issue by xiongbingyang** [ZipArchive/ZipArchive#401]
I upgrade the SSZipArchive to version 2.1.0, it tells mistakes in the console.Details in the picture.But, when I use 1.8.1 version,It is normal to unzip files.
![image](https://user-images.githubusercontent.com/14078005/31420475-534ea7ae-ae07-11e7-8416-8ed854a40ff4.png)
![image](https://user-images.githubusercontent.com/14078005/31420695-bdb08904-ae08-11e7-96d4-06caf69bcecc.png)

**Comment by Coeur** [comment]
An EXC_BAD_ACCESS sounds like you didn't properly rebuilt the dependency. You may want to clear your derived data.

As for the "Failed to set attributes", please provide a sample zip or a way to reproduce the issue. You can eventually clone the ZipArchive repository and attempt to modify the sample project to demonstrate your issue.

**Comment by xiongbingyang** [comment]
I clear the derived data and It reproduce again in my project, but can not reproduce the issue in anther project with version 2.1.0

**Comment by Coeur** [comment]
Then.. @xiongbingyang 

1. try `pod uninstall` then `pod install` then `pod update` with CocoaPods 1.3.1
2. try to `git clone` your own project in a new folder (and I mean git cloning, not copy-pasting)

**Comment by xiongbingyang** [comment]
I have tried that you tell,but also can not solve the problem.But in anthor project I can not reproduce the issue.Now, I decide to use the version 1.8.1. Thanks a lot.

**Comment by Coeur** [comment]
If git clone doesn't solve the problem, then it technically means that you did reproduce the issue.
So just share with me an access to your project.
