### ISSUE TITLE
Z_BUF_ERROR happening inside zlib

### ISSUE THREAD

**Issue by alexhunsley** [ZipArchive/ZipArchive#404]
I'm unzipping a zip file that's 18MB in size. Around half way through, it stops unzipping the files (a mix of TXT and PDF files) and returns NO (i.e. fails). 

Stepping into the SSZipArchive code and then into zlib, I can see that the problem happens inside the unzReadCurrentFile function at this call:

   err = inflate(&s->pfile_in_zip_read->stream, flush);

The inflate call is returning Z_BUF_ERROR. Any hints as to what is happening or if I can fix it?

I sadly can't provide the zip file as it contains confidential material.

**Comment by Coeur** [comment]
Can you please confirm which version of ZipArchive you are using? There was an issue in 2.1.0, fixed in 2.1.1.

**Comment by alexhunsley** [comment]
Hi, I'm using the CocoaPod which is 2.1.0, so I'll try 2.1.1, thanks.

**Comment by Coeur** [comment]
Ah ah, sorry for the trouble using 2.1.0.
I released 2.1.1 as a hotfix as soon as I got aware of the issue: https://github.com/ZipArchive/ZipArchive/releases/tag/v2.1.1

**Comment by alexhunsley** [comment]
Yup, 2.1.1 works for me, thanks for prompt response!
