### ISSUE TITLE
主线程卡死

### ISSUE THREAD

**Issue by survivorsfyh** [ZipArchive/ZipArchive#406]
您好,请问我执行该解压后,会导致解压期间主线程卡死,是必须要异步执行该方法么?
[SSZipArchive unzipFileAtPath:downloadPath toDestination:destinationPath overwrite:YES password:nil error:&error delegate:self]

**Comment by Coeur** [comment]
Hum... Google translate:
>The main thread stuck
>
>May I ask the implementation of the decompression, will lead to decompression during the main thread stuck, it is necessary to implement the method asynchronously?

**Comment by jhudsonWA** [comment]
Ah, Yes. If you want the decompression to be asynchronous then it should be fired on it's own operation queue or thread.  

是。如果希望解压缩是异步的，那么它应该在自己的队列或线程上被触发。

**Comment by survivorsfyh** [comment]
thank u for u answer,if the running method causes the main thread to die,it`s normal;
i have started asynchronously to execute the call to this method.

**Comment by survivorsfyh** [comment]
but i also have a question that when i invoke the asynchronous method,
i will end the decompression method and i need manually switch to the main thread,
i feel like there`s something wrong,would u please advise,
thank u!

for example:
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
      NSError *error = nil;
      if ([SSZipArchive unzipFileAtPath:downloadPath toDestination:destinationPath overwrite:YES password:nil error:&error delegate:self]) {
            do somethings.
      }
      else {
            do somethings.
      }
      
      dispatch_async(dispatch_get_main_queue(), ^{
            if (results) {
                results(dataSource, error);
            }
        });
};

**Comment by Coeur** [comment]
Well, why would we return to the main thread from the lib?
Main thread is used for UI, while zipping/unzipping is unrelated to UI.

**Comment by survivorsfyh** [comment]
i need to turn the results back to the UI;
so call the main thread in asynchrony;

**Comment by Coeur** [comment]
Then, yes, you need to call `dispatch_async(dispatch_get_main_queue()` yourself. :)

**Comment by survivorsfyh** [comment]
yes,i do it after;
thank u for u advice!
