### ISSUE TITLE
Undefined symbols for architecture armv7: "OBJC_CLASS$_SSZipArchive"

### ISSUE THREAD

**Issue by DrDRoarty** [ZipArchive/ZipArchive#407]
Tried it both with cocoa pods and manually adding the folders and lib
Cant get it working at all, just get error

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in controller
ld: symbol(s) not found for architecture armv7

I am sure i am missing something but after 2 days and no progress i am pulling my hair out

Searched and searched online for help but to no avail, loads of ideas but none worked for me
Pity it looks like just what i need

Got an idiots guide please

**Comment by jhudsonWA** [comment]
Give me some details about your project? Swift based, ObjectiveC based? What version of Xcode? In your project build settings what are the values for Build Active Architecture Only and Valid Architectures?

Finally what iOS sdk version are you targeting?

**Comment by DrDRoarty** [comment]
Thank you so much for responding
I am using Obj C, Xcode Version 9
IOS Deployment Target 9.0
 Build Active Architecture Only - set to yes
Valid Architectures = //:configuration = Debug
VALID_ARCHS = arm64 armv7s armv7
//:configuration = Release
VALID_ARCHS = arm64 armv7s armv7

Anything else you need?

Thanks

**Comment by Coeur** [comment]
Focus on trying with CocoaPods, because it's the safest way to get it correctly configured.

In your Podfile, you may want:
```
platform :ios, '9.0'
use_frameworks!

abstract_target 'default_pods' do
    pod 'SSZipArchive', '~> 2.1'

    target 'MyAppTarget'
end
```

And your version of CocoaPods should currently be 1.3.1 or 1.4.0.

**Comment by DrDRoarty** [comment]
Thanks for the response Coeur

CocoaPod Version 1.3.1

I have made sure the pod file is exactly as you say and the pod is loaded correctly, i am not getting any syntax errors when creating the object SSZipArchive, however as soon as i try to build the project 2 errors come up



1. Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in MyTableViewController.o
ld: symbol(s) not found for architecture arm64
2. clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any other suggestions gratefully received

**Comment by Coeur** [comment]
@DrDRoarty, well, please share a project that can reproduce the issue.
You'll notice that our ObjectiveCExample is using CocoaPods 1.3.1 without this issue:
https://github.com/ZipArchive/ZipArchive/blob/master/ObjectiveCExample/Podfile.lock

**Comment by DrDRoarty** [comment]
Thank you to Coeur and jhudsonWA 

I am sorry but i have wasted your time, i found the issue, i have  project with many pods and the way i was calling one of the pods was getting in the way, a schoolboy error and i hold my head in shame

I  referred to a backup of the project and followed the instructions by both of you and made sure everything was being called correctly, cleaned and built the project and it built correctly, i have yet to create a zip file but i am sure all will go right from here

Thanks again Chaps - Your help and time is greatly appreciated.

**Comment by jhudsonWA** [comment]
We have all been there. :) Let us know if something else comes up :)
