### ISSUE TITLE
the decompress the problem of success rate: failed to open zip file

### ISSUE THREAD

**Issue by survivorsfyh** [ZipArchive/ZipArchive#408]
Decompression failure rate is very hight,when I perform the decompression operation;
i dont know what`s going to happen.

**Comment by survivorsfyh** [comment]
Can u give me some advice,thank u!
This is my code:

dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
        NSError *error = nil;
        if ([SSZipArchive unzipFileAtPath:downloadPath toDestination:destinationPath overwrite:YES password:nil error:&error delegate:self]) {// Zip Succeed
            NSLog(@"Zip Succeed --- %@", destinationPath);
            
            // zip succeed delete file
            [self deleteCurrentDownloadToLocalFileWithPath:downloadPath];

        }
        else {// Zip Failure
            NSLog(@"Zip Failure --- %@", error);
            
            // zip failure delete file
            [self deleteCurrentDownloadToLocalFileWithPath:downloadPath];

        }
        
        dispatch_async(dispatch_get_main_queue(), ^{// call back result to ui
            if (results) {
                results(dataSource, error);
            }
        });
        
    });

**Comment by Coeur** [comment]
What kind of failures?
* same file uncompressed multiple times or different files?
* archives from known sources to be reliable, or arbitrary user provided archives?
* with enough disk space?
* with symbolic links?
* on iOS or macOS?
* with which version of ZipArchive?
* you have an `NSLog(@"Zip Failure --- %@", error);`, but you didn't gave us the the log of the error.
* could you try this method instead:
```
BOOL success = [SSZipArchive unzipFileAtPath:downloadPath
                                   toDestination:destinationPath
                              preserveAttributes:YES
                                       overwrite:YES
                                  nestedZipLevel:0
                                        password:nil
                                           error:&error
                                        delegate:self
                                 progressHandler:nil
                               completionHandler:^{ /* CHECK IF SUCCESS HERE */ }];
```

:)

**Comment by survivorsfyh** [comment]
I tried to use the method you provided,the results are as follows:
a compressed file is compressed only once;
and archives from known sources to be reliable;
and with enough disk space;
on iOS;
the ZipArchive Version is 2.1.1;
the zip failure error is :
Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file" UserInfo={NSLocalizedDescription=failed to open zip file}

**Comment by Coeur** [comment]
You get _failed to open zip file_ when the downloadPath is incorrect or the file is missing.

**Comment by survivorsfyh** [comment]
the problem has been solved, and finally the reason is locked to the file processing, not the result of unzipping.
thank for u help!

**Comment by Coeur** [comment]
no problem :)
