### ISSUE TITLE
instruments detected small leak

### ISSUE THREAD

**Issue by julapy** [ZipArchive/ZipArchive#410]
https://github.com/ZipArchive/ZipArchive/blob/6b302a33b1a7505caec68518ac74f07443f082f0/SSZipArchive/SSZipArchive.m#L350

<img width="1023" alt="untitled" src="https://user-images.githubusercontent.com/331382/31881517-7ba34322-b82f-11e7-948c-2abaca2502c7.png">

**Comment by Coeur** [comment]
Thanks, confirmed. I'll fix it for next release.

**Comment by Coeur** [comment]
fixed on master
