### ISSUE TITLE
Any example of using NSURLSessionDownloadTask

### ISSUE THREAD

**Issue by bishalg** [ZipArchive/ZipArchive#411]
I am using NSURLSessionDownloadTask to download "**zip**" from web-service.
And need to extract and use those extracted files for project.

```
    NSURL *url = [NSURL URLWithString:urlString];
    if (url == nil) return;

    NSURLSessionConfiguration *backgroundSessionConfiguration = [NSURLSessionConfiguration defaultSessionConfiguration];
    self.backgroundSession = [NSURLSession sessionWithConfiguration:backgroundSessionConfiguration
                                                           delegate:self
                                                      delegateQueue:[NSOperationQueue mainQueue]];
    
    NSURLSessionDownloadTask *downloadTask = [self.backgroundSession
                                              downloadTaskWithURL:url
      completionHandler:^(NSURL *location, NSURLResponse *response, NSError *error) {
          if (error == nil) {
              NSLog(@"Temporary file = %@", location);

              NSError *err = nil;
              NSFileManager *fileManager = [NSFileManager defaultManager];
              NSString *docsDir = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];

              NSString *unzipPath = [self tempUnzipPath];
              [SSZipArchive unzipFileAtPath:docsDir toDestination:unzipPath];
              
              /*
              NSURL *docsDirURL = [NSURL fileURLWithPath:[docsDir stringByAppendingPathComponent:@"out.zip"]];
              if ([fileManager moveItemAtURL:location
                                       toURL:docsDirURL
                                       error:&err]) {
                  NSLog(@"File is saved to = %@", docsDir);
                  [SSZipArchive unzipFileAtPath:docsDir toDestination:docsDir];
              } else {
                  NSLog(@"failed to move: %@", [error userInfo]);
              }
              */
          }
    }];
    [downloadTask resume];
}
```

Any working example of extracting the file using web services.

**Comment by jhudsonWA** [comment]
What's not working about this one? Give us some details on what you are seeing.

**Comment by bishalg** [comment]
@jhudsonWA : 
1. `NSURLSessionDownloadTask's` completion task with `NSURL *location` returns the following location - 
`file:///Users/bishalghimire/Library/Developer/CoreSimulator/Devices/FA54F541-2559-45AC-9380-7C4842C071EA/data/Containers/Data/Application/07E83F1B-720C-478E-9D77-961B34D6155C/tmp/CFNetworkDownload_Jo1hoi.tmp`

Q1. The downloaded file is actually a zip file so shouldn't the file extension be .zip ?
Maybe its "tmp" until we move the file to `NSDocumentDirectory` ?

Q2. Can we extract the downloaded file on "/tmp" folder or should we proceed to move to document folder before we can extract ? 

Q3. Will the extract work for zip file with different file extension ? ie the file is correct zip formate with just file extension of other extension.

If we have any example of using zip extraction which is downloaded from web service would be helpful.

**Comment by bishalg** [comment]
For following code - 

 ```
    NSString *docsDir = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
    NSURL *docsDirURL = [NSURL fileURLWithPath:[docsDir stringByAppendingPathComponent:@"out.zip"]];
    [SSZipArchive unzipFileAtPath:docsDirURL.absoluteString toDestination:docsDir];
```

Where, 
docsDirURL.absoluteString
`file:///Users/bishalghimire/Library/Developer/CoreSimulator/Devices/FA54F541-2559-45AC-9380-7C4842C071EA/data/Containers/Data/Application/3F7C7E7B-455D-4AF7-A045-477DC7BC2DAD/Documents/out.zip`

docsDir
`/Users/bishalghimire/Library/Developer/CoreSimulator/Devices/FA54F541-2559-45AC-9380-7C4842C071EA/data/Containers/Data/Application/3F7C7E7B-455D-4AF7-A045-477DC7BC2DAD/Documents`

Getting the error - 
`Error Domain=SSZipArchiveErrorDomain Code=-1 "failed to open zip file" UserInfo={NSLocalizedDescription=failed to open zip file}`

**Comment by bishalg** [comment]
Fixed the issue 
Path should NOT contain - `file:///`
So the way to fix is use NSURL's `path` property and not the `absoluteString`.

Also we need to move the file downloaded from temp folder to documents folder.
