### ISSUE TITLE
Support unzipping files > 4GB compressed with Archive Utility

### ISSUE THREAD

**Issue by Coeur** [ZipArchive/ZipArchive#417]
I've made some tests with a big file (Xcode9, 5.44 GB). Here are my results:

          decompressor ->   Archive Util. | UnZip 6.00 | Keka | The Unarchiver | ZipArchive
    compressor
    Archive Utility 10.10   ✅                   ❌       ❌       ❌               ❌
    Zip 3.0                 ✅                   ✅       ✅       ✅               ✅
    ZipArchive 2.1.1        ✅                   ✅       ✅       ✅               ✅

So ZipArchive seems to correctly support zipping and unzipping files larger than 4 GB when they are in a correct format (ZIP64). But it seems Archive Utility will compress large files in an undocumented format that only itself can uncompress.

[edit, thanks @palmin]

Results for a big file (5.37 GB) made of zero, so archive is only 5.2 MB:

          decompressor ->   Archive Util. | UnZip 6.00 | Keka | The Unarchiver | ZipArchive
    compressor
    Archive Utility 10.10   ✅                   ✅       ❌       ✅               ✅

So issue could potentially only affect compressed archives larger than 4 GB.

**Comment by jhudsonWA** [comment]
I'm not sure we want to try to figure out an undocumented format? What's hour thoughts on it?

**Comment by Coeur** [comment]
I know... but it's the default archiver on mac.
To be honest, I have the feeling that above 4 GB with Archive Utility, it is the so called .XIP format that is actually used...

**Comment by palmin** [comment]
I have made some quick tests archiving a 7GB iso file into a 6GB archive with the Finder on macOS 10.12.6.

The resulting file starts with "PK" as expected for PKZIP files and if this was a XIP file I think it would start with "xar!" as XIP derives from xar.

**Comment by palmin** [comment]
I had a old Windows VM but it was so awful and couldn't fit the entire file. Tried to open it from a file-share but when this is not working I cannot know if this is just Windows networking failing on very large files or WinZip and 7Zip failing.

I have tried to run `zipinfo -v` on the file and I a file that looks too small but has some kind of unknown extension:
````Central directory entry #1:
---------------------------

  14393.0.161119-1705.RS1_REFRESH_SERVER_EVAL_X64FRE_EN-US.ISO

  offset of local header from start of archive:   0
                                                  (0000000000000000h) bytes
  file system or operating system of origin:      Unix
  version of encoding software:                   2.1
  minimum file system compatibility required:     MS-DOS, OS/2 or NT FAT
  minimum software version required to extract:   2.0
  compression method:                             deflated
  compression sub-type (deflation):               normal
  file security status:                           not encrypted
  extended local header:                          yes
  file last modified on (DOS date/time):          2017 Aug 13 20:13:40
  file last modified on (UT extra field modtime): 2017 Aug 13 20:13:40 local
  file last modified on (UT extra field modtime): 2017 Aug 13 18:13:40 UTC
  32-bit CRC value (hex):                         e1710aba
  compressed size:                                2461466198 bytes
  uncompressed size:                              2677254144 bytes
  length of filename:                             60 characters
  length of extra field:                          12 bytes
  length of file comment:                         0 characters
  disk number on which file begins:               disk 1
  apparent file type:                             binary
  Unix file attributes (100777 octal):            -rwxrwxrwx
  MS-DOS file attributes (00 hex):                none

  The central-directory extra field contains:
  - A subfield with ID 0x5855 (old Info-ZIP Unix/OS2/NT) and 8 data bytes:
    27 5e 05 5a d4 96 90 59.

  There is no file comment.

**Comment by palmin** [comment]
To make testing a little easier I made a 5GB file of all zeros with
    dd if=/dev/zero of=zero.dat  bs=1048576  count=5120
and used Finder to archive this.

I am able to decompress this file using unzip on a Debian 8 (Debbie) machine, such that it does not seem to be a mac-only method of extending to above 4GB files. 

Is this test even valid when the resulting zip-file is below 4GB? 
It ends up a 5MB zip because the all zeros compress nicely.

**Comment by Coeur** [comment]
results for zero.dat.zip:
```
      decompressor ->   Archive Util. | UnZip 6.00 | Keka | The Unarchiver | ZipArchive
compressor
Archive Utility 10.10   ✅                   ✅      ❌       ✅               ✅
```
So no, it's not a valid test.

**Comment by aonez** [comment]
Just FYI, Keka uses p7zip for ZIP files (at least until 1.1.5 version). Here is a thread with information about this whole 4GB files issue: https://sourceforge.net/p/sevenzip/bugs/2038

**Comment by jhudsonWA** [comment]
I'm going to close this out as we do have some support for large archives after future PRs
