### ISSUE TITLE
if the uzip fails, will have an impact on the original file?

### ISSUE THREAD

**Issue by LeeBigRay** [ZipArchive/ZipArchive#419]
When i choose to overwrite the same file in the directory, if the uzip fails, will have an impact on the original file? thank you

**Comment by Coeur** [comment]
failing or succeeding, unzipping shall not have any impact on the original archive... unless maybe if one of the files inside the archive had the same name as the archive itself. That edge case would be interesting to test and document.

**Comment by jhudsonWA** [comment]
Agreed. I think @Coeur answered your question. I'm going to close the issue.
