### ISSUE TITLE
Classes Not working in simulator.

### ISSUE THREAD

**Issue by Prabhat-Emorphis** [ZipArchive/ZipArchive#422]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Coeur** [comment]
* Did you clean Derived Data correctly before rebuilding?
* Did you integrate with Carthage or CocoaPods?
* What is your include/import line?
* Can you share a project with the issue?

**Comment by Prabhat-Emorphis** [comment]
Now getting error with physical device, when try to use Classes:

Undefined symbols for architecture arm64:
  "_tm_to_dosdate", referenced from:
      +[SSZipArchive zipInfo:setDate:] in SSZipArchive.o
  "_zipOpenNewFileInZip5", referenced from:
      __zipOpenEntry in SSZipArchive.o
  "_zipOpen", referenced from:
      -[SSZipArchive open] in SSZipArchive.o
     (maybe you meant: __zipOpenEntry)
  "_unzReadCurrentFile", referenced from:
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpen", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzGoToFirstFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpenCurrentFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_zipWriteInFileInZip", referenced from:
      -[SSZipArchive writeFolderAtPath:withFolderName:withPassword:] in SSZipArchive.o
      -[SSZipArchive writeFileAtPath:withFileName:compressionLevel:password:AES:] in SSZipArchive.o
      -[SSZipArchive writeData:filename:compressionLevel:password:AES:] in SSZipArchive.o
  "_unzGetCurrentFileInfo", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_zipClose", referenced from:
      -[SSZipArchive close] in SSZipArchive.o
  "_zipCloseFileInZip", referenced from:
      -[SSZipArchive writeFolderAtPath:withFolderName:withPassword:] in SSZipArchive.o
      -[SSZipArchive writeFileAtPath:withFileName:compressionLevel:password:AES:] in SSZipArchive.o
      -[SSZipArchive writeData:filename:compressionLevel:password:AES:] in SSZipArchive.o
  "_unzGetGlobalInfo", referenced from:
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzCloseCurrentFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzClose", referenced from:
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpenCurrentFilePassword", referenced from:
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzGoToNextFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


This is my sample code, let me know where I am wrong:
[ExtractHTMLFile.zip](https://github.com/ZipArchive/ZipArchive/files/1466548/ExtractHTMLFile.zip)

**Comment by Prabhat-Emorphis** [comment]
Problem Resolved, Need to manually assign Target to every ".c" file.

![screen shot 2017-11-13 at 4 54 02 pm](https://user-images.githubusercontent.com/23358685/32723421-68407b8c-c893-11e7-94d1-d5521743b2a8.png)
