### ISSUE TITLE
Zipping symbolic links and alias

### ISSUE THREAD

**Issue by webjib** [ZipArchive/ZipArchive#423]
I'm unable to correctly zip symbolic links and aliases. I've tried to play with zipInfo->external_fa by adding 0120000 >> 16 (but I think it's more complicated. They are not recognised as links when unzipping the archive, but as empty file with 0 byte.

Is someone able to add symbolic links and aliases in archive ?
 
EDIT : ok I've managed to implement support for zipping UNIX symbolic links.
We need to read content of symlink using C command "readlink" and setting attributes to tell it's a symlink (S_IFLNK)

**Comment by Coeur** [comment]
would you make a pull request?

**Comment by webjib** [comment]
I thought it was a bug, but in fact this is only because not supported. I'll make pull request, you can close this issue.

**Comment by webjib** [comment]
Hello Antoine
Je suppose que tu parles français, ç tombe bien moi aussi.
Est il possible d’échanger au sujet d’un pull request ? Suis nouveau sur GitHub et je pense avoir besoin d’aide et de discuter avant de la nécessité de mon code.

Jean-Baptiste

**Comment by palmin** [comment]
I also needed this and made a pull request.

https://github.com/ZipArchive/ZipArchive/pull/424

**Comment by Coeur** [comment]
Thanks @palmin, I'll look at it this weekend.

@webjib , sorry, I exclusively give support in English, otherwise I would be mess of duplicate issues and questions in Chinese, etc.

**Comment by jhudsonWA** [comment]
PR #560 merged into master. This should fix this bug if you use the right method signature (keepSymlinks:(BOOL)keeplinks)
