### ISSUE TITLE
Can we decompress 7zip?

### ISSUE THREAD

**Issue by Jethuang** [ZipArchive/ZipArchive#425]
You can decompress. 7zip?

**Comment by Coeur** [comment]
No, we can't, it's a different format.

**Comment by jhudsonWA** [comment]
I'm closing this one. I really don't want to tackle this. Our goal is to be good at the zip format, nothing more.

**Comment by Coeur** [comment]
For record, here are similarly named formats that we do **not** support:
* 7-Zip
* gzip
* bzip2
* rzip
* xip
