### ISSUE TITLE
unable to find specifications

### ISSUE THREAD

**Issue by sonianurag022** [ZipArchive/ZipArchive#426]
I tried to setup a new workspace for project in different  user account in mac with a project running successfully on other user.

now when i tried to install pods it give me error
"[!] Unable to find a specification for `WPZipArchive"

i also tried with     "pod 'WPZipArchive'" and "pod 'WPZipArchive' '~>0.1.0'"
but result is same unable to find specification, i am new to the pods please help me with this

**Comment by Coeur** [comment]
Hi, WPZipArchive is an old unmaintained fork that you can find at https://github.com/WPMedia/WPZipArchive

Please use `pod 'SSZipArchive'` as documented in the Readme https://github.com/ZipArchive/ZipArchive

**Comment by jhudsonWA** [comment]
@sonianurag022 Does this answer your question? I'm going to close this issue and can reopen if you still have trouble.
