### ISSUE TITLE
conflict to opencv

### ISSUE THREAD

**Issue by topws** [ZipArchive/ZipArchive#429]
When my project contains both OpenCV and SSZipArchive, the zip package with SSZipArchive with password compression can not be decompressed with the original password

**Comment by Coeur** [comment]
Did you try without AES?
By default, password encryption is with AES, and it is not supported by some tools.

Also, there are so many variants of OpenCV, so please share your **Podfile.lock** to determine which one you are using: https://cocoapods.org/?q=OpenCV

Also, it's unclear to me how do you uncompress with OpenCV: https://docs.opencv.org/2.4/modules/refman.html
So please share an MVCE project/code where OpenCV is involved.

**Comment by topws** [comment]
[SSZipArchive createZipFileAtPath:zipPath
				  withContentsOfDirectory:filePath
					  keepParentDirectory:NO
						 compressionLevel:Z_DEFAULT_COMPRESSION
								 password:SSZipArchivePassword
									  AES:NO
						  progressHandler:^(NSUInteger entryNumber, NSUInteger total) {

						  }]

**Comment by topws** [comment]
My OpenCV version is pod 'OpenCV', '~> 3.2.0'，when i delete opencv,everything is ok.
I guess it may be a problem at compile time.Forgive my English is not good.

**Comment by Coeur** [comment]
I did not reproduce your issue at all.
Tested on iOS simulator with Xcode 9.1 on a public branch/commit with the specified informations from this issue (pod, compressionLevel, AES, objective-c), so you can try it yourself:
branch: https://github.com/ZipArchive/ZipArchive/tree/opencv
commit: https://github.com/ZipArchive/ZipArchive/commit/f18b0e902f9b1e598081203e82944ab7241791f0

**Comment by topws** [comment]
sorry,forgot to tell you,I am working on mac osx.this is a demo:[](https://github.com/topws/TestOpencvAndSSZipArchive)

**Comment by topws** [comment]
https://github.com/topws/TestOpencvAndSSZipArchive

**Comment by Coeur** [comment]
@topws sorry for the wait.

I tried your project with Xcode 9.4, changing the DEVELOPMENT_TEAM to mine, and replacing

    @"/Users/avazuholding/Desktop/222"

with

    @"/Users/coeur/Desktop/222"

And my output was successful (with no warning/error at compilation):
>TestOpencvAndSSZip[12553:57872834] 1

Then I tried to decompress it:

    BOOL flag2 = [SSZipArchive unzipFileAtPath:zipPath
                                 toDestination:filePath
                                     overwrite:YES
                                      password:@"123"
                                         error:nil];
    NSLog(@"%d",flag2);

and it was successful:
>TestOpencvAndSSZip[14709:57912924] 1

So there is no apparent conflict with opencv. I'll close the issue for now.
