### ISSUE TITLE
Question about Manual installation

### ISSUE THREAD

**Issue by andre0707** [ZipArchive/ZipArchive#430]
I'm very new to GitHub.

I downloaded the complete project and unzipped it.
I then added the SSZipArchive folder (which includes the minizip folder) to my Xcode project. 
In Xcode I selected the following for the adding files process: 
<img width="591" alt="bildschirmfoto 2017-11-28 um 17 51 15" src="https://user-images.githubusercontent.com/34069417/33332535-ce0cbd0e-d464-11e7-89ee-db924fbbc6c6.png">
It looks like this then:
<img width="221" alt="bildschirmfoto 2017-11-28 um 17 52 36" src="https://user-images.githubusercontent.com/34069417/33332619-037efa42-d465-11e7-9db8-3d297e735d68.png">
I also included the libz library in my target under "Build Phases" and "Link Binary With Libraries". See:
<img width="781" alt="bildschirmfoto 2017-11-28 um 17 53 39" src="https://user-images.githubusercontent.com/34069417/33332720-48122724-d465-11e7-896a-7eb3ca7bf542.png">

When I now try to use SSZipArchive somewhere, it's not working. I get the following:
<img width="778" alt="bildschirmfoto 2017-11-28 um 17 56 16" src="https://user-images.githubusercontent.com/34069417/33332893-b99a9408-d465-11e7-8a48-0ee392c531c0.png">

What am I doing wrong?

**Comment by jhudsonWA** [comment]
Does it build if you don't use SSZipArchive? Just with the source and linked library included?

**Comment by jhudsonWA** [comment]
If possible we really recommend using cocoapods for installation. It greatly simplifies working with and updating the library.

**Comment by andre0707** [comment]
Yes, it builds if I don't use SSZipArchive. It's included the way the above pictures show

**Comment by andre0707** [comment]
worked with cocoapods. Thank you!

**Comment by jhudsonWA** [comment]
Great. Starting to wonder if we just want to drop support for manual instructions. To fidgety.
