### ISSUE TITLE
How to control the memory of iphone when unzip the file? #324

### ISSUE THREAD

**Issue by wangkangwei** [ZipArchive/ZipArchive#432]
thanks! I still have issues with this.

 - The zip contains
    
![62ac1199-a727-4207-9724-8d50da610306](https://user-images.githubusercontent.com/20127920/34035001-8c45b9a2-e1bb-11e7-8793-0193a5eb168e.png)
 something like the image shows. The three directories(resources-iphone/iphonehd/ipadhd) contains a lot of images only,like this
![0b14fc36-b9c1-48d0-9f33-6b2c58070f4d](https://user-images.githubusercontent.com/20127920/34035045-ad5efe00-e1bb-11e7-933b-c4170cb7bc0a.png)

 -   The problem almost happens in ipad mini1 and so on. iphone seems have no problem.
    so in ipad mini1 when unzip it my app crashed. I use instrument tool to monitor the memory useage, then the memory get jump useage and shut down.
    I used this method:

[SSZipArchive unzipFileAtPath:[zipFileURL path] toDestination:path];

Looking forward to reply. ^-^

**Comment by wangkangwei** [comment]
#324

**Comment by jhudsonWA** [comment]
Let's close this one and track on #324
