### ISSUE TITLE
Rename the file which is unzip.

### ISSUE THREAD

**Issue by ambujshukla-cdn** [ZipArchive/ZipArchive#433]
Hi,
   How can I rename the files which is unzipped with the help of the ZipArchive. Is there any way to achieve this.

**Comment by jhudsonWA** [comment]
So after the files are unziped you need them renamed? 

Just do that using the iOS FileManager sdk. After the files are unzipped they area just normal files, so you can rename them, delete them, etc.

https://developer.apple.com/documentation/foundation/filemanager

**Comment by ambujshukla-cdn** [comment]
@jhudsonWA , Thanks for the help:)

**Comment by jhudsonWA** [comment]
You're welcome!
