### ISSUE TITLE
Build Error about 'UNZ_BADPASSWORD'

### ISSUE THREAD

**Issue by LiuYibin** [ZipArchive/ZipArchive#434]
Build error: Use of undeclared identifier 'UNZ_BADPASSWORD' in SSZipArchive.m

**Comment by jhudsonWA** [comment]
How are you using the library? Manual, Cocoapods, Carthage?

It is highly recommended you use Cocoapods or Carthage for the easiest setup.

**Comment by LiuYibin** [comment]
I‘m using cocoapods. And I imported your library via react-native-code-push which is dependent on your lib.

**Comment by jhudsonWA** [comment]
Do you know what version it is pulling in?

**Comment by LiuYibin** [comment]
Sorry for having ignored this. It seems that  it's not your issue. Because every thing is OK if I  import your lib in a  separated project. 
Your lib is also imported by another RN package, if I don't import the RN package 'react-native-code-push' and your lib is only imported by another RN package, there is no error.
