### ISSUE TITLE
ZipArchive go to iOS App Store?

### ISSUE THREAD

**Issue by heiligabendbaer49** [ZipArchive/ZipArchive#436]
Hello developer, 

can you release a iOS version to the App Store? 
Here a new news, is this good?
https://developer.apple.com/support/membership-fee-waiver/

Which app in App Store use ZipArchive library?

**Comment by jhudsonWA** [comment]
We are a developer library that has bene used in 10s of thousands of apps. Many of which are in the app store. We are not in the business of making our own dedicated app so no need to release something to the app store.

**Comment by heiligabendbaer49** [comment]
@jhudsonWA 
which app in app store has this functions? compression level, create zip, create protected zip

**Comment by jhudsonWA** [comment]
Not sure of any specific app. Lots of apps use our library simply to decompress content downloaded from the internet and more. I'm sure there are general purpose zipping apps.

**Comment by heiligabendbaer49** [comment]
@jhudsonWA @Coeur 
I cannot find so a app with this functions with your library.

Therefore is it better you make a app. I am very sure many consumers like this!

**Comment by jhudsonWA** [comment]
That is not the purpose of this library. I'm going to lock this conversation now.
