### ISSUE TITLE
Crash in ZipArchive

### ISSUE THREAD

**Issue by Kmohamed** [ZipArchive/ZipArchive#437]
NSInvalidArgumentException: *** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]

0  CoreFoundation          ___exceptionPreprocess
1  libobjc.A.dylib         _objc_exception_throw
2  CoreFoundation          __CFThrowFormattedException
3  CoreFoundation          -[__NSPlaceholderArray initWithObjects:count:]
4  CoreFoundation          +[NSArray arrayWithObjects:count:]
5  CoreFoundation          -[NSDictionary allValues]
6  ZipArchive            derive_key
7  ZipArchive            derive_key
8  ZipArchive            derive_key
9  Foundation              ___NSOQSchedule_f
10 libdispatch.dylib       __dispatch_client_callout
11 libdispatch.dylib       __dispatch_continuation_pop$VARIANT$mp
12 libdispatch.dylib       __dispatch_async_redirect_invoke$VARIANT$mp
13 libdispatch.dylib       __dispatch_root_queue_drain
14 libdispatch.dylib       __dispatch_worker_thread3
15 libsystem_pthread.dylib __pthread_wqthread
16 libsystem_pthread.dylib _start_wqthread

**Comment by Coeur** [comment]
Come on...
https://github.com/Instabug/Instabug-iOS/search?utf8=%E2%9C%93&q=ziparchive&type=
There is no mention of ZipArchive in your source code, then you edit your crashlog to change "InstabugCore" to "ZipArchive"?

Don't expect to get any support like that, especially with a log that basically only says:
"hey, there is a crash on `ZipArchive derive_key`"

You're missing:
* honesty in your report
* ZipArchive version
* platform and version (iOS, macos)
* circumstances of the issue
* etc.

**Comment by Kmohamed** [comment]
Hey!!!
We are using ZipArchive inside Instabug so it completely make sense to be inside InstabugCore binary.
And this due to prefix ZipArchive to allow Instabug users to use your code without conflicts

**Comment by keith** [comment]
Also note the repo doesn’t have references to ZipArchive since there’s no code there, just a precompiled framework.

**Comment by HeshamMegid** [comment]
Just to clear up the air here, Instabug is a closed source framework as @keith mentioned, so you wouldn’t find any references to ZipArchive in our public repo.

ZipArchive is used inside our InstabugCore framework, we just swapped the framework names in the stack trace to make it more obvious where ZipArchive is being used. Sorry, we should have pointed that out.

PS: You might want to consider adding an [issue template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/) to let people know the kind of information you expect them to add when creating an issue.
