### ISSUE TITLE
ASAN: Should use `memmove` not `memcpy`

### ISSUE THREAD

**Issue by fpillet** [ZipArchive/ZipArchive#438]
Address Sanitizer chokes on this line: 

https://github.com/ZipArchive/ZipArchive/blob/ef845f9e681d2240941f5df66fbd1a15b9c06d88/SSZipArchive/minizip/unzip.c#L1347

Because both buffers overwrite and the code should be using `memmove` instead

**Comment by jhudsonWA** [comment]
I'd recommend proposing this change to the upstream library:

https://github.com/nmoinvaz/minizip

**Comment by alexrestrepo** [comment]
Fwiw this has been fixed upstream `https://github.com/nmoinvaz/minizip/issues/276`

**Comment by littlebobert** [comment]
Sorry, any chance that fix could make it into the next release somehow?

**Comment by Coeur** [comment]
@littlebobert 
@alexrestrepo 
Thank you for notifying us about that. I'll review the changes made on upstream library and integrate them for next release: https://github.com/Coeur/minizip/compare/master...nmoinvaz:1.2

I'm re-opening this ticket and assigning it to myself.

**Comment by jhudsonWA** [comment]
Thanks @Coeur

**Comment by Coeur** [comment]
Fixed on master with 6866ad618c73d9b3b73ee0c922a8ce9e3493a061
