### ISSUE TITLE
compile failed 

### ISSUE THREAD

**Issue by BruceZhu0821** [ZipArchive/ZipArchive#439]
error info: ld: symbol(s) not found for architecture arm64
Can you help me? great thanks!

**Comment by BruceZhu0821** [comment]
Objective C version

**Comment by jhudsonWA** [comment]
This is similar to the issue here, but for arm64 vs v7: https://github.com/ZipArchive/ZipArchive/issues/407

Please review that issue and let us know if you still have an issue.

**Comment by jhudsonWA** [comment]
And this one: https://github.com/ZipArchive/ZipArchive/issues/298

**Comment by jhudsonWA** [comment]
Closing due to no response
