### ISSUE TITLE
Failed to unarchive a ZIP file with no error

### ISSUE THREAD

**Issue by eytanschulman** [ZipArchive/ZipArchive#442]
Hello!

SSZipArchive is failing to unarchive this ZIP file, and is returning a NIL error. From my short investigation, I believe the issue has something to do with fopen() not functioning properly.

This is the ZIP file I am trying to unarchive [https://docs-assets.developer.apple.com/published/a986081324/RecognizingImagesInAnARExperience.zip](https://docs-assets.developer.apple.com/published/a986081324/RecognizingImagesInAnARExperience.zip)

The code I am using to Unarchive is below:

```
SSZipArchive.unzipFile(atPath: fromLocation.path, toDestination: toLocation.path, progressHandler: {
                    (entry, zipInfo, readByte, totalByte) -> Void in
                    
                }, completionHandler: { (path, success, error) -> Void in
                    print("There was an error unarchiving: \(String(describing: error))")
                    completion(success)
                })
```

Any help would be greatly appreciated, thank you.

**Comment by jhudsonWA** [comment]
Can you attach a quick test project that shows the error?

**Comment by eytanschulman** [comment]
Sorry about that, I discovered that I was one version behind of SSZipArchive 2.1.1 (was 2.1.0). Updating fixed the issue.
