### ISSUE TITLE
Static library support - Cocoapods 1.5.0

### ISSUE THREAD

**Issue by taglia3** [ZipArchive/ZipArchive#452]
It doesn't works with cocoa pods 1.5.0 without use_frameworks option.

<img width="1045" alt="screen shot 2018-05-04 at 00 47 40" src="https://user-images.githubusercontent.com/4321291/39606251-c9452f9a-4f34-11e8-8efc-8f629ddf7a4d.png">

**Comment by Coeur** [comment]
Oh, reading the CocoaPods blog, I found the answer: http://blog.cocoapods.org/CocoaPods-1.5.0/

>Interop with Objective-C should _just_ work. However, if your Swift pod depends on an Objective-C, pod you will need to enable "modular headers" (see below) for that Objective-C pod.

>[...]

>As a pod author, you can add `'DEFINES_MODULE' => 'YES'` to your `pod_target_xcconfig`. Alternatively, in your Podfile you can add `use_modular_headers!` to enable the stricter search paths and module map generation for all of your pods, or you can add `:modular_headers => true` to a single `pod` declaration to enable for only that pod.

So, I tried it, and with this pod declaration in Podfile it works:

    pod 'SSZipArchive', :modular_headers => true

Now, I guess I should add `'DEFINES_MODULE' => 'YES'` to our ZipArchive podspec to solve it automatically for everyone.
