### ISSUE TITLE
Undefined symbols for architecture i386:

### ISSUE THREAD

**Issue by coder4567** [ZipArchive/ZipArchive#458]
I am trying the test example (ObjectiveCExample) you have provided but I'm getting on build the following errors
although I have added mini zip folder inside the project and zlib library as instructed.
Would you kindly advise. 

Undefined symbols for architecture i386:
  "_tm_to_dosdate", referenced from:
      +[SSZipArchive zipInfo:setDate:] in SSZipArchive.o
  "_zipOpenNewFileInZip5", referenced from:
      __zipOpenEntry in SSZipArchive.o
  "_zipOpen", referenced from:
      -[SSZipArchive open] in SSZipArchive.o
     (maybe you meant: __zipOpenEntry)
  "_unzReadCurrentFile", referenced from:
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpen", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzGoToFirstFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_zipClose", referenced from:
      -[SSZipArchive close] in SSZipArchive.o
  "_zipCloseFileInZip", referenced from:
      -[SSZipArchive writeFolderAtPath:withFolderName:withPassword:] in SSZipArchive.o
      -[SSZipArchive writeFileAtPath:withFileName:compressionLevel:password:AES:] in SSZipArchive.o
      -[SSZipArchive writeData:filename:compressionLevel:password:AES:] in SSZipArchive.o
  "_unzGetGlobalInfo", referenced from:
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzClose", referenced from:
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzCloseCurrentFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpenCurrentFilePassword", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzOpenCurrentFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_zipWriteInFileInZip", referenced from:
      -[SSZipArchive writeFolderAtPath:withFolderName:withPassword:] in SSZipArchive.o
      -[SSZipArchive writeFileAtPath:withFileName:compressionLevel:password:AES:] in SSZipArchive.o
      -[SSZipArchive writeData:filename:compressionLevel:password:AES:] in SSZipArchive.o
  "_unzGetCurrentFileInfo", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
  "_unzGoToNextFile", referenced from:
      +[SSZipArchive isFilePasswordProtectedAtPath:] in SSZipArchive.o
      +[SSZipArchive isPasswordValidForArchiveAtPath:password:error:] in SSZipArchive.o
      +[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] in SSZipArchive.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jhudsonWA** [comment]
The example project should work without any modifications. What version of Xcode are you working in?

**Comment by meccatol1** [comment]
That error occurred in some environment, example cocoapods 1.5.3 version and SSZipArchive old version. (in my case 1.2)
But, Not Problem with cocoapods 1.5.3 version and SSZipArchive 2.1.3 version. Thanks. :D

**Comment by Coeur** [comment]
Glad it works with latest version of ZipArchive.
