### ISSUE TITLE
Special characters in file Names

### ISSUE THREAD

**Issue by MarkBirch3D** [ZipArchive/ZipArchive#461]
Hello! My issue may be related to https://github.com/ZipArchive/ZipArchive/issues/449, but i would still like some pointers, or at least an update on the status of the issue. 

I am having problems when zipping a file with special characters in the file name like ß or é. When i zip them from ZipArchive and open them on a Windows OS, the characters in question are all messed up. At first I thought it was because of the OS, but if i zip the same files from the mac, they come out fine so I guess it's not it!

I also tried going back to the 2.1.1 version as it seemed to be suggested in the post above, but I guess the OP's problem was more with UNzipping files, and not zipping them, because it didn't help.

Any pointers or news about this?

**Comment by MarkBirch3D** [comment]
bump

**Comment by willson-chen** [comment]
also related to Issue #545.

**Comment by willson-chen** [comment]
@MarkBirch3D This issue has been fixed by PR #564, and will be released in next version.
