### ISSUE TITLE
UNZip failed in myself asynchronous queue

### ISSUE THREAD

**Issue by YanPengImp** [ZipArchive/ZipArchive#463]
i had download some tasks in asynchronous queue,these tasks`s completeBlock on main thread,then create an asynchronous queue to execute unzip work,but some work will be failed,some be successed.if i create a synchronous queue to execute unzip work,it will not be failed,but it will become stuck main thread.so how can i solve this problem?

**Comment by jhudsonWA** [comment]
Upload a sample project. Lots of folks use this library on asynchronous queues with no issue.

**Comment by YanPengImp** [comment]
Sorry,it`s my mistake,when i acquire the tmp file path,i had added another "/"，so it open file will be falied.Anyway, thank you!
