### ISSUE TITLE
Cannot build in Xcode 10 for Release configuration

### ISSUE THREAD

**Issue by nick3389** [ZipArchive/ZipArchive#469]
The following error comes up when building my project for release configuration:

no such module 'SSZipArchive' (where I import the library)

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal i386
	CompileSwiftSources normal i386 com.apple.xcode.tools.swift.compiler

**Comment by Coeur** [comment]
I'll test try to build the [test project](https://github.com/ZipArchive/ZipArchive/tree/master/SwiftExample) in release configuration within next hours.

**Comment by Coeur** [comment]
I successfully built in Xcode 10 for release configuration:

* Xcode 10.0 beta 4
* The above mentioned test project that is available in our repository
* I added a Team for signing
* I selected "Generic iOS Device"
* I choosed "Archive" (that will build in release configuration)
<img width="715" alt="screen shot 2018-08-20 at 10 55 35" src="https://user-images.githubusercontent.com/839992/44318283-b3cddd00-a467-11e8-9c83-b1cceb57f429.png">

---
So please provide more details on how to reproduce your issue, and we'll re-open it. :)
