### ISSUE TITLE
Carthage WatchOS v2.1.4 doesn't include arm64_32 (Series 4) Architecture

### ISSUE THREAD

**Issue by charlymr** [ZipArchive/ZipArchive#474]
Hi everyone,

I know it's just out, but the current release version of the framework doesn't include the amr64_32 slide. 
https://github.com/ZipArchive/ZipArchive/releases/tag/v2.1.4

```bash
$ cd watchOS 
$ lipo -info ZipArchive 
Architectures in the fat file: ZipArchive are: i386 armv7k 
```

I checked and it is building with Xcode 10. So it's just a matter of releasing it.
Thanks for the great work.

Denis

**Comment by charlymr** [comment]
@Coeur thanks :)

Yes I know I can build it, it's just I am using it in a project where I myself deliver a Carthage framework too, so it's downloading the zipped framework, rather than re-building. 

Will check if I can attach you framework directly. Thanks

**Comment by Coeur** [comment]
Done with https://github.com/ZipArchive/ZipArchive/releases/tag/v2.1.5
