### ISSUE TITLE
miniZip version choose question regarding performance

### ISSUE THREAD

**Issue by yuman07** [ZipArchive/ZipArchive#479]
as the license say, 'SSZipArchive is protected under the MIT license and our slightly modified version of Minizip 1.2 is licensed under the Zlib license.'

but I notice that miniZip's master version is update to 2.6.x，and the 1.2 branch is seems like a LTS branch.

Will there be performance gains if you switch to the new version?
If so, is the cost of switching high?

**Comment by yuman07** [comment]
I raised this question
because, I noticed that the operation of unzip was very slow on the iphone6.
a 1.5mb zip package，will cost 2.2s for unzip
so, I hope to speed up the decompression

**Comment by yuman07** [comment]
> Have you compared decompression performance to the Apple Compression framework? https://developer.apple.com/documentation/compression/compression_algorithm?language=objc Hal
> […](#)
> On Oct 16, 2018, at 1:14 AM, yuman ***@***.***> wrote: I raised this question because, I noticed that the operation of unzip was very slow on the iphone6. a 1.5mb zip package，will cost 2.2s for unzip so, I hope to speed up the decompression — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Sorry, I didn't find the sample code for Apple's official decompression algorithm.

**Comment by halmueller** [comment]
It’s just another framework. Drop it into your project (see the doc link I included in my last message) and try it. No sample code needed. 

Hal

**Comment by yuman07** [comment]
> It’s just another framework. Drop it into your project (see the doc link I included in my last message) and try it. No sample code needed. Hal
> […](#)

from my test, apple's framework is faster. But, apple's API is hard to use. 
For example，no password, can not decompression signle file ,too few error messages ...
SSZipArchive is more functional than I need, but it has poor performance on poor performance phone(such as iPhone6)
so, I would like to ask, there be performance gains if you switch miniZip to the new version?

**Comment by halmueller** [comment]
That was my experience too, and the reason I chose ZipArchive. I didn’t ever bump up against performance limits though.

**Comment by yuman07** [comment]
> That was my experience too, and the reason I chose ZipArchive. I didn’t ever bump up against performance limits though.
> […](#)

This is my sample.zip, it just 1.5mb.
I create a new empty only with SSZipArchive(v2.4.1). i test unzip it will cost 2.2s at first time.
[sample.zip](https://github.com/ZipArchive/ZipArchive/files/2486566/sample.zip)

**Comment by jhudsonWA** [comment]
Thanks for the ping Coeur. I'll take another look on it. It's a move we need to make. And I believe our concerns of moving earlier have been mitigated in the newer versions.

**Comment by Coeur** [comment]
Minizip 2.x is now merged on master and will be released as part of ZipArchive 2.2.0.
There is still a compatibility layer (mz_compat.*), which will be removed in a future major release.
