### ISSUE TITLE
Error "failed to open zip file"

### ISSUE THREAD

**Issue by chenliangloveyou** [ZipArchive/ZipArchive#484]
i have download a file from our server through AFNetworking.
file is here : https://github.com/chenliangloveyou/test/blob/master/11.zip 
but use ZipArchive unzip is faild .  i need help !!!

**Comment by chenliangloveyou** [comment]
i gress is my zip problem , but use other third library can unzip .

**Comment by Coeur** [comment]
`unzSearchCentralDir` is returning `UNZ_ERRNO`, which means that the Central directory of the zip file couldn't be located. I need to try with a newer version of [minizip](https://github.com/nmoinvaz/minizip/), to see if it's supported/fixed.

**Comment by nmoinvaz** [comment]
This is not a ZIP file, it is a Gzip file.

**Comment by Coeur** [comment]
Also an issue with the latest minizip:
```
$ ./minizip -x 11.zip 
Minizip 2.8.6 - https://github.com/nmoinvaz/minizip
---------------------------------------------------
-x 11.zip 
Archive 11.zip
Error -107 opening archive 11.zip
```

**Comment by Coeur** [comment]
@nmoinvaz oh lol, I didn't notice that. Well, in that case I'll close the issue. Thank you for watching.
