### ISSUE TITLE
Zipping does not preserve the directory 

### ISSUE THREAD

**Issue by tripledee** [ZipArchive/ZipArchive#486]
On Mojave, when I zip a (docx structured) directory with subdirectories and files, the structure is not preserved when the archive is created using `createZipFileAtPath: withFilesAtPaths:  `, and the resulting zip contains a mess. On iOS, the hierarchy is correctly preserved.

**Comment by Coeur** [comment]
I can't reproduce that issue at all with the example macos app from Master branch.
Please fork our project and alter our example macos app to demonstrate the issue.
