### ISSUE TITLE
Can't zip folder when there're some empty files there

### ISSUE THREAD

**Issue by lincyim** [ZipArchive/ZipArchive#487]
Can't zip folder when there're some empty files there. The zip method just keeps on running when it meets the file whose size is zero. When I filtered out all the empty files, everything works fine.

**Comment by Coeur** [comment]
I made an empty file:
```sh
cd ./Example/Sample Data
touch hello.txt
```

Then I ran the sample example app, and zipping and unzipping were working fine, with and without password.

Please fork the project and make a reproducible scenario with the example app.
