### ISSUE TITLE
License GNU General Public License (GPL) is in conflict with Apple App Store? Is ZipArchive allowed to go to Apple App Store?

### ISSUE THREAD

**Issue by krishkumar83** [ZipArchive/ZipArchive#489]
License GNU General Public License (GPL) is in conflict with Apple App Store? Is ZipArchive allowed to go to Apple App Store?

I find GNU GPL license in following pod file places
fileenc.h
fileenc.c
prng.c
prng.h

**Comment by jhudsonWA** [comment]
Yes, there are thousands of apps in the App Store that use this library. You are fine.
