### ISSUE TITLE
Is there a way to add new file or  folder to the zip ?

### ISSUE THREAD

**Issue by FlashTang** [ZipArchive/ZipArchive#492]
Hello 
Is there a way to add new file or  folder to the existing zip ? (instead of create a new one)
 
Thanks

**Comment by Coeur** [comment]
Apparently, our current ZipArchive implementation does not support that.
It calls `_zip = zipOpen(_path.fileSystemRepresentation, APPEND_STATUS_CREATE);` which will erase the existing content of any archive. We would need to pass `APPEND_STATUS_ADDINZIP` to support that feature.

**Comment by csc-EricWu** [comment]
I need this, too

**Comment by jhudsonWA** [comment]
Implementation of this request is now included in the master branch thanks to #598, it will be pushed out to all in the next release, which should be soon.
