### ISSUE TITLE
SSZipArchive.createZipFile(atPath: aTempZipPath, withContentsOfDirectory: folderURL.path, keepParentDirectory: false)

### ISSUE THREAD

**Issue by ReddyBasha** [ZipArchive/ZipArchive#494]
I am keeping "keepParentDirectory" as "false", so it will remove original directory/folder after creating zip. keepParentDirectory is meant to remove original folder after compression?. If yes it is not removing original folder. Sorry if my understanding is wrong about "keepParentDirectory" property.

**Comment by Coeur** [comment]
`keepParentDirectory` will affect unzipping:

* if you zipped the file with `true`, then unzipping will give you:
  * parent/file1
  * parent/file2

* you zipped the file with `false`, then unzipping will give you:
  * file1
  * file2

Zipping doesn't delete the original files.
