### ISSUE TITLE
crash on unzipFileAtPath:toDestination: when it calls NSFileManager.fileExistsAtPath:

### ISSUE THREAD

**Issue by MYAppKit** [ZipArchive/ZipArchive#498]
![image](https://user-images.githubusercontent.com/26372070/53776729-dcb04e00-3f31-11e9-96c7-b69ef8f8c9cc.png)

**Comment by jhudsonWA** [comment]
While a stack trace is nice it tells us nothing about your set up or what you were trying to do except for unzip a file with a password. 

Do you have a sample project that replicates the issue?

**Comment by Coeur** [comment]
You did not reply with an [MCVE](https://stackoverflow.com/help/mcve), so I'm closing the issue.
