### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by hackzilla** [ZipArchive/ZipArchive#499]
Get this project be used with swift's package manager?
Would it be possible to add a package.swift file?

**Comment by hackzilla** [comment]
Just realised this isn't possible, as it's an Obj-C project

**Comment by ralphpina** [comment]
I don't think it being an Obj-C project prevents it being published via Swift PM. Take a look at this [talk](https://developer.apple.com/videos/play/wwdc2019/410/) from WWDC 2019, starting at 16:42 they show how to add SPM support for a project with Obj-c code.

**Comment by Coeur** [comment]
@ralphpina OK: reopening for now, until I investigate.

**Comment by muizidn** [comment]
Is this resolve the issue? #523

**Comment by Garfeild** [comment]
Any progress on this?

**Comment by eytanschulman** [comment]
Two PRs open for this, I know it would help a lot of people get off of Cocoapods (Including myself), and move towards the future 😄 

https://github.com/ZipArchive/ZipArchive/pull/536
https://github.com/ZipArchive/ZipArchive/pull/523

@muizidn @Coeur Any chance these could get looked at?

**Comment by ryanholden8** [comment]
Also looking forward to using Swift Package manager, thanks for considering!

**Comment by willson-chen** [comment]
> Also looking forward to using Swift Package manager, thanks for considering!

Thanks for your feedback. But I am afraid the current maintainers are busy these days. It would be appreciated if some one could help to review #536 and #523.

**Comment by Coeur** [comment]
SPM added in #536. Thanks.
