### ISSUE TITLE
Problem import SSZipArchive 

### ISSUE THREAD

**Issue by pmd2245** [ZipArchive/ZipArchive#501]
Hi,

I am not able to import SSZipArchive. I am running under Xcode 10.
I tried via CocoaPods and the manual way without any success. 
Just to avoid misunderstanding for the manual method:
1/ I copied the folder "SSZipArchive" into my project directory.
2/ In Xcode, "add files to", I selected the SSZipArchive folder
3/ Then general -> Linked framework and librairies -> (+) -> libz.tbd 
*/ I checked Objective-C Automatic Reference Counting is On

I get the error: "No such module "SSZipArchive'"
I would appreciate if someone could help me.

Thanks

**Comment by DivineDominion** [comment]
Which Xcode, platform target, and language are you using?

**Comment by Coeur** [comment]
Please note that via CocoaPods 1.6.1+, there shouldn't be any issue with Xcode 10.2, as demonstrated by our Continuous Integration tests at https://travis-ci.org/ZipArchive/ZipArchive/branches

**Comment by pmd2245** [comment]
Many thanks for your support. 
I finally managed to install it trough CocoaPods. 
If it can help someone:
Xcode: 10.1
Platform: iPhone X (12.1.4)
Language: Objective-C
