### ISSUE TITLE
Travis Xcode 10 builds are failing when using the modern build system

### ISSUE THREAD

**Issue by Coeur** [ZipArchive/ZipArchive#502]
As seen by https://github.com/ZipArchive/ZipArchive/commit/9b70b5938ad64bd13bd313166947101b76c526a8, I had to set `-UseModernBuildSystem=NO` in order to build successfully with Xcode 10.x on Travis.

Is there be an alternative to avoid that and keep using modern build system?

**Comment by jhudsonWA** [comment]
Closing out as our builds on travis seem to be fine.
