### ISSUE TITLE
Fatal error: Class 'ZipArchive' not found in /var/www/html/phpword/PHPWord/Writer/Word2007.php on line 70

### ISSUE THREAD

**Issue by wyd6295578sk** [ZipArchive/ZipArchive#504]
您好，我这边报错
Fatal error: Class 'ZipArchive' not found in /var/www/html/XXX/wp-content/themes/XXX/phpword/PHPWord/Writer/Word2007.php on line 70

php版本是5.6
代码是在WordPress上跑的，是没有装这个插件的原因吗？还是怎么？求助~

**Comment by Coeur** [comment]
1. Please write in English
2. Please note that this github project is in Objective-C and only for iOS/macOS/tvOS/watchOS.
3. Please search internet for PHPWord, then pick the first result and figure out by yourself that it has nothing to do with us: https://github.com/PHPOffice/PHPWord/blob/master/src/PhpWord/Shared/ZipArchive.php
