### ISSUE TITLE
rejected when reviewing: "The app references non-public selectors"

### ISSUE THREAD

**Issue by cj1024** [ZipArchive/ZipArchive#505]
![image](https://user-images.githubusercontent.com/4304630/56713035-2adc1380-6763-11e9-913d-714e656c587d.png)

**Comment by Coeur** [comment]
We never use `_canPerformAction:` in our code, we use `respondsToSelector:`. You may be using some fork of our project, but not the code from here.

**Comment by mafaming** [comment]
我也遇到了这样的问题，请问这个是怎么解决的？
![image](https://user-images.githubusercontent.com/11641379/57692710-0a281f00-767a-11e9-906a-9e4ec503aae5.png)

**Comment by Coeur** [comment]
We can't help with comments in Chinese.
And we can only help if you've been using CocoaPods or Carthage, or if you provide a sample project.
Also, please read previous comment about making sure that SSZipArchive.h is public.

**Comment by cj1024** [comment]
> We never use _canPerformAction: in our code, we use respondsToSelector:. You may be using some fork of our project, but not the code from here.
> And for the zipArchive methods, maybe you did not include SSZipArchive.h as a public header. It's best to use CocoaPods integration: non-standard installations aren't supported by us.
> Or you're using Carthage and you forgot to remove/sync the debug symbols before shipping.

I checked my project and I believe that _canPerformAction: is caused by Flipboard's FLEX.
So I dropped FLEX and use ZipArchive instead of SSZipArchive.
Finally that works.

**Comment by cj1024** [comment]
> 我也遇到了这样的问题，请问这个是怎么解决的？

如果你也用了FLEX，那可能是因为FLEX，但我是把FLEX和SSZipArchive都下掉了
