### ISSUE TITLE
Can't compile files manually

### ISSUE THREAD

**Issue by mark33699** [ZipArchive/ZipArchive#508]
Hello Everybody:

I try manually installation,
code: https://drive.google.com/file/d/1PtO6SsqNBOnD7KtFw-8YShjW-jQWXaIz/view?usp=sharing

Undefined symbol: _OBJC_CLASS_$_SSZipArchive
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_SSZipArchive", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64

I do follow this:
1.Add the SSZipArchive and minizip folders to your project.
2.Add the libz library to your target
3.try all issue soultion
3.1 Other Linker Flags add $(inherited)
3.2 can't assign Target to every ".c" file

great thanks

**Comment by Coeur** [comment]
You added the ZipArchive folder as a "folder reference" (blue icon), which should almost exclusively only be used for assets (images, audio, fonts, data, etc.).

Instead, add the ZipArchive folder as a "group" (yellow icon). This requirement applies for any code that you would like to compile.

Note that we normally only support framework or lib integration (CocoaPods or Carthage or sub-project), to avoid potential surprise side effects of compiling everything together. Also working with frameworks makes compilation faster in a working environment.

**Comment by mark33699** [comment]
Hi Coeur:

After I change "folder" to "group" & edit import path, it compile success.
Thanks for your help & note.

Mark
