### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by xjh093** [ZipArchive/ZipArchive#512]
dyld: Library not loaded: @rpath/ZipArchive.framework/ZipArchive
  Referenced from: /var/containers/Bundle/Application/CF4B4C68-5B64-4950-A420-438FB5258339/Box.app/Box
  Reason: image not found

in iPhone5s

**Comment by Coeur** [comment]
- How did you integrate it? CocoaPods, Carthage, Subproject?
- Objective-C or Swift app? Which iOS version? 
- Can you provide a fork of our example app demonstrating the issue?

**Comment by xjh093** [comment]
I download the release source of framework
iOS app
Real-device only

**Comment by xjh093** [comment]
Real-device: 6 Plus

<img width="670" alt="屏幕快照 2019-05-14 下午4 14 20" src="https://user-images.githubusercontent.com/7610880/57682202-dcd07680-7663-11e9-86bc-2b8cc08a05aa.png">

<img width="927" alt="屏幕快照 2019-05-14 下午4 18 58" src="https://user-images.githubusercontent.com/7610880/57682260-0093bc80-7664-11e9-8e70-7bfb901831bd.png">

**Comment by xjh093** [comment]
simulator:
- 5s 12.2

<img width="793" alt="屏幕快照 2019-05-14 下午4 25 07" src="https://user-images.githubusercontent.com/7610880/57683131-aa277d80-7665-11e9-977f-d7db8cca3211.png">

<img width="792" alt="屏幕快照 2019-05-14 下午4 25 20" src="https://user-images.githubusercontent.com/7610880/57683173-c1666b00-7665-11e9-91ac-c5179a6ef6a3.png">

**Comment by Coeur** [comment]
<img width="1353" alt="Screen Shot 2019-05-14 at 16 43 58" src="https://user-images.githubusercontent.com/839992/57684008-7f3e2900-7667-11e9-8c3e-751ec02c8c36.png">

Please double-check your integration. There is nothing wrong on the given scenarios.

**Comment by Coeur** [comment]
@xjh093 I've just updated the manual instructions, maybe that was the misunderstanding: https://github.com/ZipArchive/ZipArchive/commit/4d35a841a3ad3deeb0b2ba244f341ba03a319a42

**Comment by Coeur** [comment]
Also, you need the following GCC_PREPROCESSOR_DEFINITIONS:
```
HAVE_INTTYPES_H HAVE_PKCRYPT HAVE_STDINT_H HAVE_WZAES HAVE_ZLIB MZ_ZIP_NO_SIGNING $(inherited)
```

**Comment by Coeur** [comment]
Just to be clear, if there is still an issue, I can only help if you provide an [MCVE](https://stackoverflow.com/help/mcve) project. And it's a thousand times better to use Carthage or CocoaPods: they are tools designed to solve all those setup issues. Not using Carthage or CocoaPods should only be done by people able to debug those issues themselves.

**Comment by xjh093** [comment]
Thank you~
