### ISSUE TITLE
Cannot cancel extract operation

### ISSUE THREAD

**Issue by TheFlow95** [ZipArchive/ZipArchive#514]
I want to extract a file asynchronously so I used `OperationQueue` like this:
```swift
let queue = OperationQueue()
queue.addOperation {
    do {
        _ = try archive.extract(entry, to: temporaryFileURL)
        completionHandler(temporaryFileURL)
    } catch {
        print("Cannot extract video file: \(error)")
    }
}
```

And then I want to cancel my operation with `queue.cancelAllOperations()` but the extraction work doesn't stop…
How to fix it?

Thanks

**Comment by Coeur** [comment]
You may need a Cancel delegate like I wrote in this comment: https://github.com/ZipArchive/ZipArchive/issues/374#issuecomment-330404394

**Comment by willson-chen** [comment]
@TheFlow95 I will close this issue, and repoen if any problems.
