### ISSUE TITLE
Unable to compile version 2.2.1 in an iOS project

### ISSUE THREAD

**Issue by fkelly** [ZipArchive/ZipArchive#515]
Hi, this is probably something I'm doing wrong, but I'm hoping you'll have some insight. I have an iOS project I'm working on and I've tried to include SSZipArchive 2.2.1 in my Podfile, but I get compile errors. Just by way of example, it's complaining about the symbol `CMSEncodeContent` in mz_crypt_apple.c, which appears to be defined for macOS, but not iOS. There are many other errors, most or all, relating to mz_crypt_apple.c.

I don't encounter this problem for versions < 2.2.0; e.g. 2.1.0 compiles just fine.

Any suggestions you have would be most welcome.

Thanks.

**Comment by Coeur** [comment]
`CMSEncodeContent` is part of the `Security` framework which is explicitly written in the podspec:
https://github.com/ZipArchive/ZipArchive/blob/97956a9c62f798c734a82223eff1c2482c0ebdac/SSZipArchive.podspec#L17

So you're either using a custom podspec, or a broken version of CocoaPods. Make sure you're using CocoaPods 1.6.1. If you're using 1.7.0.rc.2, then tell me and I'll try to investigate.
