### ISSUE TITLE
isPasswordValidForArchive returns false for old zips

### ISSUE THREAD

**Issue by Florrr** [ZipArchive/ZipArchive#516]
I've recently updated the library from 2.1.4 to 2.2.1 using CocoaPods. I've noticed, that the function `isPasswordValidForArchive` returns false in 2.2.1 for an aes encrypted zip file created in 2.1.4. (`NSErrorPointer` is nil)
Zip files created in the same Version (2.2.1) are working.

**Comment by Coeur** [comment]
You mean that you can't unzip a file created in a previous version?
I've normally tested such scenario before releasing 2.2.x.

Could you provide an example archive?

**Comment by Coeur** [comment]
I've reproduced the issue. I do not know how to fix it. Maybe Nathan can help.

**Comment by Coeur** [comment]
Fixed by Nathan. I've added a Unit Test for AES to avoid that issue in the future.
Bugfix release version 2.2.2 very soon.
