### ISSUE TITLE
In Version 2.2.1 I can no longer unzip single file archives on Mac OS Mojave with AES turned on.

### ISSUE THREAD

**Issue by JeffersonSchuler** [ZipArchive/ZipArchive#517]
Files are zipped on iOS and then unzipped on Mac and Windows machines.
Version 2.1.5 would allow AES to be turned on as long as a third party unzip tools was used.  Now they do not work either.  Setting the AES flag to false, allows all tools to unzip with password.

**Comment by Coeur** [comment]
We've changed AES from _Brian Gladman_ to _Apple CommonCrypto_: https://opensource.apple.com/source/CommonCrypto/
But it wasn't the only change.

I need to understand better your scenario: which third party (on macOS) has an issue now?

**Comment by JeffersonSchuler** [comment]
I have tried two.  The Unarchiver and 7zX.  The Unarchiver gives the error: "Error on decrunching".  
7zX gives:  "Data Error in encrypted file. Wrong Password?"  Sub items: Errors: 1

They both worked previously.  The built in unzip tool never worked with AES turned on. 

I am zipping small single text files.

**Comment by Coeur** [comment]
I've never heard of 7zX before and after a search, it disappeared from the internet in 2014: https://web.archive.org/web/20141010181216/http://sixtyfive.xmghosting.com/. Their last release was [in March 2008](https://web.archive.org/web/20080317000513/http://sixtyfive.xmghosting.com:80/products/7zx/).

I'll take a look at The Unarchiver.

**Comment by JeffersonSchuler** [comment]
I just tried Keka and got the error: "Error code 334 using "p7zip" Bad password, try again"

**Comment by Coeur** [comment]
My first guess is that it's related to another bug report from today, #516.
I may wait for Nathan answer on it, or we may have to rollback to Brian Gladman AES.

**Comment by paolo31415** [comment]
Same here, instead I'm having to turn of AES in my Swift compression. At least it's still password protected, although not terribly secure I guess. GDPR :-/

        SSZipArchive.createZipFile(atPath: fileNameUrl.path, withContentsOfDirectory: NSURL(fileURLWithPath: NSTemporaryDirectory()).path!, keepParentDirectory: false, compressionLevel: 0, password: pw, aes: false, progressHandler: nil)

**Comment by Coeur** [comment]
Fixed by Nathan. I've added a Unit Test for AES to avoid that issue in the future.
Bugfix release version 2.2.2 very soon.
