### ISSUE TITLE
Still won't decompress on Mac

### ISSUE THREAD

**Issue by paolo31415** [ZipArchive/ZipArchive#518]
Using 2.2.2 (with the new AES fix), it still doesn't unzip on mac using

      SSZipArchive.createZipFile(atPath: fileNameUrl.path, withFilesAtPaths: [tempFile!.path], withPassword: pw)

The native right clicking the zip on the mac desktop and clicking open with the native archive manager gives the error:

      "Error 1 - operation not permitted"

If I go to the terminal I get the error:

      Archive:  temp.zip ... skipping: file.csv  need PK compat. v5.1 (can do v4.5)

**Comment by Coeur** [comment]
Native compress tool on mac doesn't support AES at all.
You need The Unarchiver or Keka.
Or you need to compress without AES.

**Comment by Coeur** [comment]
I understand that it may be frustrating. I believe that in ZipArchive 3.0, I'll change the signature of the methods to make it clearer when AES is used and when it's not.

**Comment by paolo31415** [comment]
Thanks for the info, didn't know that. I managed to get it working by setting AES to false. Theres a command for that, and it worked in native unzip. I'll try 2.2.2 with keka or The Unzipoer then too.

Do you happen to know if it still encrypts the files without AES? ... does it use a different encryption method?

**Comment by Coeur** [comment]
@paolo31415  Yes, it uses a different encryption method, the classic PKWare method:
https://crypto.stackexchange.com/questions/60567/which-encryption-algorithm-is-used-for-password-protecting-a-file

**Comment by paolo31415** [comment]
@Coeur using 2.2.2, The Unarchiver says "Error on decrunching"
It allows me to "Continue," and it does create the file, but the text file contains nothing.

**Comment by Coeur** [comment]
As written in other issues, I made a unit test this time. So please find the file *TestAESPasswordArchive.zip* in https://github.com/ZipArchive/ZipArchive/tree/master/Example/ObjectiveCExampleTests/Fixtures and see if you can decompress it with The Unarchiver. ([password is "passw0rd" as seen here](https://github.com/ZipArchive/ZipArchive/blob/582949eaf50e988305bc9e76302ab020ca3d900b/Example/ObjectiveCExampleTests/SSZipArchiveTests.m#L209))

For me, it works. If your file doesn't succeed at decompressing, you'd need to share it.
