### ISSUE TITLE
Is zip64 supported? 

### ISSUE THREAD

**Issue by anilsudhakaran** [ZipArchive/ZipArchive#521]
Is zip64 supported? We are having issues unzipping the attached file via our app using version 
[A_300100181351411.zip](https://github.com/ZipArchive/ZipArchive/files/3258024/A_300100181351411.zip)
2.1.4 of this library.

**Comment by nmoinvaz** [comment]
Please provide more details about the _issues_ you are having.

**Comment by anilsudhakaran** [comment]
SSZipArchive - 2.1.4
Calling SSZipArchive.unzipFile returns true even though files are not unzipped. Here's a sample iOS project.
[TestSSZipArchive.zip](https://github.com/ZipArchive/ZipArchive/files/3273912/TestSSZipArchive.zip)

**Comment by joelfischerr** [comment]
MiniZip supports zip64 but it is disabled in the current version of ZipArchive (2.2.3). See #579

**Comment by jhudsonWA** [comment]
This was answered and handled in #580.
