### ISSUE TITLE
When I Archive my project ,There are some problems occur.

### ISSUE THREAD

**Issue by wangchaohao123** [ZipArchive/ZipArchive#526]
Hi,
When I build and run my program ,There is no problem. But,When I want to archive my program,There are always some problems,like the Image show, and I don't know how to solve them. I have import the libz.tbd. Could you give me some advice? Thanks..
![4B214368-5B13-465A-8D77-B993ECB2BF7B](https://user-images.githubusercontent.com/54013016/62844794-347b8e00-bcf6-11e9-922a-0edfbcc53cf6.png)
![747900F4-EF0A-4ED3-A7AE-9F9E897C0BC2](https://user-images.githubusercontent.com/54013016/62844849-90dead80-bcf6-11e9-8a77-9493ef660e1f.png)

**Comment by nmoinvaz** [comment]
I can't remember exactly but I think you have to link Security framework.

**Comment by Coeur** [comment]
@wangchaohao123 we support three installation procedures:

- CocoaPods, following those steps: https://github.com/ZipArchive/ZipArchive#cocoapods
- Carthage, following those steps: https://github.com/ZipArchive/ZipArchive#carthage
- Manual, following those steps: https://github.com/ZipArchive/ZipArchive#manual

Please make sure that you've followed the installation steps correctly. If the problem persists, please specify:
- the installation method (CocoaPods, Carthage, Manual)
- the platform (iOS, macOS, ...)
- Xcode version
- and provide a sample project that can reproduce the issue

Thank you

**Comment by wangchaohao123** [comment]
> I can't remember exactly but I think you have to link Security framework.

Thanks, I have resolve the problem. I think the reason for this problem is because   I archive my program in debug mode, but I forgot to change Archive's  " Build configuration" to debug mode, It was my carelessness.

**Comment by wangchaohao123** [comment]
> @wangchaohao123 we support three installation procedures:
> 
> * CocoaPods, following those steps: https://github.com/ZipArchive/ZipArchive#cocoapods
> * Carthage, following those steps: https://github.com/ZipArchive/ZipArchive#carthage
> * Manual, following those steps: https://github.com/ZipArchive/ZipArchive#manual
> 
> As you wrote "_I have import the libz.tbd_", I suspect you're on a manual installation scenario, which, as written in the doc, requires **libz**, **libiconv** and **Security**.
> 
> Please make sure that you've followed the installation steps correctly. If the problem persists, please specify:
> 
> * the installation method (CocoaPods, Carthage, Manual)
> * the platform (iOS, macOS, ...)
> * Xcode version
> * and provide a sample project that can reproduce the issue
> 
> Thank you


Thank you for your reply.  My installation method is Manual. I think the reason for this problem is because I archive my program in debug mode, but I forgot to change Archive's " Build configuration" to debug mode, It was my carelessness. 
 I notice that  " Add the following GCC_PREPROCESSOR_DEFINITIONS: HAVE_INTTYPES_H HAVE_PKCRYPT HAVE_STDINT_H HAVE_WZAES HAVE_ZLIB MZ_ZIP_NO_SIGNING $(inherited)" , Now I have added them in my program . There is no problem with archive again.  I don't understand why they need to be added.

**Comment by Coeur** [comment]
>I don't understand why they need to be added.

Well, `HAVE_WZAES` allows you to zip/unzip password protected archives for instance. You can look at the code to see what those flags activate/deactivate.
