### ISSUE TITLE
Example does not compile "from the box"

### ISSUE THREAD

**Issue by sgdmitriev** [ZipArchive/ZipArchive#528]
Hi.
I try to build Example in ZipArchive, but got error
/Users/admin/Documents/ZipArchive-master/Example/Pods/Target Support Files/Pods-core-ObjectiveCExample/Pods-core-ObjectiveCExample.debug.xcconfig: unable to open file (in target "ObjectiveCExample" in project "ZipArchiveExample") (in target 'ObjectiveCExample')
Maybe I don't understand something and new for github, but I think example just should work from the box. XCode 10.2.1. Objective C

2. Add the following GCC_PREPROCESSOR_DEFINITIONS: HAVE_INTTYPES_H HAVE_PKCRYPT HAVE_STDINT_H HAVE_WZAES HAVE_ZLIB MZ_ZIP_NO_SIGNING $(inherited).
Where is the place for this key?

**Comment by Coeur** [comment]
- What is in the folder `Pods` is created by a CocoaPods installation.
- What is in the folder `Carthage` is created by a Carthage installation.
- You only need to manually set the GCC_PREPROCESSOR_DEFINITIONS if you attempt an installation by yourself.

I would recommend reading https://guides.cocoapods.org/using/getting-started.html as it's the easiest and a widely used way of installing third-parties.
=> If demo doesn't build, try those steps from the demo folder:
- `gem install cocoapods`
- `pod install`
- open the .xcworkspace file

If you want to add a bit of custom architecture to your project, you may use Carthage instead.

Once you've got experience with all the aspects of an Xcode project, and you want to make things a million times more complex and very difficult for your project collaborators, you can decide to try the manual steps.
https://stackoverflow.com/a/57479570/1033581

**Comment by sgdmitriev** [comment]
Thank you, Antoine. Especially for the last link
There are many issues with manually setting up Example
Besides place for GCC_PREPROCESSOR_DEFINITIONS, I stuble of
minizip directory type and way of creation in Xcode
