### ISSUE TITLE
"Failed to open zip file" on iOS 13

### ISSUE THREAD

**Issue by markymc** [ZipArchive/ZipArchive#537]
I'm seeing a problem that's started occurring in iOS 13, where I'm getting an error with "Failed to open zip file" when attempting to unzip a file. This used to work fine on iOS 12. 

I've confirmed that the file exists and is readable. It looks like `zipFile zip = unzOpen(path.fileSystemRepresentation);` is returning `NULL`. Has anyone else seen this? If so, is there a workaround? I don't really understand why this is suddenly happening in iOS 13.

Thanks!

EDIT - as a follow up, it looks like `mz_zip_open` is returning a `MZ_EXIST_ERROR`. But I'm not sure why.

**Comment by quanvo87** [comment]
unzipping a file on iOS 13 is also failing for me. Worked on iOS 12.

**Comment by markymc** [comment]
Actually I discovered that the file that was downloaded was not in fact a zip file, and was a text file containing an error message from Amazon regarding an auth error that was due to some changes in the way iOS 13 sent URL requests. Will close this. Sorry for the spam!

**Comment by henryyohn** [comment]
> unzipping a file on iOS 13 is also failing for me. Worked on iOS 12.

I have the problem, do you solve it.
