### ISSUE TITLE
ITMS-90338: Non-public API usage

### ISSUE THREAD

**Issue by msh940620** [ZipArchive/ZipArchive#538]
ITMS-90338: Non-public API usage:

zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:unzippedFilePath:
zipArchiveProgressEvent:total:. 

in: SSZipArchiveDelegate
```
- (void)zipArchiveDidUnzipFileAtIndex:(NSInteger)fileIndex totalFiles:(NSInteger)totalFiles archivePath:(NSString *)archivePath unzippedFilePath:(NSString *)unzippedFilePath;
- (void)zipArchiveProgressEvent:(unsigned long long)loaded total:(unsigned long long)total;
```

**Comment by jhudsonWA** [comment]
See #551. This is not because of SSZipArchive as available on current master branch or latest CocoaPods/Carthage releases. This library is used in MANY store applications.

This is caused by another dependency, or some modified/different version of ZipArchive.
