### ISSUE TITLE
because of iOS 13 Non-Public API usage, the release version unzip failed

### ISSUE THREAD

**Issue by henryyohn** [ZipArchive/ZipArchive#541]
<img width="647" alt="屏幕快照 2019-10-08 上午7 33 15" src="https://user-images.githubusercontent.com/37692583/66356621-341e0d00-e99e-11e9-9094-a862738685ec.png">

my app unzip always fails on release version, but the debugger is ok. Im not sure that reason. could tell me how can I fix this. thank you!

**Comment by Coeur** [comment]
Not because of SSZipArchive as available on current master branch or latest CocoaPods/Carthage releases.

This is caused by another dependency, or some modified/different version of ZipArchive.

And `ddSetLogLevel` is a famous symbol from **CocoaLumberjack** by the way.

**Comment by ygj6** [comment]
#538
