### ISSUE TITLE
unzipFile(atPath: toDestination:) always returning false on iOS Simulator on Xcode 11.2 beta (11B41)

### ISSUE THREAD

**Issue by rodrigoaraujo01** [ZipArchive/ZipArchive#542]
I'm using version 2.2.2, and unzipFile(atPath: toDestination:) always returns false on the simulator. On my iPhone 8Plus, it works flawlessly.

I've debugged the error and it seems the function fopen64 is always returning NULL.

I'm currently on macOS Catalina 10.15 (19A583) and Xcode 11.2 beta (11B41).

**Comment by henryyohn** [comment]
I have the same problem. do you get a method to solve it?

**Comment by AppHock** [comment]
Oh no, I have the same problem.

**Comment by YangYiBo23** [comment]
I have the same problem. do you get a method to solve it?

**Comment by rodrigoaraujo01** [comment]
I haven't found a solution, as a workaround, I've stopped testing on the simulator and only test on my phone.

**Comment by willson-chen** [comment]
Hi, all. Did you resolve it by upgrading your Xcode version? I run ObjectiveCExample, which includes zip and unzip operations, on iOS Simulator on **Xcode 11.3 (11C29)**. And there is no error.

I wonder if this error only exists on Xcode 12.2 beta. Could you help me?

**Comment by jhudsonWA** [comment]
No response in over a year. Please re-open if still an issue.
