### ISSUE TITLE
Unzip png issues

### ISSUE THREAD

**Issue by NedLu** [ZipArchive/ZipArchive#543]
I put one png file in a folder
when  us  
+ (BOOL)unzipFileAtPath:(NSString *)path
          toDestination:(NSString *)destination
     preserveAttributes:(BOOL)preserveAttributes
              overwrite:(BOOL)overwrite
         nestedZipLevel:(NSInteger)nestedZipLevel
               password:(nullable NSString *)password
                  error:(NSError **)error
               delegate:(nullable id<SSZipArchiveDelegate>)delegate
        progressHandler:(void (^_Nullable)(NSString *entry, unz_file_info zipInfo, long entryNumber, long total))progressHandler
      completionHandler:(void (^_Nullable)(NSString *path, BOOL succeeded, NSError * _Nullable error))completionHandler;

to unzip it return error: Error Domain=SSZipArchiveErrorDomain Code=-2 "failed to open file in zip file" UserInfo={NSLocalizedDescription=failed to open file in zip file}

when .png file change to .txt file it work

**Comment by willson-chen** [comment]
Any .png file could reproduce this bug? Or could you please offer the .png file? And could you please offer more information to help reproduce?

**Comment by willson-chen** [comment]
Hi @NedLu. Your reply and help to reproduce this issue would be highly appreciated. :)

**Comment by NedLu** [comment]
When i change to older version this issue fix, thx for help!

**Comment by willson-chen** [comment]
Could you please specify how to reproduce this issue? If it still exists in current version, we hope we could fix it.

**Comment by zhuozhuo** [comment]
> When i change to older version this issue fix, thx for help!

same problem. Which version did you use to fix the problem?

**Comment by zhuozhuo** [comment]
My problem is that the script packaging is overriding the macro definition.
The correct way to write it is inheritance. For example:
```GCC_PREPROCESSOR_DEFINITIONS='$GCC_PREPROCESSOR_DEFINITIONS ISRELEASE=1'```

**Comment by Coeur** [comment]
We already succeed at zipping/unzipping png in our unit tests:
https://github.com/ZipArchive/ZipArchive/blob/main/Example/Sample%20Data/mountain.png

Closing for lack of sample reproducing the issue.
