### ISSUE TITLE
Problem unzipping files with word "accent" - "dissolução" becomes "dissoluc╠ºa╠âo"

### ISSUE THREAD

**Issue by danielCarlosCE** [ZipArchive/ZipArchive#545]
Original file is `Rápida dissolução no trato gastrointestinal (TGI).png` 
Unzipped file is `Ra╠üpida dissoluc╠ºa╠âo no trato gastrointestinal (TGI).png` 

Because of that app is unable to find right file. 

(SSZipArchive (2.2.2))

**Comment by willson-chen** [comment]
@danielCarlosCE Hello, can you provide a zip file that can reproduce the problem?
I created a folder `test`, added a file with the file name `Rápida dissolução no trato gastrointestinal (TGI).png`,  and unzipped it with ziparchive 2.2.2 everything works fine.

**Comment by VNKorchagin** [comment]
Hi @willson-chen! I'm faced with this issue too. Still reproduce on SZipArchive (2.2.3)

[This](https://bitbucket.org/bacc3/zipissueexample/src/master/) is a small test project
[This](https://drive.google.com/file/d/1HgbAFUZt4owA_1TQgYo7kuJtxgrMQZdz/view?usp=sharing) is only zip file

**Comment by willson-chen** [comment]
@VNKorchagin In fact, the 2.2.3 version does not solve this problem, the PR #562 will not be merged until v3.0.

**Comment by MarkBirch3D** [comment]
Do we have an ETA for this issue to be fixed?
