### ISSUE TITLE
the release IPA can not unzip files on ios13, but ios12 is ok.

### ISSUE THREAD

**Issue by henryyohn** [ZipArchive/ZipArchive#546]
I use ZipArchive lib to unzip zip files in my app. it work well on ios 12, but it can not unzip zip files on ios 13. 
I used fileManager to check my zip files permission (Writable,Readable,Executable). before unzip all permission is enable.  but after handling the file by function(unZipFileAtPath: toDestination: progressHandler: completionHandler), the permissions are enable and getting the error info: can not open the file.

is there any wrong!

**Comment by henryyohn** [comment]
follow up the issue:
I debug on Simulator or iPhone devices, always a success. even on ios 13. It is strange!

**Comment by Coeur** [comment]
Simulator would always have different file permissions, as it's running on macOS instead of iOS.
Could you share a sample zip file?
Could you see if you have the same issue with `preserveAttributes: false`?
https://github.com/ZipArchive/ZipArchive/blob/63cc9b455c32cbbeb4df5017390e0f6a2af50c78/SSZipArchive/SSZipArchive.h#L77

**Comment by henryyohn** [comment]
my zip file is downloaded from the network by NSURLSessionDownloadTask. And, I have the new discoveries that if I set the NSURLSessionConfiguration to backgroundSessionConfigurationWithIdentifier, the download zip file can not be opened anyway, so that I can't unzip it.
But, if Set the NSURLSessionConfiguration to default(no change other settings and codes), the download zip file exactly can be unzipped correctly.

this is my zip file download link: [https://down.hoyi52.com/test/static.zip]

I already tried those unzip code, Still failing:
`BOOL success = [SSZipArchive unzipFileAtPath:pageZipPath
                                toDestination:staticPath
                           preserveAttributes:YES
                                    overwrite:YES
                                     password:nil
                                        error:&error
                                     delegate:nil];`
`+ (BOOL)unzipFileAtPath: toDestination: progressHandler: completionHandler:`

**Comment by willson-chen** [comment]
@henryyohn Hello, I created a simple project with the function of downloading zip file from the network by NSURLSessionDownloadTask and using ZipArchive lib unzip function to decompress the zip file to reproduce your problem.However it could always unzip successfully.
My project link: [NSURLSession](https://github.com/willson-chen/NSURLSession/tree/master/NSURLSession)

**Comment by willson-chen** [comment]
@henryyohn  I will close this issue first. Reopen if still have an issue.
