### ISSUE TITLE
Appears to be an issue with iOS 13 and AES encryption with v2.2.2

### ISSUE THREAD

**Issue by atticus** [ZipArchive/ZipArchive#547]
I have an app that uploads a zip file of logs periodically. I use AES encryption on the zip file. Starting about 5 weeks ago, the uploaded files are now corrupted and can't be extracted. The messages I'm getting are similar to the bug that prompted v2.2.2, but I'm running v2.2.2 with these issues.

I'm not 100% that the issue is iOS 13 related, but we have been using v2.2.2 almost since release, and the corrupted zip files roughly start around the time of iOS 13's release. And given that v2.2.2 uses Apple crypto, it seems possible that Apple may have changed something, or exposed an option that changed the behavior.

Reverting to ZipArchive v2.1.4 (before the Apple crypto) has resolved the problem; The zip files can now be un-zipped again.

Here's a sample of how I use ZipArchive:

```
let documentsURL = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
let logsURL = documentsURL.appendingPathComponent("SomeLogs")
let zipURL = documentsURL.appendingPathComponent(fileName ?? "SomeLogs.zip")
let success: Bool = SSZipArchive.createZipFile(atPath: zipURL.path,
                                                       withContentsOfDirectory: logsURL.path,
                                                       keepParentDirectory: false,
                                                       compressionLevel: -1,
                                                       password: aPasswordString,
                                                       aes: true,
                                                       progressHandler: nil)
```

If there's anything I can add that would be helpful, please let me know.

**Comment by willson-chen** [comment]
Hi, is there any way to reproduce this bug?

**Comment by nmoinvaz** [comment]
There was a bug in minzip's AES implementation when using AppleCrypto that was fixed. See nmoinvaz/minizip#397 and nmoinvaz/minizip#398. Perhaps they were using an old version that had the bug and switched to a version where the bug was fixed and found the old files no longer unzipped properly.

**Comment by willson-chen** [comment]
@nmoinvaz Thanks for the explanation!
@atticus I will close this issue, and will repoen it if problem still exists.
