### ISSUE TITLE
the method(mz_crypt_sign_verify) in mz_crypt_apple.c  on Xcode11.2 ,the line "CMSDecoderRef decoder = NULL" throw out error : Use of undeclared identifier 'CMSDecoderRef'

### ISSUE THREAD

**Issue by code1303009** [ZipArchive/ZipArchive#548]

**Comment by willson-chen** [comment]
Could you please offer more information? You compile ZipArchive failed with the error thrown?

**Comment by code1303009** [comment]
> Could you please offer more information? You compile ZipArchive failed with the error thrown?

I had fixed it by remove ' mz_crypt_apple.c' file

**Comment by willson-chen** [comment]
> > Could you please offer more information? You compile ZipArchive failed with the error thrown?
> 
> I had fixed it by remove ' mz_crypt_apple.c' file

A simple way to resolve the bug, but not best. It is so kind of you if you could specific your problem. And we could have a check if there is space to improve ZipArchive.
