### ISSUE TITLE
File corrupted after zip and unzip

### ISSUE THREAD

**Issue by trondkr** [ZipArchive/ZipArchive#551]
Hi, I create a zip file of any Macos application file (.app file, e.g. Adobe Illustrator, ) using the SSZipArchive:

       let _=SSZipArchive.createZipFile(atPath:zipFilePath.path,
                                                   withContentsOfDirectory: fileURL.path,
                                                   keepParentDirectory: false,
                                                   withPassword: nil,
                                                   andProgressHandler: { (read_files, total_files) in
                                                    let progress=Double(read_files)/Double(total_files)
                                                    self.update_progress_of_zip(progress:progress, 
    finished:read_files==total_files)
                })

If I then unzip the same file using :

      let _: Bool = SSZipArchive.unzipFile(atPath: fileURL.path,
                                             toDestination: destinationURL.path,
                                             preserveAttributes: true,
                                             overwrite: true,
                                             nestedZipLevel: 1,
                                             password: nil,
                                             error: nil,
                                             delegate: nil,
                                             progressHandler:{(entry, zipInfo, readByte, totalByte) -> Void in
                                                
                                                let per=Double(readByte)/Double(totalByte)
                                                self.update_progress_of_unzip(progress: per, finished: false)
                                                
        }, completionHandler:completionHandler

The application file is corrupted and won't open on Macos Catalina. I assume something happens with the codesigning as perhaps some files or folders are not preserved as they should be. If I use Swift/Objective-c FileManager zip tool to zip the file:

      try? fileManager.zipItem(at: fileURL, to: zipFilePath, shouldKeepParent:false)

 and then use SSZipArchive to do the unzipping everything works fine and the application is not corrupted. The thing is I would like to use SSZipArchive consistently but I have trouble getting this to work. any suggestions as to what may be wrong? Thanks for your help. Cheers, Trond

**Comment by trondkr** [comment]
I guess this problem is probably caused by how SSZipArchive handles symlinks. I see that the zip file grows in size suggesting that symlinks are followed and included and not kept as symlinks. But according to the commit on May 2nd 2019 symlinks should be working correctly:

https://github.com/nmoinvaz/minizip/commit/3249eac0879c1e7693707a31d45c37ce164fbb4b

(I use latest cocoapod release for macos)
Do I need to define an option to enable symlinks? 

Would really appreciate help on this. Thanks again. T

**Comment by trondkr** [comment]
I just confirmed that its the missing symlinks that causes my problem. Below is a image of the difference between the correct and unzipped file missing symlinks. 

I wonder if there is a specific branch I need to use to make symlinks work or do I need to use the manual installations as the cocoapod version is not updated?

<img width="1555" alt="Screenshot 2019-12-11 at 10 37 02" src="https://user-images.githubusercontent.com/3648387/70649571-43ba0c00-1c02-11ea-8652-cecc9f3a76bb.png">

**Comment by willson-chen** [comment]
@trondkr hi, I have a deep research on this issue. I think you want the function that ZipArchive could zip the symlink itself, right? The commit [nmoinvaz/minzip@3249eac](https://github.com/nmoinvaz/minizip/commit/3249eac0879c1e7693707a31d45c37ce164fbb4b) you memtion in your last comment indeed implements the function. But it is only implemented on `mz_zip_writer/mz_zip_reader`, which is one of three series APIs, while ZipArchive uses `mz_compat` to zip and unzip files. Please reference to [nmovaz/minizp Issue #446](https://github.com/nmoinvaz/minizip/issues/446) and [reply in Issue #445](https://github.com/nmoinvaz/minizip/issues/445#issuecomment-577194490).

**Comment by willson-chen** [comment]
I am trying to resolve this issue. IMHO, there are some problems on how to design this function. List as follow:
1. Shall we implement it in ZipArchive or minizip? I noticed there is a [PR](https://github.com/ZipArchive/ZipArchive/pull/424) ever try to add support to zip symlink, by adding codes in ZipArchive. Considering minizip has such function already(although just in `mz_zip_writer/mz_zip_reader`), adding this function to `mz_compat` of minizip sounds more reasonable.
2. There are three options for the design of APIs to support this function:
* Add a new API named `createZipFileAtPath:withFilesAtPath:symlink:`, for example. It can keep compatible with previous version.
* Add a parameter for current API.
* Zip the symlink itself instead the original file by default. Not a good choice, there are still some users wants to zip the original file.

@Coeur hi, could your please help to resolve these questions?

**Comment by Coeur** [comment]
So, third option is not acceptable obviously.

First option seems the best approach for now, as we're in Objective-C. The `symlink:` parameter needs to be named clearly like `keepSymlinks: BOOL`.

**Comment by jhudsonWA** [comment]
PR #560 merged into master. This should fix this bug if you use the right method signature (keepSymlinks:(BOOL)keeplinks)
