### ISSUE TITLE
Error Domain=SSZipArchiveErrorDomain Code=-2 "failed to open first file in zip file"

### ISSUE THREAD

**Issue by BlankConan** [ZipArchive/ZipArchive#555]
iPhonexsmax ios 12.4

zip first file type is `.json`

**Comment by willson-chen** [comment]
@BlankConan hi, I try to reproduce this bug by modifying source file `ZipArchive/Example/ObjectiveCExample/ViewController.m`. The target runs on simulator iPhonexsmax ios 12.4, but no error is generated.

Could you please offer the sample file?

**Comment by BlankConan** [comment]
> @BlankConan hi, I try to reproduce this bug by modifying source file `ZipArchive/Example/ObjectiveCExample/ViewController.m`. The target runs on simulator iPhonexsmax ios 12.4, but no error is generated.
> 
> Could you please offer the sample file?

it's ok when i replace the `.zip` file，thanks!

**Comment by willson-chen** [comment]
Thanks for your response and closing the issue. :)
