### ISSUE TITLE
App Crashes: Bad access while creating a zip file.

### ISSUE THREAD

**Issue by kapadiamoheet** [ZipArchive/ZipArchive#556]
Application crashes while creating a zip file below is the following code. Highlighted the line on which I am getting bad access.
```
File: SSZipArchive.m line #863.
-(BOOL)open
{
    NSAssert((_zip == NULL), @"Attempting to open an archive which is already open");
    **_zip = zipOpen(_path.fileSystemRepresentation, APPEND_STATUS_CREATE);**
    return (NULL != _zip);
}

**Thread 1: EXC_BAD_ACCESS (code=2, address=0x10540f998)**
```
Terminal Logs:
```
(lldb) po zipOpen(_path.fileSystemRepresentation, (0))
error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=2, address=0x10540f998).
The process has been returned to the state before expression evaluation.
```
My implementation:
```
BOOL successCompressing = [SSZipArchive createZipFileAtPath:archivePath withFilesAtPaths:fullPaths];
    if(successCompressing)
        NSLog(@"Success");
    else
        NSLog(@"Fail");
```

**Comment by ninjitaru** [comment]
also encountered this issue and downgraded to v2.1.5 seem to resolve the EXC_BAD_ACCESS error

**Comment by vlinde** [comment]
I updated to the latest version and I have the same issue.

Version v2.1.5 is working as expected, but I have a zip file with issues and when I try to unzip the file, the app crashes and I cannot catch the error.

At unzip I get the following error `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` at this line `        cx->f_begin(cx->sha_ctx);` in file `hmac.c`.

Is there any possibility to catch the error ?

**Comment by willson-chen** [comment]
Everything works fine in my project. Could you please specifiy your environment and version that I can reproduce this issue?

**Comment by vlinde** [comment]
When I tested I used the latest version implemented in the following Cordova plugin: https://github.com/vlinde/cordova-plugin-zeep 

The changes are not available on the git repository. I can push the changes to a beta branch but I don't know if that will help you to reproduce this issue.

I use xCode 11.3.1 and macOS Catalina 10.15.3

**Comment by ramywagdyrizkalla** [comment]
This crash happens with me also. It happens when I install it using SPM, but it's working fine with Cocoapods.

**Comment by Coeur** [comment]
Our unit tests do not reproduce any crash.

> This crash happens with me also. It happens when I install it using SPM, but it's working fine with Cocoapods.

That doesn't seem plausible: they would be the same code.

> At unzip I get the following error `Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)` at this line ` cx->f_begin(cx->sha_ctx);` in file `hmac.c`.

`hmac.c` was removed in 2.2.0. Let's not mix things up.

>When I tested I used the latest version implemented in the following Cordova plugin: https://github.com/vlinde/cordova-plugin-zeep

Oh my... that's a more than 6-years old copy of ZipArchive:
https://github.com/vlinde/cordova-plugin-zeep/tree/master/src/ios

>Version v2.1.5 is working as expected

From the issue creation date, I can only suppose that you were using ZipArchive 2.2.2, which could mean caused by #509 (update minizip-ng from 1.2.0 to 2.8.6).

ZipArchive is now at minizip-ng 4.0.7 (#724).

Please try a newer version. If crash is still happening on main branch of ZipArchive, kindly attach a crashlog.
