### ISSUE TITLE
Security concerns with using ECB mode for encryption

### ISSUE THREAD

**Issue by mjmadick** [ZipArchive/ZipArchive#557]
At our company we use CodePush for ReactNative app updates, and CodePush depends on ZipArchive.  

- CodePush (5.6.0):
    - Base64 (~> 1.1)
    - JWT (~> 3.0.0-beta.7)
    - React
    - SSZipArchive (~> 2.1)

Our security team flagged an issue with using weak ECB encryption mode, here:
https://github.com/ZipArchive/ZipArchive/blob/44970effad727e97a28a0b21e1f5a298949cb29a/SSZipArchive/minizip/mz_crypt_apple.c

mz_crypt_aes_set_encrypt_key calls _CCCryptorCreate(, _, kCCOptionECBMode, _, _, _, _)

Can this be addressed?
thanks.

Details from our security team:
Using ECB as the mode of operation for AES encryption can leak information about the content of the encrypted data, because identical plaintext blocks are encrypted into identical ciphertext blocks. Consequently, ECB does not hide data patterns well and does not provide proper message confidentiality; this is demonstrated in the screenshot which shows how patterns can leak information about the plaintext.

As a consequence, ECB mode is not recommended for use in cryptographic protocols at all.

Impact
ECB does not hide data patterns well and does not provide proper message confidentiality.

Remediation
As raw cryptographic algorithms are difficult to use securely due to subtle implementation flaws such as weak modes of operation or timing attacks, avoid directly using low-level cryptographic APIs (such as CCCrypt) to encrypt sensitive data.

Instead, consider relying on a high-level cryptographic library such as:

Apple's CryptoKit framework which is available starting with iOS 13.
If older versions of iOS need to be supported, RNCryptor (https://github.com/RNCryptor/RNCryptor) can be used instead.
If AES needs to be used directly, rely on the Cipher Block Chaining (CBC) mode in order to hide patterns within the ciphertext and ensure that random Initialization Vectors are used for each cryptographic operation.

Secure Code Example

Using RNCryptor:

// Example showing how to encrypt data with RNCryptor
NSData *data = [@"Data" dataUsingEncoding:NSUTF8StringEncoding];
NSError *error;
NSData *encryptedData = [RNEncryptor encryptData:data
                                    withSettings:kRNCryptorAES256Settings
                                          password:aPassword
                                             error:&error];
Using CryptoKit (iOS 13 - Swift):

// Example showing how to encrypt data with CryptoKit
let data = "Data".data(using: String.Encoding.utf8)
let key = SymmetricKey(size: .bits256)
let sealedBox = try! ChaChaPoly.seal(data!, using: key)
let encryptedData = sealedBox.combined
T

**Comment by nmoinvaz** [comment]
https://github.com/icsharpcode/SharpZipLib/issues/367

**Comment by Coeur** [comment]
@nmoinvaz

Are we in the case where "_we select ECB mode here is so that we can build our own mode on top of it_"?

Or are we in the case that if we change it, our archives wouldn't be readable by other libraries?

**Comment by nmoinvaz** [comment]
If you change it from ECB it will not be readable by other libraries or programs. It uses CTR (which he describes as "our own mode") on top of ECB.

**Comment by nmoinvaz** [comment]
> Using ECB as the mode of operation for AES encryption can leak information about the content of the encrypted data, because identical plaintext blocks are encrypted into identical ciphertext blocks.

I think because it uses CTR on top of ECB it prevents identical blocks.

**Comment by willson-chen** [comment]
@nmoinvaz Thanks for the explanation!
@mjmadick I will close this issue.
