### ISSUE TITLE
createZipFileAtPath  don’t return the creation result

### ISSUE THREAD

**Issue by EdwinXiang** [ZipArchive/ZipArchive#565]
+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath keepParentDirectory:(BOOL)keepParentDirectory

xcode:11.3.1
SSZipArchive：2.1.3
iPhone system：IPhone 7  10.2.1

when i  use   BOOL success = [SSZipArchive createZipFileAtPath:desFilePath withContentsOfDirectory:uploadDir keepParentDirectory:YES];
This method never returns the creation result，which causes the program card owner to move。how to do it?

**Comment by willson-chen** [comment]
Could you please post your related code block so that we could analyze it?

**Comment by ixulei007** [comment]
I have a truble

**Comment by willson-chen** [comment]
> I have a truble

If your trouble is different from this one, please create a new issue. Or please specific your issue with appending your comment. :)

**Comment by willson-chen** [comment]
I will close it first, reopen until any discussion.

**Comment by EdwinXiang** [comment]
I think I should paste all the code：
///上传日志临时目录
+ (NSString *)uploadTmpDirPath {
    NSString *path = [NSString stringWithFormat:@"%@/%@", [REDFileManager cachePath], @"uploadLogs"];
    return path;
}

///压缩包路径
+ (NSString *)zipFilePath {
    NSString *path = [NSString stringWithFormat:@"%@/%@", [REDFileManager temLogFolderPath], @"upload.zip"];
    return path;
}

+ (NSString *)cachePath {
     NSString *cachePath = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject];
    return cachePath;
}

+ (NSString *)temLogFolderPath
{
    //caches 路径,513 error ,permission deny
    NSString *caches = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject];
    NSString *tempLogPath = [caches stringByAppendingPathComponent:@"uploadLogs"];
    
    //查看目录如果已经存在就直接返回路径，否则创建目录并返回路径，如果创建路径失败则返回nil
    if (![[NSFileManager defaultManager] fileExistsAtPath:tempLogPath isDirectory:nil])
    {
        NSError *createError = nil;
        BOOL createSuccess = [[NSFileManager defaultManager] createDirectoryAtPath:tempLogPath withIntermediateDirectories:YES attributes:nil error:&createError];
        
        if (createSuccess) {
        }
        else
        {
            tempLogPath= nil;
        }
    }
    return tempLogPath;
}

+ (BOOL)zipUploadFiles {
    NSString *uploadDir = [self uploadTmpDirPath];
    NSString *desFilePath = [self zipFilePath];
    
    NSError *erro = nil;
    [[NSFileManager defaultManager] removeItemAtPath:desFilePath error:&erro];
    if (erro) {
        DDLogInfo(@"%@", erro);
    }
    
    BOOL success = [SSZipArchive createZipFileAtPath:desFilePath withContentsOfDirectory:uploadDir keepParentDirectory:NO];
    return success;
}

Hope it helps you analyze the problem。

**Comment by EdwinXiang** [comment]
`///上传日志临时目录

(NSString *)uploadTmpDirPath {
NSString *path = [NSString stringWithFormat:@"%@/%@", [REDFileManager cachePath], @"uploadLogs"];
return path;
}
///压缩包路径

(NSString *)zipFilePath {
NSString *path = [NSString stringWithFormat:@"%@/%@", [REDFileManager temLogFolderPath], @"upload.zip"];
return path;
}

(NSString *)cachePath {
NSString *cachePath = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject];
return cachePath;
}

(NSString *)temLogFolderPath
{
//caches 路径,513 error ,permission deny
NSString *caches = [NSSearchPathForDirectoriesInDomains(NSCachesDirectory, NSUserDomainMask, YES) lastObject];
NSString *tempLogPath = [caches stringByAppendingPathComponent:@"uploadLogs"];

//查看目录如果已经存在就直接返回路径，否则创建目录并返回路径，如果创建路径失败则返回nil
if (![[NSFileManager defaultManager] fileExistsAtPath:tempLogPath isDirectory:nil])
{
NSError *createError = nil;
BOOL createSuccess = [[NSFileManager defaultManager] createDirectoryAtPath:tempLogPath withIntermediateDirectories:YES attributes:nil error:&createError];

  if (createSuccess) {
  }
  else
  {
      tempLogPath= nil;
  }
}
return tempLogPath;
}

(BOOL)zipUploadFiles {
NSString *uploadDir = [self uploadTmpDirPath];
NSString *desFilePath = [self zipFilePath];

NSError *erro = nil;
[[NSFileManager defaultManager] removeItemAtPath:desFilePath error:&erro];
if (erro) {
DDLogInfo(@"%@", erro);
}

BOOL success = [SSZipArchive createZipFileAtPath:desFilePath withContentsOfDirectory:uploadDir keepParentDirectory:NO];
return success;
}`

**Comment by willson-chen** [comment]
Hi @EdwinXiang. Welcome back. I had update your comments with markdown syntax, which make them easy to read.

I will spend some time on your issue. Thanks for your feedback. :)

**Comment by EdwinXiang** [comment]
The reason has been found. Is caused by the problem of compressed package and compressed resource level.
thanks

**Comment by willson-chen** [comment]
Thanks :)
