### ISSUE TITLE
when i using [SSZipArchive unzipFileAtPath:zipPath toDestination: unzipPath] carsh

### ISSUE THREAD

**Issue by hzw0407** [ZipArchive/ZipArchive#566]
<img width="759" alt="图片" src="https://user-images.githubusercontent.com/25050158/79560629-7c02b700-80da-11ea-9535-64391f342e26.png">
carsh in this line
other info:
SSZipArchive version 2.2.2
Xcode version 11.4.1
iPhone 8 Plus version 13.4.1

**Comment by willson-chen** [comment]
Thanks for your feedback. :)

Could you please post your code to show how you call unzip funciton?

**Comment by willson-chen** [comment]
#362

**Comment by hzw0407** [comment]
thank you ，I have solved this problem。This is due to conflicts with other libraries in the project

**Comment by llesson** [comment]
@hzw0407 how did u solved this problem?
rename the confilt symbols?
