### ISSUE TITLE
Carthage update failed

### ISSUE THREAD

**Issue by tienyuanwu** [ZipArchive/ZipArchive#568]
Hi, my issue is when i run 
**carthage update**
, it shows the following message.

A shell task (/usr/bin/env git fetch --prune --quiet https://github.com/ZipArchive/ZipArchive.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/* (launched in /Users/michael.wu/Library/Caches/org.carthage.CarthageKit/dependencies/ZipArchive)) failed with exit code 1

When i run 
**/usr/bin/env git fetch --prune --quiet https://github.com/ZipArchive/ZipArchive.git refs/tags/*:refs/tags/* +refs/heads/*:refs/heads/***
shows the following message
fatal: Refusing to fetch into current branch refs/heads/master of non-bare repository

**Comment by willson-chen** [comment]
Please pay attention to the release notes:

>Note:
>
>* We stop releasing Carthage package from this version on. It is better for developers to build it by >themselves.

**Comment by willson-chen** [comment]
Hi @tienyuanwu. I will close this issue. More issues are welcome. :)
