### ISSUE TITLE
[SSZipArchive] Failed to set attributes - whilst setting modification date

### ISSUE THREAD

**Issue by ljw215** [ZipArchive/ZipArchive#570]
the method unzipFileAtPath cause  "[SSZipArchive] Failed to set attributes - whilst setting modification date“

**Comment by willson-chen** [comment]
Thanks for your feedback. :)

It seems that the error occured when setting date. Could you please offer the archive file so that we could check if the file is fine?

**Comment by ljw215** [comment]
thanks,the "test8.zip"


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wilson chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 下午2:40
收件人:&nbsp;"ZipArchive/ZipArchive"<ZipArchive@noreply.github.com&gt;;
抄送:&nbsp;"ljw@qq.com"<876107909@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ZipArchive/ZipArchive] [SSZipArchive] Failed to set attributes - whilst setting modification date (#570)





 
Thanks for your feedback. :)
 
It seems that the error occured when setting date. Could you please offer the archive file so that we could check if the file is fine?

**Comment by willson-chen** [comment]
Hi @ljw215. We need the original archive file, not just the name. You could attach it to the comment.

**Comment by ljw215** [comment]
附件里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wilson chen"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 下午3:00
收件人:&nbsp;"ZipArchive/ZipArchive"<ZipArchive@noreply.github.com&gt;;
抄送:&nbsp;"ljw@qq.com"<876107909@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ZipArchive/ZipArchive] [SSZipArchive] Failed to set attributes - whilst setting modification date (#570)





 
Hi @ljw215. We need the original archive file, not just the name. You could attach it to the comment.

**Comment by willson-chen** [comment]
You have to attach the file on GitHub web instead of email. The attachement in reply to the GitHub notification email is unavailable in GitHub web.

**Comment by ljw215** [comment]
我好像知道问题了，压缩包的名称，和要压缩的文件名称要一致
