### ISSUE TITLE
crash at  *error = unzippingError;

### ISSUE THREAD

**Issue by ljw215** [ZipArchive/ZipArchive#571]
![c7460304c64b8292974626f8bbc3cfd9](https://user-images.githubusercontent.com/14038681/82037489-cc1e6a80-96d4-11ea-9c7f-2e86dad93109.JPG)

```
 if (error) {
        if (unzippingError) {
            *error = unzippingError;
        }
        else {
            *error = retErr;
        }
    }

crash at        if (unzippingError) {
            *error = unzippingError;
        }
```

**Comment by willson-chen** [comment]
Hi @ljw215. Thanks for your feedback. :)

Could you please specify your environment? Such as:
* the platform, iOS or macOS?
* platform version
* you archive file
* your code block of call ZipArchive
* if it is easy to reproduce?

**Comment by Coeur** [comment]
no feedback, closing
