### ISSUE TITLE
Warning due to incorrect PRIx64 format specifier in mz_zip.c

### ISSUE THREAD

**Issue by triplef** [ZipArchive/ZipArchive#572]
I am getting the following warning when building for iOS using Xcode 11.4 (it’s an error here due to "treat warnings as errors" being enabled):

```
minizip/mz_zip.c:757:37: error: format specifies type 'unsigned long' but the argument has type 'int64_t' (aka 'long long') [-Werror,-Wformat]
            file_info->disk_number, file_info->disk_offset);
            ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
```

This is the code causing the warning, specifically the `PRIx64` resolving to `%lx` instead of `%llx`:
https://github.com/ZipArchive/ZipArchive/blob/e127449c91f182e112e9ceb26c1c99800b26477f/SSZipArchive/minizip/mz_zip.c#L756-L757

I think `PRIx64` should be resolving to `%llx` to fix the warning, but I am not sure about the best way to fix this.

**Comment by willson-chen** [comment]
Hi @nmoinvaz. Could you please help to check the type `PRIx64`?

**Comment by triplef** [comment]
I think I found the issue and opened a PR to fix this: https://github.com/nmoinvaz/minizip/pull/482

For further context, I was directly adding SSZipArchive to an Xcode project, so that `HAVE_INTTYPES_H` was not defined and the built-in defines were used.

I’m also wondering if it could be using `__has_include()` instead of the HAVE_XXX_H defines. @nmoinvaz is this something you’d accept a PR for? Not sure if compiler support for this feature is prevalent enough for minizip.

**Comment by nmoinvaz** [comment]
@triplef yes I would support a change like that in `mz.h`.

**Comment by triplef** [comment]
This was fixed in https://github.com/zlib-ng/minizip-ng/pull/482, which was also updated here.
