### ISSUE TITLE
Suggest add namespace for minizip

### ISSUE THREAD

**Issue by yanqiw** [ZipArchive/ZipArchive#577]
### Steps to reproduce
Some third part framework may also include zip package, and the function name is same. However, those functions may not include in the header file of those third part framework. 

This causes the bad address issue in runtime, and it's very difficult to define the issue.
In my case, after include the minizip, the app crashed with bad address. Refer to the idea of [362](https://github.com/ZipArchive/ZipArchive/issues/362) , I try to change the below function name with namespace, the issue is solved. 

mz_compat.h
```text
zipOpen -> ZA_zipOpen
zipOpen2 -> ZA_zipOpen2
zipOpen2_64 -> ZA_zipOpen2_64
zipClose -> ZA_zipClose
zipClose_64 -> ZA_zipClose_64
zipClose2_64 -> ZA_zipClose2_64
zipClose_MZ -> ZA_zipClose_MZ
zipClose2_MZ -> ZA_zipClose2_MZ
zipWriteInFileInZip -> ZA_zipWriteInFileInZip
zipCloseFileInZip -> ZA_zipCloseFileInZip
zipCloseFileInZip64 -> ZA_zipCloseFileInZip64
```

### Expected behavior
The zipArchive should manage the minizip namespace within the package scope. 

### Actual behavior
minizip is global defined

### Version of ZipArchive
all version

### Environmental information
ios 13

**Comment by yanqiw** [comment]
If we agree, I can try to change it, and create a shell to do this for minizip upgrade.

**Comment by willson-chen** [comment]
Looks like a good idea. What do you think? @Coeur @jhudsonWA

**Comment by jhudsonWA** [comment]
In general, I don't like to change the code we import because it makes version upgrades of that package harder. We have to remember to apply this change everytime we update minizip.

**Comment by willson-chen** [comment]
@jhudsonWA Yeah, it makes the update more complicate. But is there a better way to resolve the conflict of minizip from other framework? I have encountered this problem before, and have no idea about how to deal with it.

**Comment by Coeur** [comment]
mz_compat is the only file of minizip that is OK to customize because it's a compatibility layer between version 1 and 2 of the framework, that should be abandoned in the long term. So yes, it's fine to rename the functions inside mz_compat (but only that file).

**Comment by willson-chen** [comment]
Hi @yanqiw. PR is welcome.

**Comment by mqlsq** [comment]
> If we agree, I can try to change it, and create a shell to do this for minizip upgrade.

Can you help me to upgrade minizip. I want to solve this issue on Unity project.

**Comment by willson-chen** [comment]
Hi @mqlsq. Any new problems?

**Comment by mqlsq** [comment]
> Hi @mqlsq. Any new problems?
The same problems [https://github.com/ZipArchive/ZipArchive/issues/525](url)

**Comment by willson-chen** [comment]
Hi @mqlsq. Please specify your issues, I hope I could offer some help. Which version of minzip do you want to upgrade to?

**Comment by huuchi207** [comment]
same problem
