### ISSUE TITLE
Can not create zip files larger than 4.3Gb

### ISSUE THREAD

**Issue by joelfischerr** [ZipArchive/ZipArchive#579]
### Steps to reproduce
1. Add files using `- (BOOL)writeData:(NSData *)data filename:(nullable NSString *)filename compressionLevel:(int)compressionLevel password:(nullable NSString *)password AES:(BOOL)aes;` until the archive reaches an expected size of around 5Gb
2. Check the content and size of the archive
3. The archive will be missing some files and the size is 4.3Gb instead of 5Gb

### Expected behavior
All files should be present in the archive, an error should appear, or the behaviour should be documented.

### Actual behavior
Files are missing from the zip archive without any notification of the user.

### Version of ZipArchive
v2.2.3

### Environmental information
Xcode 11.5 and iOS 13.5

What is the expected behaviour here?

**Comment by willson-chen** [comment]
I think the `Expected behavior` here should be `zip the total 5Gb files`.

Thanks for your feedback, we will try to reproduce this issue. :)

**Comment by joelfischerr** [comment]
I have some additional information. The 4.3 Gb i.e. 2^32 bytes seem to be the size limit of the original zip spec [1].

Minizip supports the Zip64 extension to the zip archive format and it can be enabled in this call https://github.com/ZipArchive/ZipArchive/blob/83f367f2bc32cf45adba8115459df18ca942384b/SSZipArchive/SSZipArchive.m#L1143.

I haven't tested this though.

[1] : http://www.artpol-software.com/ziparchive/KB/0610051629.aspx

**Comment by joelfischerr** [comment]
Enabling `zip64` by setting the last parameter to 1 in the function call above fixes the issue for my project. I have only tested a handful of different zip files with Keka on macOS so it might introduce unintended side effects for other projects.

**Comment by rholstad** [comment]
@joelfischerr I have used [ZipKit](https://github.com/kolpanic/ZipKit) instead for supporting files over 2^32 bytes.

**Comment by joelfischerr** [comment]
@rholstad Thanks for the suggestion! But we need AES support.

**Comment by willson-chen** [comment]
Hi @joelfischerr. Thanks for your research on this issue.

Zip64 should be a priority feature. We will add it in the next version.

**Comment by joelfischerr** [comment]
@willson-chen Do you already know when the next version will be released?

**Comment by willson-chen** [comment]
@joelfischerr All the committers are all kind of busy recently. If you create the PR, I am willing to review and merge it, which will accelerate the new version release. :)

**Comment by joelfischerr** [comment]
It looks like the change mentioned in https://github.com/ZipArchive/ZipArchive/issues/579#issuecomment-651699932 was the only change required. I have opened a PR at #580
