### ISSUE TITLE
can not unzip xxx.7z format file

### ISSUE THREAD

**Issue by tangdanfeng88** [ZipArchive/ZipArchive#582]
can not unzip xxx.7z format file

**Comment by willson-chen** [comment]
Yes, we are `ZipArchive` so it only supports `zip` format right now. ZipArchive is a wrapper of [minizip](https://github.com/nmoinvaz/minizip), which only supports zip, so that ZipArchive will never support 7z format. :)

**Comment by willson-chen** [comment]
Hi @tangdanfeng88 . I will close this issue, and will reopen it if you have more question.
