### ISSUE TITLE
Provide progress handler for + (BOOL)createZipFileAtPath:withFilesAtPaths:withPassword:

### ISSUE THREAD

**Issue by fritzt0** [ZipArchive/ZipArchive#583]
The class function + (BOOL)createZipFileAtPath:withFilesAtPaths:withPassword: does not provide a means to track or visualize progress.

I added a function + (BOOL)createZipFileAtPath:withFilesAtPaths:withPassword:progressHandler: to fill that gap.

Please see pull request: https://github.com/ZipArchive/ZipArchive/pull/578

Best, Fritzt

**Comment by jhudsonWA** [comment]
#578 has been merged in. Thank you for your PR.
