### ISSUE TITLE
App Crashed when create zip file, EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jeff77731** [ZipArchive/ZipArchive#584]
<img width="1331" alt="截圖 2020-08-06 10 37 10" src="https://user-images.githubusercontent.com/4278332/89484553-573d6700-d7d1-11ea-9f32-1257ad995309.png">

Xcode: 11.6
iOS: 13.6

**Comment by willson-chen** [comment]
Hi @jeff77731. Thanks for you feedback. Could you please specify how to reproduce this issue? We need more information. :)

**Comment by jeff77731** [comment]
hmm...seems my iPhone's problem, it never happened after I restart my iPhone

**Comment by willson-chen** [comment]
thanks bud :)

**Comment by alwaysblue3** [comment]
I have the same problem

**Comment by JohnyLisir** [comment]
I have the same problem
Xcode：13.2
iOS：15.2

**Comment by venu-nuncsys** [comment]
> I have the same problem Xcode：13.2 iOS：15.2 pod 'SSZipArchive', '~> 2.4.3' ![截屏2022-03-03 上午10 54 27](https://user-images.githubusercontent.com/16588594/156487414-b452bfb9-82bf-460e-90af-06e94d1b2363.png)

@JohnyLisir Did you resolve this issue, am getting the same issue in
Xcode 15.0.1 and checked with multiple versions pod 'SSZipArchive', '~> 2.4.3' and pod 'SSZipArchive', '~> 2.5.5'

**Comment by Coeur** [comment]
Not that I can do much, but best to create a new issue for visibility instead of discussing on a closed issue?
