### ISSUE TITLE
Cannot build on Xcode 12/iOS 14

### ISSUE THREAD

**Issue by HaikuOezu** [ZipArchive/ZipArchive#590]
I'm trying to build an iPad app that was previously working just fine, but despite integrating the latest version through CocoaPods (by specifying the git repo and branch) I'm greeted with a huge amount of errors in SSZipCommon.h

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/814403/93946205-f219e280-fd38-11ea-948f-bef371ee836d.png">

I'm not sure what to do about this, is this a known issue?

**Comment by dstop75** [comment]
Fixed for me by updating to 2.2.3, pod install and clean the build folder.

**Comment by dstop75** [comment]
I spoke too soon, seemed like it was fixed for me but it came back, don't know what to do.

**Comment by Coeur** [comment]
Typically you have either multiple dependencies using different versions of minizip, or you need to clear your DerivedData folder.

I believe it's the first case (multiple Pods using different versions of minizip).

**Comment by dstop75** [comment]
Good hint, thanks. Looks like SSZipArchive 2.2.2 brings in minizip 2.8.7 and defines for example unz_global_info_s in SSZipCommon.h:
```
typedef struct unz_global_info_s
{
    uint32_t number_entry;          /* total number of entries in the central dir on this disk */
    uint32_t number_disk_with_CD;   /* number the the disk with central dir, used for spanning ZIP */
    uint16_t size_comment;          /* size of the global comment of the zipfile */
} unz_global_info;
```

But another pod I'm using uses Zip which brings in minizip 1.1 and defines unz_global_info_s in unzip.h:
```
typedef struct unz_global_info_s
{
    uLong number_entry;         /* total number of entries in the central dir on this disk */
    uLong number_disk_with_CD;  /* number the the disk with central dir, used for spanning ZIP*/
    uLong size_comment;         /* size of the global comment of the zipfile */
} unz_global_info;
```

So the types (uint32_t, uLong) don't match (along with others).

Any thoughts on why this issue doesn't appear in Xcode < 12? Any suggestions for how to resolve this in Xcode 12?

**Comment by Coeur** [comment]
Maybe related to the change in the #import <> made recently in #588:
>* Fixed Quoted Brackets xcode 12 warning
I don't think it's Xcode 12 specific: if you switch back to Xcode 11, you'd probably have the same issue.

As a temporary fix, you may try to configure you Podfile to pull the code from the previous commit (546b99c5c0f7e0c5761960c8ffd486f2ef7610d7).
As a long term fix, you can check with @ddaddy and @willson-chen or abandon the pod that is using Zip 1.1.0 since that old minizip 1.1 has security issues if I remember correctly.

**Comment by HaikuOezu** [comment]
> Maybe related to the change in the #import <> made recently in #588:
> 
> > * Fixed Quoted Brackets xcode 12 warning
> 
> I don't think it's Xcode 12 specific: if you switch back to Xcode 11, you'd probably have the same issue.
> 
> As a temporary fix, you may try to configure you Podfile to pull the code from the previous commit ([546b99c](https://github.com/ZipArchive/ZipArchive/commit/546b99c5c0f7e0c5761960c8ffd486f2ef7610d7)).
> As a long term fix, you can check with @ddaddy and @willson-chen or abandon the pod that is using Zip 1.1.0 since that old minizip 1.1 has security issues if I remember correctly.

Hmmm I'm confused, what other pod I should be using? The README only mentions 'SSZipArchive'

**Comment by ddaddy** [comment]
Your project really shouldn't have 2 different versions of the same framework (minizip 1.1 & 2.8.7).
I believe this might be one of the reasons Apple decided to switch on the "Quoted imports" compiler warning, to catch this.
The framework that is importing minizip 1.1 should really be updated. If the author can't update it, then fork the repo and update it yourself to use minizip 2.8.7

**Comment by dstop75** [comment]
Everything you're saying makes sense. Just sharing info:

The project does compile in Xcode 11, but not in Xcode 12. 🤷

The "Quoted imports" compiler warning still seems to be off, from what I see in the Xcode UI. Toggling the setting from NO -> YES -> NO adds an explicit setting `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = NO` in .xcodeproj/project.pbxproj, but it doesn't help.

The framework importing minizip 1.1 in my project is closed source, but I've asked for an update. 🤞

**Comment by HaikuOezu** [comment]
> Your project really shouldn't have 2 different versions of the same framework (minizip 1.1 & 2.8.7).
> I believe this might be one of the reasons Apple decided to switch on the "Quoted imports" compiler warning, to catch this.
> The framework that is importing minizip 1.1 should really be updated. If the author can't update it, then fork the repo and update it yourself to use minizip 2.8.7

I'm not sure wether you're talking to me or not, but I don't think my project has two versions of the same framework
This is all the pods I'm using

```
pod 'Alamofire', '~> 4.8.2'
pod 'AlamofireObjectMapper' 
pod 'CSV.swift'
pod 'M13ProgressSuite', '~> 1.2'
pod 'SDWebImage', '~> 5.0'
pod 'VerticalSlider'
pod 'SSZipArchive', :git => 'https://github.com/ZipArchive/ZipArchive.git', :branch => 'master'
pod 'Drawsana', :git => 'https://github.com/Asana/Drawsana.git', :branch => 'master'
```
