### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by rafagan** [ZipArchive/ZipArchive#591]
There is any prediction about Swift Package Manager support in this lib?

**Comment by pitoneux** [comment]
Any update on this ?

**Comment by paulja** [comment]
Is this project still under development? No commits for 9 months now and no releases for over a year 😢

**Comment by halmueller** [comment]
There was a PR merged a month ago.

**Comment by jhudsonWA** [comment]
Development has considerably slowed as the maintainers have gotten busy with real-life work over the last year/year & a half.  I'll review the SPM issue and related PRs soon. If folks would like to join the maintainer's team and have time to dedicate I'd love to have a discussion. Usually, we add folks based on their PRs and contributions.

**Comment by paulja** [comment]
> Development has considerably slowed as the maintainers have gotten busy with real-life work over the last year/year & a half. I'll review the SPM issue and related PRs soon. If folks would like to join the maintainer's team and have time to dedicate I'd love to have a discussion. Usually, we add folks based on their PRs and contributions.

Thanks for taking the time to feedback on the current state of play. We're all developers here and we know how the real-world can sometimes get the way of our passion projects. Thanks for looking at SPM integration sooner rather than later, personally, I know it is something that will really help me out and make my life much easier managing my own projects. Thanks. —Paul

**Comment by jhudsonWA** [comment]
SPM support merged into master. Thank you for your patience. Let me know how it works for you and if a new version needs to be created to make this work.

**Comment by Coeur** [comment]
A new "pod" isn't strictly needed to support SPM, Joshua. But it could be nice nonetheless for whatever fixes were added in the past year. At a minimum, an update of minizip could be worth a new release of ZipArchive.

**Comment by sweetppro** [comment]
Im getting this build error:

~/Library/Developer/Xcode/DerivedData/eMail_Address_Extractor-evyooqjgeaizdgetfuphuvnhnjes/SourcePackages/checkouts/ZipArchive/SSZipArchive/include/SSZipArchive.h:17:9: 'ZipArchive/SSZipCommon.h' file not found

**Comment by jhudsonWA** [comment]
> A new "pod" isn't strictly needed to support SPM, Joshua. But it could be nice nonetheless for whatever fixes were added in the past year. At a minimum, an update of minizip could be worth a new release of ZipArchive.

Thanks, I'll update then version bump.

**Comment by jhudsonWA** [comment]
> Im getting this build error:
> 
> ~/Library/Developer/Xcode/DerivedData/eMail_Address_Extractor-evyooqjgeaizdgetfuphuvnhnjes/SourcePackages/checkouts/ZipArchive/SSZipArchive/include/SSZipArchive.h:17:9: 'ZipArchive/SSZipCommon.h' file not found

Using SPM? There should be no ZipArchive/SSZipCommon.h, it would have been moved to ZipArchive/include/SSZipCommon.h

**Comment by Coeur** [comment]
(I would recommend, sweetppro, to create a new distinct issue if you're still encountering a problem after clearing your DerivedData)

**Comment by sweetppro** [comment]
it's still failing after clearing DerivedData.
I was actually using a fork previously without issues, and it builds fine with the following relative imports:
SSZipArchive/include/SSZipArchive.h:17
`#import < SSZipCommon.h >`

also in
SSZipArchive/include/ZipArchive.h:22
`#import <SSZipArchive.h>"
