### ISSUE TITLE
Issue with compressing a folder

### ISSUE THREAD

**Issue by brandonplank** [ZipArchive/ZipArchive#595]
### Steps to reproduce
1. On Big Sur
2. Call [SSZipArchive createZipFileAtPath:temp_path withContentsOfDirectory:payload_dir keepParentDirectory:true] in the App Support folder
3. Returns error, and does not create a zip.
                |-----Error code                    |----Function
ASSERT(21:[SSZipArchive createZipFileAtPath:temp_path withContentsOfDirectory:payload_dir keepParentDirectory:true])@patcher.m:135[patch_ipa]

### Expected behavior
Should have crated a zip

### Actual behavior
Returns error code 21

### Version of ZipArchive
Latest

**Comment by Coeur** [comment]
We have a unit test for that: `testZippingAndUnzippingEmptyDirectoryWithPassword`
https://github.com/ZipArchive/ZipArchive/blob/4b4cccf56923c554f08c1554b1480821706c2000/Example/ObjectiveCExampleTests/SSZipArchiveTests.m#L487-L488

So I'll close as too few informations to reproduce (or it has already been fixed).
