### ISSUE TITLE
Password not matching while unzipping 

### ISSUE THREAD

**Issue by sz-ashik440** [ZipArchive/ZipArchive#601]
### Steps to reproduce
I have tried to make zip file with password protection. Zip creation succeeded but while unzipping the password is not matching anymore. I have tried to unzip with Finder on macOS Catlina(version 10.15.6) but still no luck

```
let url = getDocumentsDirectory().appendingPathComponent("log.txt")
try fileBody.write(to: url, atomically: true, encoding: .utf8)
let zipURL = self.getDocumentsDirectory().appendingPathComponent("log.zip")
 SSZipArchive.createZipFile(atPath: zipURL.absoluteString, withFilesAtPaths: [url.absoluteString], withPassword: "123")
```

### Environmental information
SSZipArchive: 2.2.3
Swift version: 5.2
Xcode version: 12.2 (12B45b)
Tested On: iPhone X(iOS 14.0.1), iPhone 6s Plus(13.4.1)

**Comment by joelfischerr** [comment]
SSZipArchive uses AES encryption by default. But Finder or the standard Apple unarchiver does not support AES. The archive should open just fine with something like The Unarchiver or Keka.

Does it also fail if you unzip it again with SSZipArchive?

If you want to disable AES, you can do that by using a method like the one below and setting AES to false.

```
+ (BOOL)createZipFileAtPath:(NSString *)path
    withContentsOfDirectory:(NSString *)directoryPath
        keepParentDirectory:(BOOL)keepParentDirectory
           compressionLevel:(int)compressionLevel
                   password:(nullable NSString *)password
                        AES:(BOOL)aes
            progressHandler:(void(^ _Nullable)(NSUInteger entryNumber, NSUInteger total))progressHandler;
```

**Comment by sz-ashik440** [comment]
Thanks, I have disable AES. Now its works for Finder.
But Keka also failed to extract file if AES is enabled. It throws `Error code 2 using "p7zip"`
