### ISSUE TITLE
it will crash when you unzip zip files

### ISSUE THREAD

**Issue by Lemontree7137** [ZipArchive/ZipArchive#602]
### Steps to reproduce
it crashes when unzipping the zip file

### Actual behavior
![image](https://user-images.githubusercontent.com/13774783/102482428-2124c380-409e-11eb-8cf1-e9c0984406a8.png)

### Version of ZipArchive
v2.2.3

### Environmental information
XCode 11.7 
iPhone 11
iOS 13.7

**Comment by JoaoManaroulas** [comment]
Same problem here. Happening on a real device, iPad Mini with iOS 14.2.
When trying to decompress a 250MB file, it crashes near the end all the time.
Smaller files seem to have no problem.

The same big file on an real iPhone 12 doesn't crash.

**Comment by arinjay** [comment]
Having a similar issue for the last 1 month.
Not able to reproduce the issue. Tried unzipping the small file, large file (50 MB size), switching from background, foreground mode.

iOS version - all iOS 14+
Device - not specific to a device

**Comment by Coeur** [comment]
I don't see anything from this code that could cause EXC_BAD_ACCESS.
Our unit tests don't reproduce the issue.

Kindly attach an archive that can reproduce the issue.

**Comment by Coeur** [comment]
From the duplicate issue (#605):
>Crash was happening because of stack corruption due to unzGetCurrentFileInfo function call.

So I'll tag this as Minizip.

SSZipArchive 2.2.3 was using minizip-ng 2.9.2 and we're now at minizip-ng 4.0.7 on main ZipArchive branch, so hopefully it has been resolved.

**Comment by Coeur** [comment]
Also duplicate of #362:
You were maybe using two incompatible versions of minizip together.
