### ISSUE TITLE
iOS deployment target  is set to 8.0, but ... Warning

### ISSUE THREAD

**Issue by multitudes** [ZipArchive/ZipArchive#609]
### Steps to reproduce
1.  add pod 'SSZipArchive' to pod file. 
2. Compile
3. see warning

### Expected behavior
No warning

### Actual behavior
The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99.

### Version of ZipArchive
2.2.3

### Environmental information
Mac Big Sur, Xcode 12.5

This would be an easy fix!
Thanks!

**Comment by Coeur** [comment]
I dropped iOS 8 support on purpose in 2019: #531.
I believe that the warning is coming from either your Podfile targeting iOS 8, or your xcodeproj targeting iOS 8.

**Comment by Coeur** [comment]
Also, be aware that there may be a bug in CocoaPods itself:
https://github.com/CocoaPods/CocoaPods/issues/7314

**Comment by multitudes** [comment]
Thanks for taking care of this, I am running iOS 12 but will check again the pods

**Comment by Coeur** [comment]
Also, sometimes, `pod deintegrate && pod install` will fix some old configurations.
