### ISSUE TITLE
Missing '#include "SSZipArchive.h"'; 'SSZipArchive' must be defined before it is used

### ISSUE THREAD

**Issue by lijiaxiang** [ZipArchive/ZipArchive#614]
### Steps to reproduce
1. pod 'SSZipArchive', '2.4.0'
2. pod install/update
3. build project

### Expected behavior
build Success, but  not now

### Actual behavior
Missing '#include "SSZipArchive.h"'; 'SSZipArchive' must be defined before it is used

### Version of ZipArchive
```
  pod 'SSZipArchive', '2.4.0'
```

**Comment by jhudsonWA** [comment]
@Coeur Thanks... Working on it now.

**Comment by jhudsonWA** [comment]
Fixed in 2.4.1. Sorry about that. SPM support stepped on cocoapods. I thought it was well tested, but alas.

**Comment by lijiaxiang** [comment]
> Fixed in 2.4.1. Sorry about that. SPM support stepped on CocoaPods. I thought it was well tested, but alas.

Thank you very much.

best wishes
