### ISSUE TITLE
pod lib or pod repo push Error 

### ISSUE THREAD

**Issue by wyxuan** [ZipArchive/ZipArchive#615]
- ERROR | [iOS] xcodebuild:  SSZipArchive/SSZipArchive/include/SSZipArchive.h:14:9: error: 'SSZipCommon.h' file not found with <angled> include; use "quotes" instead

It used to be fine.

**Comment by jhudsonWA** [comment]
Thanks... Working on it now.

**Comment by jhudsonWA** [comment]
Fixed in 2.4.1. Sorry about that. SPM support stepped on cocoapods. I thought it was well tested, but alas.
