### ISSUE TITLE
Can we have zip64 as a parameter during zipping?

### ISSUE THREAD

**Issue by nick3389** [ZipArchive/ZipArchive#619]
Hello,

zip64 format creates some problems in our backend during the manipulation of the zip file when I upload it in our backend system. It seems that this format creates a problem and the parsing of the file throws an exception. This happens since v2.4.0. So I am wondering if it is feasible to have this as a parameter, global or local.

Thank you!

**Comment by Coeur** [comment]
I changes zip64 logic to be "AUTO": it will only use zip64 when the size needs it.
