### ISSUE TITLE
Only 22B after compression (压缩完成后只有22B)

### ISSUE THREAD

**Issue by 597579501** [ZipArchive/ZipArchive#621]
### Steps to reproduce
Only 22B after successful compression (压缩成功后只有22B)

![image](https://user-images.githubusercontent.com/6228678/123066309-850bb880-d442-11eb-99b2-68d73e07632e.png)
![image](https://user-images.githubusercontent.com/6228678/123066360-9228a780-d442-11eb-86e6-2bb027729930.png)

**Comment by Coeur** [comment]
Est-ce un souci avec le `compressionLevel:-1` ? (oui, je réponds en français, vu que c'était demandé en chinois)

**Comment by Coeur** [comment]
`compressionLevel:-1` is supported, as shown by our sample Example app:
https://github.com/ZipArchive/ZipArchive/blob/738a6b8bcb08bd107e38d3e7e5bd337632298e28/Example/SwiftExample_macOS/ViewController.swift#L55-L61

**Comment by Coeur** [comment]
I reproduced the issue:
If we pass a filePath instead of a directoryPath to `withContentsOfDirectory:`, it will incorrectly return a success.
