### ISSUE TITLE
zip archive cannot be read using Java's ZipInputStream

### ISSUE THREAD

**Issue by stefaneberl** [ZipArchive/ZipArchive#622]
### Steps to reproduce
1. Create a zip file using `[SSZipArchive createZipFileAtPath:zipPath withFilesAtPaths:@[crashPath]];`
2. Try to uncompress the resulting zip file using Java's built-in `ZipInputStream`.

### Details
* Compression method is deflate.
* Local file header flags indicates the presence of a data descriptor (bit 3 is set to 1)
  * According to spec, if data descriptor is present, the CRC-32, compressed size, uncompressed size in the local file header are set to zero
  * Instead, compressed size and uncompressed size in local file header indicate ZIP64 extension
* Data descriptor is present, but the uncompressed size is 0 in there
  * Compressed size and CRC-32 are however correct in the data descriptor

### Suggested fix
* Do not use ZIP64 extension, if not necessary (uncompressed size is ~200KB in my case), and only use data descriptor in this case.
* Or: do not use a data descriptor and only use the ZIP64 extension

**Comment by nick3389** [comment]
@stefaneberl I think your issue is relevant to mine. Check here: #619

**Comment by temkich** [comment]
I have the same problem. Have you found a solution?

**Comment by andrewdewaal** [comment]
This is an issue for us as well; is there a workaround or a fix in progress? Thanks very much!

**Comment by silverhammermba** [comment]
Downgrade to 2.2.3 to work around this issue.

**Comment by Coeur** [comment]
There is a proposed fix here: #640

**Comment by Coeur** [comment]
Fixed in #726.
