### ISSUE TITLE
mz_compat.h/c out of sync with minizip-ng

### ISSUE THREAD

**Issue by triplef** [ZipArchive/ZipArchive#623]
We would like to use ZipArchive with our own minizip build that we have already configured for our project. However, it seems that while the bundled minizip-ng is generally up-to-date, the `mz_compat.h/c` files are outdated (outside of the ZipArchive-specific changes).

The main problem is that the `unz_file_info64_s` struct gained another field upstream, which is not yet reflected in ZipArchive, and which makes ZipArchive binary-incompatible with other minizip-ng installations (even the same version):
https://github.com/zlib-ng/minizip-ng/commit/ce26dba5bafae49e92d31bd1a0ef10e09bb763bb#diff-c22d376981028523d588652dec8666d3608a9ec76a6065f6a3898331a895f51cR204

I realize this is not a standard or even supported setup, but I would nonetheless appreciate if these files could be updated to match the upstream implementation. Please let me know if this would be ok and I’d be happy to try to put together a PR for this.

**Comment by jhudsonWA** [comment]
I'm happy to review a PR if submitted. As long as compatibility is maintained for older archives.

**Comment by triplef** [comment]
We ended up writing our own smaller wrapper around minizip, so this is no longer an issue for us.

I also saw that mz_compat.c/h was not updated with the latest minizip update (https://github.com/ZipArchive/ZipArchive/pull/613), so I guess that this is a conscious decision.
