### ISSUE TITLE
zip压缩包路径,经过几次方法调用变成了 nil 

### ISSUE THREAD

**Issue by to-explore-future** [ZipArchive/ZipArchive#631]
![Snip20211208_6](https://user-images.githubusercontent.com/21005045/145138958-aa05b057-c42b-4fac-89d9-ef053860fd10.png)

![Snip20211208_7](https://user-images.githubusercontent.com/21005045/145138998-0bcba879-ffbb-4247-a28a-ca93caae7eaa.png)

![Snip20211208_8](https://user-images.githubusercontent.com/21005045/145139556-46af9617-b46f-40f2-a6ee-d99dbcef2d1b.jpg)

![Snip20211208_9](https://user-images.githubusercontent.com/21005045/145139637-2ee6990a-0e34-402a-96bb-87f3c781075c.png)

**Comment by jhudsonWA** [comment]
Can you submit a test project that shows the issue? Plus details on how you integrated the library?
