### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rastaman111** [ZipArchive/ZipArchive#632]
Hey!  How can I unzip files in the CBR, CBZ, CB7, CBT format, this is a comic format, when I try to do it it gives an error, I also tried to change the extension to ZIP and also gives an error that it cannot unzip.  What do I need to do?

**Comment by jhudsonWA** [comment]
This library is made to support standard zip files. It "may" be able to do CBZ as that is stored as zip in my research but it is not tested.
