### ISSUE TITLE
Xcode Package resolution failed. ZipArchive could not be resolved.

### ISSUE THREAD

**Issue by berzzani** [ZipArchive/ZipArchive#634]
### Steps to reproduce
1. add SPM to project referencing https://github.com/ZipArchive/ZipArchive.git
2.  Package resolution failure shows:
![zip spm issue](https://user-images.githubusercontent.com/66145809/153491091-706b8dd2-313d-4234-9b92-b8dc8c6e634d.png)

### Expected behavior
 Package resolution should not fail

### Actual behavior
![zip spm issue](https://user-images.githubusercontent.com/66145809/153491091-706b8dd2-313d-4234-9b92-b8dc8c6e634d.png)

### Version of ZipArchive
current

### Environmental information
Xcode Version 13.2.1 (13C100)

**Comment by KoichiroKAMADA** [comment]
+1

**Comment by jhudsonWA** [comment]
I'm not sure why it's trying to find old versions that existed before there was SPM support. That seems like a regression in XCode 13, but working on it. 

But you can add it by doing branch master, or calling out a version > 2.3 which added SPM.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/702446/154083594-0b291c59-e892-4769-8e91-f306ede51740.png">

**Comment by jhudsonWA** [comment]
Was an issue with tag names and what SPM expected. recreated the tag for 2.4.2 and now it picks the correct "major" version 2 vs 0.2.3. 

Thanks for the heads up!

**Comment by theohdv** [comment]
Hey @jhudsonWA ,

We got this problem just right now in our project, could it be related to what you've just done ?

```
 > Git download
     $ /usr/local/bin/git clone https://github.com/ZipArchive/ZipArchive.git /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/d20220215-2613-1nb8e6 --template= --single-branch --depth 1 --branch v2.2.3
     Cloning into '/var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/d20220215-2613-1nb8e6'...
     warning: Could not find remote branch v2.2.3 to clone.
     fatal: Remote branch v2.2.3 not found in upstream origin

[!] Error installing SSZipArchive
[!] /usr/local/bin/git clone https://github.com/ZipArchive/ZipArchive.git /var/folders/bl/wbxjgtzx7j5_mjsmfr3ynlc00000gp/T/d20220215-2613-1nb8e6 --template= --single-branch --depth 1 --branch v2.2.3
```

**Comment by jhudsonWA** [comment]
Could be. Try now. I can probably keep the old tag names for anything 2.0 - 2.4 as well.

**Comment by theohdv** [comment]
It works, thanks !
