### ISSUE TITLE
Please restore old version branches

### ISSUE THREAD

**Issue by grant-mccarriagher** [ZipArchive/ZipArchive#635]
It seems that older version branches were deleted along with the readme bump to the min version of the package that should be used. 

This breaks CI for projects that use this package, especially if they're using other Pods that depend on this package (Cocoapods _only_ supports version branches when specifying a dependency in a podspec). In this case, projects have no recourse other than waiting for updates from those other packages.

**Comment by jhudsonWA** [comment]
Yep, got a little enthusiastic with some cleanup. They should all be restored.
