### ISSUE TITLE
Getting error while adding this library using cocoapod

### ISSUE THREAD

**Issue by ncomo11** [ZipArchive/ZipArchive#636]
### Steps to reproduce
1. Add 'pod 'SSZipArchive', '~> 2.4.3'' in podfile
2. Execute 'pod install' from terminal
3. Below error will occur:
                `[!] An unexpected version directory `include` was encountered for the `/Users/praveen/.cocoapods/repos/ziparchive-ziparchive/SSZipArchive` Pod in the `SSZipArchive` repository.`

### Expected behavior
SSZipArchive should get install without any error.

### Actual behavior
Error through about the include directory exists

### Version of ZipArchive
I am trying to install version: 2.4.3

### Environmental information
Mac OSx: 11.6.4
cordova: 10.0.0
cordova-ios: 6.2.0
pod version: 1.11.3

### Podfile Content:
-----------------
```
source 'https://github.com/ZipArchive/ZipArchive.git'
platform :ios, '11.0'
use_frameworks!
target 'Zip Test App' do
	project 'ZipTestApp.xcodeproj'
	pod 'SSZipArchive', '~> 2.4.3'
end
```
------------------

**Comment by ncomo11** [comment]
Also I am not able to add this manually and that is the reason I tried adding it using cocoa pod but this also has issue as stated above

**Comment by ncomo11** [comment]
I tried deleting the 'include' folder but then i started bellow below error:
`[!] An unexpected version directory `minizip` was encountered for the `/Users/venkatavemula/.cocoapods/repos/ziparchive-ziparchive/SSZipArchive` Pod in the `SSZipArchive` repository.`

Not sure how to fix this, I just followed the documentation to add this library.

**Comment by ncomo11** [comment]
After removing minizip i am gertting below:
`[!] Unable to find a specification for `SSZipArchive (~> 2.4.3)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.`

**Comment by ncomo11** [comment]
When i tried adding libraries manually I get below error:
`Undefined symbol: _OBJC_CLASS_$_SSZipArchive`

**Comment by haripacewisdom** [comment]
@ncomo11 did you solve this issue! stuck this issue in 3 days

**Comment by Coeur** [comment]
Since we have an Example folder which relies on cocoapods:
https://github.com/ZipArchive/ZipArchive/tree/main/Example

I'm pretty sure that the cocoapods specs are fine (and more so because we were successfully able to make newer releases of the specs). You'd need to ask to the CocoaPods team if you still face issues.
