### ISSUE TITLE
Crash: unzipFileAtPath:toDestination:preserveAttributes

### ISSUE THREAD

**Issue by agan112** [ZipArchive/ZipArchive#637]
### Steps to reproduce

Hello, when we downloading , it sometimes crash.

_$s7XCamera12UnZipManagerC02unC04path11destination16progressCallback8finishedySS_SSySd_SStcSgySSSg_SSs5Error_pSgtcSgtFySdcfU_ (<compiler-generated>:0)

_$s7XCamera12UnZipManagerC02unC04path11destination16progressCallback8finishedySS_SSySd_SStcSgySSSg_SSs5Error_pSgtcSgtFySdcfU_ (UnZipManager.swift:82)

_$s7XCamera14UnZipOperationC4mainyyFyyXEfU_ySS_So15unz_file_info_sVS2itcfU_ (UnZipOperation.swift:75)

_$sSSSo15unz_file_info_sVS2iIeggyyy_So8NSStringCABS2iIeyByyyy_TR (<compiler-generated>:0)

+[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:nestedZipLevel:password:error:delegate:progressHandler:completionHandler:] (SSZipArchive.m:0)

+[SSZipArchive unzipFileAtPath:toDestination:preserveAttributes:overwrite:password:error:delegate:progressHandler:completionHandler:] (SSZipArchive.m:281)

+[SSZipArchive unzipFileAtPath:toDestination:progressHandler:completionHandler:] (SSZipArchive.m:257)

### Version of ZipArchive
2.4.2

**Comment by Coeur** [comment]
This does not offer enough informations to identify the issue you're encountering.
Could you share some of those:
- the crash logs
- the zip file with the crash
- eventually the code being used, since it could be a crash related to your own `completionHandler`.

**Comment by dmantryingcode** [comment]
Hi got it ok let me try
