### ISSUE TITLE
is support ios 14.0 ?

### ISSUE THREAD

**Issue by PopFisher** [ZipArchive/ZipArchive#646]
is support ios 14.0 ?

**Comment by Coeur** [comment]
Support for 14.x was dropped in ZipArchive 2.5.0, for security reasons (See #639). If you need 14.x support, stay on the previous version of ZipArchive, but no support will be given.

**Comment by PopFisher** [comment]
Which version does it support 14.x? I can't find it in the history

**Comment by jhudsonWA** [comment]
Any version prior to 2.5.0. But that statement is as much as I'm willing to offer up.
