### ISSUE TITLE
No such module 'SSZipArchive'

### ISSUE THREAD

**Issue by daver234** [ZipArchive/ZipArchive#648]
### Steps to reproduce
1. I was using pod 'SSZipArchive' in my Podfile.  I deleted this reference
2. I added ZipArchive to Swift Package Manager with https://github.com/ZipArchive/ZipArchive.git
3. Now I get the "No such model SSZipArchive" in files in my project where I had imported SSZipArchive

However, it looks like it works if I change my file import to ZipArchive from SSZipArchive.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Environmental information
Xcode 13.4.1
macOS 12.4

**Comment by jhudsonWA** [comment]
Just for reference for future folks, the namespace does change when switching from pods to SPM. This is due to the name of this GitHub project dropping the SS prefix of earlier contributors to be a simpler name. We didn't change the pods information to maintain compatibility.
