### ISSUE TITLE
Global namespace conflict

### ISSUE THREAD

**Issue by daver234** [ZipArchive/ZipArchive#649]
### Steps to reproduce
1. I have SDK in my project that imports it's own Swift Packages.  One of them is https://github.com/marmelroy/Zip
2. That Zip repo includes minizip and a header unzip with a struct in the global namespace of typedef struct unz_file_info_s
3. This struct is the same name found in the global namespace in SSZipCommon.
4. As such, I am getting build errors like: 'unz_file_info_s::tmu_date' from module 'Minizip' is not present in definition of 'struct unz_file_info_s' in module 'ZipArchive'.

I guess this is only partially a name space issue.  It is implementation also since the error says tmu_date is not implemented in struct unz_file_info_s.

Would you happen to have any suggestions about how to resolve this?  Thanks.

### Expected behavior
No conflicts

### Actual behavior
Conflicts

### Version of ZipArchive
Master

### Environmental information
Xcode 13.4.1

**Comment by Coeur** [comment]
tmu_date is being added soon in ZipArchive 2.5.1 according to this PR: #647

**Comment by daver234** [comment]
I have found a way to resolve this.
