### ISSUE TITLE
Lock screen crash

### ISSUE THREAD

**Issue by shenyuanluo** [ZipArchive/ZipArchive#650]
### Steps to reproduce
1. Start archive big file(about 7 GB), CPU usage about 95%
2. lock screen 
3. Crash after about 1 minute ("Message from debugger: **Terminated due to signal 9**")

### Expected behavior
I hope it can still be used after the screen is locked

### Actual behavior
Crash after about 1 minute

### Version of ZipArchive
v2.4.3

### Environmental information
iOS-14.2

**Comment by jhudsonWA** [comment]
I'll leave this open in case others choose to help, but version 2.4.3 and older operating systems are no longer supported. See the readme for details.

**Comment by Coeur** [comment]
Did you try to create the file on the UI thread or on a dedicated separate thread?
Did you use a background task for doing the heavy work?
https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/using_background_tasks_to_update_your_app
