### ISSUE TITLE
error build: The package product 'ZipArchive' requires minimum platform version 15.5 for the iOS platform, but this target supports 11.0

### ISSUE THREAD

**Issue by mohsulthana** [ZipArchive/ZipArchive#655]
While trying out ZipArchive latest version with Xcode 14.0 (14A309), SPM fetches all the dependencies correctly, but when building, I am getting the following error:

`Error build: The package product 'ZipArchive' requires a minimum platform version of 15.5 for the iOS platform, but this target supports 11.0.`

Meanwhile, I already set the minimum platform to version 15.6 for iOS.
My dependency specification is as follows:

`.package(name: "ZipArchive", url: "https://github.com/ZipArchive/ZipArchive.git", from: "2.3.0")`

**Comment by Fonceur** [comment]
That minimum requirement kills backward compatibility for all applications using ZipArchive... Can't you keep a lower minimum requirement, and devices with access to a newer version of zlib will be using it anyway?

**Comment by jhudsonWA** [comment]
Sorry, all versions prior to 15.5 use a version of zlib that has a known vulnerability. We will not support versions with know vulnerabilities. You are free to use an earlier version of ZipArchive but know you do so without support.
