### ISSUE TITLE
After compressing the Unix executable file, Use the system decompression,  it will become a normal file

### ISSUE THREAD

**Issue by Shellylang** [ZipArchive/ZipArchive#657]
### Steps to reproduce
1. SSZipArchive.createZipFile("zip path", "executable file path")

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

check posixPermissions 775 became 644

### Version of ZipArchive
SSZipArchive 2.4.2

### Environmental information
macos 12.0

**Comment by Coeur** [comment]
Analysis done in #689.
Fix in #716.

I'll close it as duplicate of #689, even if your issue is older. But thanks for reporting it.
