### ISSUE TITLE
some files are lost after unzip package

### ISSUE THREAD

**Issue by AndreHu88** [ZipArchive/ZipArchive#660]
### Steps to reproduce
 use  follow api unzip package
   BOOL result = [SSZipArchive unzipFileAtPath:decPath toDestination:filePath];

### Expected behavior
Tell us what should happen
some files are lost after unzip package
![image](https://user-images.githubusercontent.com/18731383/205278382-8e755947-131d-4867-a1db-e9918303eaa0.png)

### Actual behavior
Tell us what happens instead

### Version of ZipArchive
  pod 'SSZipArchive', '~> 2.2.2'

### Environmental information
iPhone 13

**Comment by Coeur** [comment]
Our unit tests do not reproduce such issue.
Closing for lack of sample archive that reproduces the issue.
We can reopen this and hopefully fix it if you attach a problematic archive.
