### ISSUE TITLE
Veracode scan reported very high vulnerability

### ISSUE THREAD

**Issue by sumitmorey** [ZipArchive/ZipArchive#665]
Hello There,
I am using SSZipArchive since many years in my app. Recent Veracode scan has reported a very high vulnerability, refer [this](https://sca.analysiscenter.veracode.com/vulnerability-database/security/arbitrary-file-write/objective-c/sid-38804) vulnerability database. Due to this I have to remove SSZipArchive from my app. I hope this will be fixed for benefit of all.

**Comment by Coeur** [comment]
Happy to wait for your Pull Request.
Assigning the issue to you.

**Comment by sumitmorey** [comment]
@Coeur  [Here]([here](https://sca.analysiscenter.veracode.com/vulnerability-database/security/arbitrary-file-write/objective-c/sid-38804)) is the Veracode error. Raising a PR would take time.

**Comment by jhudsonWA** [comment]
We believe this is the same report as #662 and was fixed in 2.5.4.
