### ISSUE TITLE
Does SSZipArchive support brotli uncompress?

### ISSUE THREAD

**Issue by wizardch** [ZipArchive/ZipArchive#670]
I want to know whether SSZipArchive supprot brotli uncompress? Thank you

**Comment by Coeur** [comment]
https://manpages.ubuntu.com/manpages/jammy/en/man1/brotli.1.html
>brotli file format is defined in RFC 7932 https://www.ietf.org/rfc/rfc7932.txt.

So the answer is NO.
ZipArchive only supports the .ZIP file format, which is defined in https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT
