### ISSUE TITLE
"...minimum platform version 15.5 for the iOS platform..."

### ISSUE THREAD

**Issue by olibar27** [ZipArchive/ZipArchive#671]
### Steps to reproduce
1. Add SwiftXLSX
2. Add ZipArchive
3. = Error "The package product 'ZipArchive' requires minimum platform version 15.5 for the iOS platform, but this target supports 11.0"

### Expected behavior
Error should not occur because Deployment target is set to 16.2!

### Actual behavior
See Error above.

### Version of ZipArchive
2.5.4

### Environmental information
Xcode 14.2 using SwiftUI 5.7

**Comment by Coeur** [comment]
Well, how did you "Add ZipArchive"?
- CocoaPods? Then configure the min target in your .podfile
- Carthage? Then configure it in your .cartfile I suppose?
- Subproject? Then configure the deployment target of your subproject.

Deployment targets of the main Xcode project doesn't automatically supersedes or overrides those of dependencies.
