### ISSUE TITLE
unzipping not working

### ISSUE THREAD

**Issue by f15radar** [ZipArchive/ZipArchive#673]
I have the following code:

        print("Zippath is "+zippath)
        print("unzippath is "+unzippath)
        print("url path is "+url.path)
        let fileManager1 = FileManager.default
        if fileManager1.fileExists(atPath: zippath) {
             print("Archive exists")
        }
        if fileManager1.isWritableFile(atPath: unzippath){
             print("dir writable")
         }
        do
            {
                try SSZipArchive.unzipFile(atPath: zippath, toDestination: unzippath, overwrite: true,password:"icp")
            }
            catch
            {
            print("error unzipping")
            }
        print("after unzip")

Here is my output:

Zippath is /var/mobile/Containers/Data/Application/DCE37610-39D1-4E94-8690-8178D50C571D/Documents/file.csvallpics.ggg
unzippath is /var/mobile/Containers/Data/Application/DCE37610-39D1-4E94-8690-8178D50C571D/Documents/unzip
url path is /var/mobile/Containers/Data/Application/DCE37610-39D1-4E94-8690-8178D50C571D/Documents
Archive exists
dir writable
error unzipping
after unzip

I have checked the zipped up file and it is valid, although I don't think there is a password.  I also tried with a blank password and received the same error.

I followed the code down and saw a 107 error

What is a 107 error and why is this not working?

**Comment by f15radar** [comment]
More information. The zip file is create with SSZipArchive and is greater then 6gb. I tried using a smaller file and it works. Can i not unzip files greater then 6gb?

**Comment by f15radar** [comment]
It looks like the zip file which was created with ZipArchive is somehow corrupt.  Now to try and figure out why.

**Comment by f15radar** [comment]
So I am very perplexed, can someone help me? I have 4400 pictures in an iPhoneXR.  When I run them thru the createzip using the documents directory, 1 file always gets messed up.  When I say messed up, if I look at it using 7 zip, 1 file (not the same file everytime) is currupted.  One time it was file 1566, last time it was 465.  What could the problem be?  I have been working on this for days now.

**Comment by Coeur** [comment]
https://github.com/ZipArchive/ZipArchive/blob/be6ac340cbe394cc6a81eae6034a91a7702d9db3/SSZipArchive/minizip/mz.h#L36

Possibly some file was already existing? Like duplicate filepath?

**Comment by Coeur** [comment]
>Can i not unzip files greater then 6gb?

Yes you can.

I'll close the issue for now, as it lacks reproduction steps. If you can share a file which has issues, we can reopen this and hopefully fix it.
