### ISSUE TITLE
About directory backtracking

### ISSUE THREAD

**Issue by rand01m** [ZipArchive/ZipArchive#675]
https://github.com/ZipArchive/ZipArchive/blob/b56f8c605a233fb25fe8d49f1b9ed50912c2d1b7/SSZipArchive/SSZipArchive.m#L1448

This line of code still cannot prevent directory backtracking, which should be "a/b/../c.txt" -> "a/b/c.txt"

**Comment by Coeur** [comment]
Why should it be "a/b/c.txt"? The author of the archive can set any path they want under ".", and returning "a/c.txt" is fine and likely the desired behavior.
