### ISSUE TITLE
ssziparchive leaks

### ISSUE THREAD

**Issue by zhangjiang1203** [ZipArchive/ZipArchive#683]
### Steps to reproduce
1.use xcode debug memory graph tool
2.location  ziparchive malloc is not free
3.
 `

          char *filename = (char *)malloc(fileInfo.size_filename + 1);
          if (filename == NULL)
          {
              success = NO;
              break;
           }
          unzGetCurrentFileInfo(zip, &fileInfo, filename, fileInfo.size_filename + 1, NULL, 0, NULL, 0);
          filename[fileInfo.size_filename] = '\0';
          
          BOOL fileIsSymbolicLink = _fileIsSymbolicLink(&fileInfo);
          
          NSString * strPath = [SSZipArchive _filenameStringWithCString:filename size:fileInfo.size_filename];
          if ([strPath hasPrefix:@"__MACOSX/"]) {
              // ignoring resource forks: https://superuser.com/questions/104500/what-is-macosx-folder
              unzCloseCurrentFile(zip);
              ret = unzGoToNextFile(zip);
              continue;
            }
`

when `[strPath hasPrefix:@"__MACOSX/"])` is true, the filename is not free
### Expected behavior
so when `[strPath hasPrefix:@"__MACOSX/"]` to free filename

### Actual behavior
Tell us what happens instead

**Comment by Coeur** [comment]
Sorry, but not funny.
I fixed this six years ago: https://github.com/ZipArchive/ZipArchive/commit/924b924
Please don't open issues for extremely outdated versions of the project.
