### ISSUE TITLE
uncompressed_size is not right

### ISSUE THREAD

**Issue by bdtren** [ZipArchive/ZipArchive#685]
### Steps to reproduce
1. Have a big zip file. (My zip file is 4.5GB unzipped and 330MB zipped with only 1 DB file inside)
2. call `NSNumber *wantedFileSize = [SSZipArchive payloadSizeForArchiveAtPath:path error:&error];`
3. Check the value of wantedFileSize

### Expected behavior
Value of wantedFileSize is the uncompressed size (4.5GB)

### Actual behavior
Value of wantedFileSize is just 928MB

### Version of ZipArchive
Tested in `2.2.0` and `2.5.4`

### Environmental information
iPhone XS (iOS 16.3.1)
iPhone 14 Pro Max (iOS 16.1)

PS: I checked function `payloadSizeForArchiveAtPath` and can be sure that the issue is from `fileInfo.uncompressed_size` as it is showing that same value 928MB (9726543314)

**Comment by Coeur** [comment]
Maybe there are symlinks in the archive?
Depending of the operating system, symlinks may or may not count toward the final uncompressed_size.
Can we get insight of which tool you used to create that archive?

**Comment by Coeur** [comment]
If I read correctly, you only have 1 single file? So no symlinks I guess.
