### ISSUE TITLE
iOS 17 New required reason API

### ISSUE THREAD

**Issue by lakshmankreditbee** [ZipArchive/ZipArchive#687]
From Apple's newly published document ["Describing use of required reason API"](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api):

> Your app or third-party SDK must declare one or more approved reasons that accurately reflect your use of each of these APIs and the data derived from their use. You may use these APIs and the data derived from their use for the declared reasons only. These declared reasons must be consistent with your app’s functionality as presented to users, and you may not use the APIs or derived data for tracking.

Will ZipArchive be either removing the use of these APIs or providing a privacy manifest file for the iOS SDK? Or perhaps are you in contact with Apple about this issue?

**Comment by Coeur** [comment]
Hi Sree.
I haven't published apps for years, so I wasn't aware of this issue. Thank you for the link.
Looking at the list of APIs:

- [creationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1418187-creationdate)
- [modificationDate](https://developer.apple.com/documentation/foundation/fileattributekey/1410058-modificationdate)

We use them once in ZipArchive:
https://github.com/ZipArchive/ZipArchive/blob/1d2c7b604c74b9eef0b99bfc83f07f4c29216e13/SSZipArchive/SSZipArchive.m#L491
It's behind a `if (preserveAttributes)`, so eventually we could change that one to a build time MACRO for those who never want to preserveAttributes. But a manifest would be needed for those who prefer to keep the original creationDate and modificationDate of files when unzipping them.

- [stat](https://developer.apple.com/documentation/kernel/stat)
- `lstat(_:_:)`

We use them multiple times in minizip:
https://github.com/ZipArchive/ZipArchive/blob/1d2c7b604c74b9eef0b99bfc83f07f4c29216e13/SSZipArchive/minizip/mz_os_posix.c#L176
https://github.com/ZipArchive/ZipArchive/blob/1d2c7b604c74b9eef0b99bfc83f07f4c29216e13/SSZipArchive/minizip/mz_os_posix.c#L249
Those are essential to zip and unzip files. And it's a third-party dependency that we normally don't alter. So a manifest seems unavoidable.

And that's all the matching symbols that I could find in the code.
PR welcome for adding a manifest.

**Comment by Coeur** [comment]
Fixed in #688

**Comment by jhudsonWA** [comment]
Released in 2.5.5

**Comment by lakshmankreditbee** [comment]
can you guys share your twitter Account, we are buddies now. Sending Positive Vibes.
