### ISSUE TITLE
Apple's update to their API policy - Required Reason

### ISSUE THREAD

**Issue by peterdestasio** [ZipArchive/ZipArchive#690]
### Problem
Apple is requiring all api calls that fall under this ruleset https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api
be added to a privacy manifest file.

### Feature Request
Some APIs that your app uses to deliver its core functionality — in code you write or included in a third-party SDK — have the potential of being misused to access device signals to try to identify the device or user, also known as fingerprinting. Regardless of whether a user gives your app permission to track, fingerprinting is not allowed. Describe the reasons your app or third-party SDK on iOS, iPadOS, tvOS, visionOS, or watchOS uses these APIs, and check that your app or third-party SDK only uses the APIs for the expected reasons.

nb. this is a requirement by Apple and it will be enforced by Spring 2024: https://developer.apple.com/news/?id=z6fu1dcu#:~:text=And%20starting%20in%20spring%202024,your%20app%20uses%20the%20API.

**Comment by Coeur** [comment]
It was added Oct 3, 2023: #688.
And is available in a release since that same day: https://github.com/ZipArchive/ZipArchive/releases/tag/2.5.5
