### ISSUE TITLE
Crash when zip large files

### ISSUE THREAD

**Issue by DikeyKing** [ZipArchive/ZipArchive#697]
### Steps to reproduce
1. Zip large files using `+ (BOOL)createZipFileAtPath:(NSString *)path withContentsOfDirectory:(NSString *)directoryPath`
2. Memory inceaced rapidly to 3.28GB
3. App crashed 

### Expected behavior
Do not crash and use less memory as tested OK in iPhone 13 Pro Max with 6GB memory

### Actual behavior
Out of memory in iPhone 13 and crashed

### Version of ZipArchive
2.4.3

### Environmental information
iOS 15.6.1 iPhone 13

![crash_1](https://github.com/ZipArchive/ZipArchive/assets/7019111/a576eff0-9be0-443b-82e5-2eca3bba3ce5)
![crash_2](https://github.com/ZipArchive/ZipArchive/assets/7019111/5d37ee59-9d57-4dac-89c7-2ea9cb5300c2)

**Comment by Coeur** [comment]
If you can confirm it's a bug, then kindly try to offer a fix via a pull request.

**Comment by Coeur** [comment]
Oh wait, you're on 2.4.3 ? Sorry, it's an obsolete version. Try 2.5.x or newer.
