### ISSUE TITLE
Ziparchive Privacy manifest keys are not reflecting in Project privacy report

### ISSUE THREAD

**Issue by rinkusadhwani** [ZipArchive/ZipArchive#698]
I am using sslziparchive library in our project through cocoapods.
We are using latest version which has manifest file added.

When i am generating final project level report from archive, Privacy Keys from ziparchive is not included in the report.
other sdks keys are properly coming in the report.

### Expected behavior
As per apple guideline all third party sdk keys should get reflected in project level privacy report combinly.

### Environmental information
Xcode 15.2.

**Comment by rinkusadhwani** [comment]
Hi Team, We have release planned in next few days and this issue should be fixed before that otherwise apple will reject the application

Most of the third party sdks showing keys properly in privacy report but ziparchive not.
Please do the needfull. Thanks

**Comment by Coeur** [comment]
It was done 6 months ago already:
https://github.com/ZipArchive/ZipArchive/pull/688

And properly released:
https://github.com/ZipArchive/ZipArchive/releases/tag/2.5.5

If there is a bug in the implementation that is only affecting you but not others, then try to figure it out and code a pull request for it.

**Comment by rinkusadhwani** [comment]
Hi,

I am already using the latest version of it.

Everything is working fine but ziparchive keys are not reflecting in
project privacy report.

Thanks,
Rinku

**Comment by angusryer** [comment]
@rinkusadhwani I'm experiencing something similar, but for me it is related to [this issue in react-native-code-push](https://github.com/microsoft/react-native-code-push/issues/2679#issuecomment-2034974534)

**Comment by Coeur** [comment]
>Hi Team, We have release planned in next few days and this issue should be fixed before that otherwise apple will reject the application

I imagine that you've solved your problem, because it would be surprising that someone abandons updating their app for 6 months without giving news.

Not seeing any pull request, I guess the issue was in your configuration.
