### ISSUE TITLE
Using SSZipArchive to decompress found that the CPU skyrocketed more than 100%, causing the APP to crash

### ISSUE THREAD

**Issue by zzq1059201979** [ZipArchive/ZipArchive#707]
### Steps to reproduce
1.Using SSZipArchive to decompress found that the CPU skyrocketed more than 100%, causing the APP to crash
2.Use version numbers: 14.3, 16.3, 17.4.1 and so on versions are all the same CPU inflation
3.Directly use the local compressed file of the project to decompress, the compressed file is about 10MB, found that the CPU hovers around 100%

**Comment by Coeur** [comment]
Please provide a sample file.

**Comment by Coeur** [comment]
Those are iOS version numbers. Since you have access to the CPU usage, it means you were monitoring it with Xcode.
Then please attach a crash report and an **Instruments** report.
https://developer.apple.com/videos/play/wwdc2023/10248/
