### ISSUE TITLE
2.4.3 Is the version stable?

### ISSUE THREAD

**Issue by beibeiGeng** [ZipArchive/ZipArchive#708]
Due to project reasons, we want to continue to use version 2.4.3. For this version, we would like to ask whether this version can continue to be used normally? Can I ask for help if I have any usage problems?

**Comment by Coeur** [comment]
I would recommend instead to use the latest version (2.5.5 currently) and manually changing the deployment_target version if that is a must for you.

Closing the issue, because no support will be given for older releases.
