### ISSUE TITLE
Can't compress single file, only directory

### ISSUE THREAD

**Issue by pkasson** [ZipArchive/ZipArchive#711]
### Steps to reproduce
1.  let fileToZip = samplePath + "/snippets.json"
2.  let success = SSZipArchive.createZipFile(atPath: zipPath!, withFilesAtPaths: [fileToZip], withPassword: !password.isEmpty ? password : nil)

Always fails.

### Expected behavior
Zip should succeed

### Actual behavior
Zip fails

### Version of ZipArchive
Latest

**Comment by Coeur** [comment]
Can you make a pull request to fix it?

**Comment by Coeur** [comment]
Actually, I just tried it myself, and it works fine.
So your issue is lacking a reproducible example.
Just double check that you have read permission for the input and write permission for the output.
