### ISSUE TITLE
Large File - 

### ISSUE THREAD

**Issue by lprhodes** [ZipArchive/ZipArchive#73]
Hi,

The file I'm unzipping has just grown to 2.3GB and I'm now getting UNZ_BADZIPFILE while unzipping. The unzipped file is around 7GB.

The error is occurring in the following check:

```
    if ((number_entry_CD!=us.gi.number_entry) ||
        (number_disk_with_CD!=0) ||
        (number_disk!=0))
        err=UNZ_BADZIPFILE;
```

The documentation of this makes it sound like it's getting an incorrect number of files from the zip archive - is that right?

I'm just using the built in compress tool in OS X to compress the file (as has worked previously).

Thanks!

Luke

**Comment by kccheung** [comment]
Hi,

I got a similar problem while unzipping a large zip file (3.37 GB). I run into error in the following statements in unzip.c:

```
    if (err==UNZ_OK)
    {
        if (unz64local_getLong(&s->z_filefunc, s->filestream,&uMagic) != UNZ_OK)
            err=UNZ_ERRNO;
        else if (uMagic!=0x04034b50)
            err=UNZ_BADZIPFILE;
    }
```

I got `uMagic == 0`, may I know what is `uMagic` and is there a way to extract my large zip file?

**Comment by jhudsonWA** [comment]
Good question. All that code comes from upstream in the minizip package.

**Comment by kccheung** [comment]
Hi, may I know if giant zip file still be supported in this library? If not I would have a try on other library like objective-zip.

**Comment by jhudsonWA** [comment]
I don't know of any support that was removed. But looking at objective-zip
it uses the same upstream library as we do (minizip)
